### ISSUE TITLE
[Feature Request] - GPU AMIs, NVIDIA drivers, CUDA support: i.e. allowing use of GPUs on GPU instance types

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2023#12]
GPU instance types tend to require additional software to take advantage of the GPUs. Much like the GPU AMIs available for AL2, we want them for AL2022.

**Comment by bryantbiggs** [comment]
Related issues:
- https://github.com/amazonlinux/amazon-linux-2023/issues/316
- https://github.com/amazonlinux/amazon-linux-2023/issues/168
- https://github.com/amazonlinux/amazon-linux-2023/issues/183

**Comment by bryantbiggs** [comment]
would this include NCCL? Ref https://github.com/amazonlinux/amazon-linux-2023/issues/491 which relies on NCCL

**Comment by stewartsmith** [comment]
NVIDIA now has documentation on using their drivers on AL2023. See https://docs.nvidia.com/cuda/pdf/CUDA_Quick_Start_Guide.pdf

**Comment by rdelcampog** [comment]
@stewartsmith Any ETA for this? Lots of projects are on hold waiting for this 😇

**Comment by limmike** [comment]
You can refer to [How do I install NVIDIA GPU driver, CUDA toolkit and optionally NVIDIA Container Toolkit on Amazon Linux 2023 (AL2023)?](https://repost.aws/articles/ARwfQMxiC-QMOgWykD9mco1w/how-do-i-install-nvidia-gpu-driver-cuda-toolkit-and-optionally-nvidia-container-toolkit-on-amazon-linux-2023-al2023) for user data script.

**Comment by jacob-talroo** [comment]
FYI - I am following this ticket so that we _don't_ have to do anything else to use the latest Linux with Nvidia drivers on AWS.  We desire simplicity.

Our use case is bringing up these instances quickly.  So, if there are extra install steps, this adds to our scale uptime.  Of course, we can package our own AMI, but this is sophisticated.  An additional benefit of AWS bundling a recent version of Linux and Nvidia drivers together is AWS supporting this configuration.

If this simplicity is not the desired goal of this ticket, let me know and I'll file another one.

**Comment by limmike** [comment]
Thanks for sharing your use case.  Included the link in case others wants to build their instances first while waiting.

**Comment by ozbenh** [comment]
Thanks for the feedback. We are looking at improving the integration of the nVidia driver packages. I cannot yet say wether we'll have a dedicated AMI or not (or if another AWS team will produce one) but we are investigating removing the need to source packages from elsewhere.

**Comment by sammcj** [comment]
Really keen to see some CUDA AL2023 AMIs made available, installing cuda-toolkit nvidia-container-toolkit and the nvidia-driver in a user script is painfully slow.

**Comment by bryantbiggs** [comment]
If using containers, the CUDA toolkit isn't recommended on the host - CUDA will be provided within your application container as a user space dependency

**Comment by sammcj** [comment]
@bryantbiggs can you still pass through runtime: nvidia and deploy with driver:nvidia though?

If not, that breaks compatibility with non-AWS deployments, container images and compose files.

**Comment by bryantbiggs** [comment]
I don't follow - but I suspect yes. 

Take PyTorch as an example - that is installed in your container (either via pip install or by using one of the PyTorch public images) and it provides the CUDA libraries that it requires so the massive install of the CUDA toolkit on your host isn't used

**Comment by sammcj** [comment]
Ohh, sorry I was thinking of the container toolkit 🤦, yes you're quite right!

**Comment by stewartsmith** [comment]
The `nvidia-release` package, added in the [2023.6.20241031 release](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.6.20241031.html) will enable an RPM package repository with NVIDIA drivers available for installation.

(more documentation updates are to come)

**Comment by stewartsmith** [comment]
As such, I'm going to resolve this issue, and will comment in the future with links to documentation.
