### ISSUE TITLE
[Feature Request] - rsyslog - enable mmtaghostname

### ISSUE THREAD

**Issue by elruwen** [amazonlinux/amazon-linux-2023#122]
**Is your feature request related to a problem? Please describe.**
Rsyslog has the useful module mmtaghostname. I use it when I build an rsyslog sidecar. I use the syslog tag to route logs to the correct place. This plugin allows me to easily adjust the hostname and the tag to pre-defined values.

From the rsyslog documenation (https://www.rsyslog.com/doc/master/configuration/modules/mmtaghostname.html)
```
The purposes are:
- to add a tag on message produce by input module which does not provide a tag like imudp or imtcp. Useful when the tag is used for routing the message.
- to force message hostname to the rsyslog valeur. AWS Use case : applications in auto-scaling systems provides logs to rsyslog through udp/tcp. As a result of auto-scaling, the name of the host is based on an ephemeral IPs (short term meaning). In this situation rsyslog local hostname is generally closed to business rule. So replacing hostanme received by the rsyslog local Hostname provide values to the logs collected.
```

**Describe the solution you'd like**
The module is part of the rsyslog source code. Just add to `./configure` `--enable-mmtaghostname` and that's it.

**Describe alternatives you've considered**
I am currently building rsyslog myself. I would like to avoid that.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests and will reply to this ticket by with our evaluation.

**Comment by elruwen** [comment]
For everybody else out there: I managed to submit a PR to alpine linux, they merged and released it: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/48893/diffs so you can `apk add rsyslog-mmtaghostname` to get it.

**Comment by stewartsmith** [comment]
I've made a PR upstream to Fedora in https://src.fedoraproject.org/rpms/rsyslog/pull-request/40 and we're looking at enabling the module in an upcoming AL2023 release.

I haven't found any good short description of the use cases of it, so the text in the package summary and description isn't great. If you have some suggested text, I'd happily take it and use it!

**Comment by stewartsmith** [comment]
FYI the pull request to the Fedora package was accepted, and this will be part of an upcoming AL2023 release.

**Comment by stewartsmith** [comment]
This has now been included in the Amazon Linux 2023 repositories.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
