### ISSUE TITLE
[Package Request] - Monit

### ISSUE THREAD

**Issue by yantene** [amazonlinux/amazon-linux-2023#124]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

Monit is an utility for managing and monitoring, processes, files, directories and devices on a *NIX system.

**Is this an update to existing package or new package request?**

New package.

**Is this package available in Amazon Linux 2?**

Yes, monit is available via EPEL. They are also available in Fedora 34.

**Number of users impacted**

Monit is one of the most popular process monitoring tools.

**Comment by stewartsmith** [comment]
We have [added documentation regarding `monit` and how `systemd` is now the preferred replacement for service monitoring](https://docs.aws.amazon.com/linux/al2023/ug/epel.html#monit). There are many advantages of using `systemd` units for the functionality provided by `monit`.

I'm going to resolve this issue as we are not currently planning on adding `monit` to AL2023.
