### ISSUE TITLE
[Package Request] - lcov

### ISSUE THREAD

**Issue by adam-azarchs** [amazonlinux/amazon-linux-2023#128]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

`lcov` - tools for working with code coverage data.  epel 7 package referred to [sourceforge repo](http://ltp.sourceforge.net/coverage/lcov.php) but more current versions on [GitHub](https://github.com/linux-test-project/lcov).

**Is this an update to existing package or new package request?**

New to AL2022.

**Is this package available in Amazon Linux 2?**

Yes, via epel, though a somewhat out of date version.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - this is now part of AL2023.4
