### ISSUE TITLE
[Feature Request] - ECS ARM image

### ISSUE THREAD

**Issue by carstenblt** [amazonlinux/amazon-linux-2023#143]
Right now ecs-hvm images are only available for for x86, not for arm64. When will they be released?

**Comment by mssrivas** [comment]
Hello, thank you for submitting your request! arm64 is expected to release with GA of AL2022

**Comment by at-wat** [comment]
AL2023 is GA, but ecs-optimized images seem not provided yet. (neither x86_64 nor arm64)
Is there a targeted schedule for this?

**Comment by at-wat** [comment]
ECS-optimized AL2023 seems be available for both x86_64 and arm64 now.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html
> - For the Amazon ECS-optimized Amazon Linux 2023 AMIs:
>     ```
>     aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended --region us-east-1
>     ```
> - For the Amazon ECS-optimized Amazon Linux 2023 (arm64) AMIs:
>     ```
>     aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2023/arm64/recommended --region us-east-1
>     ```
