### ISSUE TITLE
[Package Request] - net-snmp

### ISSUE THREAD

**Issue by youjio** [amazonlinux/amazon-linux-2023#144]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
net-snmp

**Is this an update to existing package or new package request?**
Missing

**Is this package available in Amazon Linux 2?**

```
$ sudo dnf search net-snmp --refresh
Amazon Linux 2022 repository 
No matches found.

$ cat /etc/image-id 
image_name="al2022-ami"
image_version="2022"
image_arch="x86_64"
image_file="al2022-ami-2022.0.20220728.1-kernel-5.15-x86_64.xfs.gpt"
image_stamp="207c-c0b7"
image_date="20220728172608"
recipe_name="al2022 ami"
recipe_id="2caab3fc-cb8b-5512-6bfc-0939-7895-7e12-7d17ae5c"
```
But al2022-ami-20220531 was ok.
```
$ sudo dnf search net-snmp --refresh
Amazon Linux 2022 repository
========================================================================
net-snmp.x86_64 : A collection of SNMP protocol tools and libraries

$ cat /etc/image-id 
image_name="al2022-ami-minimal"
image_version="2022"
image_arch="x86_64"
image_file="al2022-ami-minimal-2022.0.20220531.0-kernel-5.15-x86_64.xfs.gpt"
image_stamp="a518-2e04"
image_date="20220614234755"
recipe_name="al2022 ami"
recipe_id="d9866978-2069-b160-1617-5bef-cc70-083c-66318a29"
```

**Number of users impacted**

**Comment by stewartsmith** [comment]
The `net-snmp` package is one that we removed during the Tech Preview prior to RC due to low usage on prior Amazon Linux versions. We'd be interested to know your use case.

**Comment by youjio** [comment]
If a company or other organization already has a monitoring infrastructure system in place before migrating to AWS and wishes to continue to operate that infrastructure, SNMP monitoring is set up in the same way as in an on-premise environment.

**Comment by watomlinson** [comment]
We have been using net-snmp for monitoring through Nagios as well as collecting stats from devices that support SNMP. For example, we graph UPS power statistics using Grafana and a key component is being able to use SNMP.

**Comment by h-homma** [comment]
We need net-snmp too, to monitor system resources of EC2 instances. CloudWatch is not enough to monitor, for example, details of CPU usage (system, user, iowait, etc).

**Comment by donikatz** [comment]
We also require net-snmp for existing infrastructure monitoring. SNMP remains a common standard.

**Comment by mdraugh** [comment]
Same here.  All of our monitoring and our inventory system rely on SNMP; without it, I can't use Amazon Linux 2023 at all.

**Comment by 13pratikmohite** [comment]
You can still configure your favourite repo. 
Like 
1. get your repo keys  rpm -Uvh https://rpmfind.net/linux/fedora-secondary/releases/37/Everything/s390x/os/Packages/f/fedora-gpg-keys-37-1.noarch.rpm
2. configure repo under /etc/yum.repos.d/<>.repo, with kind of below  values
```
[fedora-extra]
name=Fedora Modular fedora-server-37-x86_64
failovermethod=priority
baseurl=https://mirrors.ustc.edu.cn/fedora/releases/37/Everything/x86_64/os/
enabled=1
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-37-x86_64
skip_if_unavailable=False
```
Note: select base url based on the OS you are using.

**Comment by ozbenh** [comment]
Note that we do no recommend not support running packages from Fedora, RHEL or EPEL on AL2023, do this at your own risk

**Comment by gizmonicus** [comment]
> You can still configure your favourite repo. Like
> 
> 1. get your repo keys  rpm -Uvh https://rpmfind.net/linux/fedora-secondary/releases/37/Everything/s390x/os/Packages/f/fedora-gpg-keys-37-1.noarch.rpm
> 2. configure repo under /etc/yum.repos.d/<>.repo, with kind of below  values
> 
> ```
> [fedora-extra]
> name=Fedora Modular fedora-server-37-x86_64
> failovermethod=priority
> baseurl=https://mirrors.ustc.edu.cn/fedora/releases/37/Everything/x86_64/os/
> enabled=1
> repo_gpgcheck=0
> type=rpm
> gpgcheck=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-37-x86_64
> skip_if_unavailable=False
> ```
> 
> Note: select base url based on the OS you are using.

This is not an acceptable solution. The point is: net-snmp is a package that is still used, for better or for worse, in enterprise environments and we should not need to go off script to find it through some third party repo or by rolling our own. I don't agree with using "due to low usage" as a metric for removing a package from standard repositories. There are plenty of packages we don't regularly use that we still need for various legacy applications or hardware. That's just the nature of the business.

The lack of response to this issue, and others, has forced me to rethink my strategy when it comes to Linux in AWS. We've found that Rocky 9 supports all of the required packages for our needs and we've opted not to proceed with any future Amazon Linux deployments as a result.

**Comment by gizmonicus** [comment]
> @gizmonicus net-snmp will be added to an upcoming AL2023 release. I don't have an ETA for it at this time.

That's good to hear, although it's too late at this point for us to consider AL2023 anymore. Package availability is absolutely critical to the success of any Linux distribution in my mind. Any time a third party repo is needed for basic functionality, you're opening yourself up yet another vector for supply chain attacks, and compiling/mantaining/distributing software packages ourselves is taxing on administrative teams. I understand that there's a delicate balance between supporting a large number of packages and restricting package selection to ensure maximum stability and compatibility, but in my opinion AL2023 went too far down the wrong path.

**Comment by nmeyerhans** [comment]
net-snmp is available in current AL2023 releases.
```
bash-5.2# rpm -q system-release
system-release-2023.0.20230614-0.amzn2023.noarch
bash-5.2# dnf list net-snmp*
Last metadata expiration check: 0:00:42 ago on Wed Jun 14 15:18:02 2023.
Available Packages
net-snmp.x86_64                         1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-agent-libs.x86_64              1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-devel.x86_64                   1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-gui.x86_64                     1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-libs.x86_64                    1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-perl.x86_64                    1:5.9.3-2.amzn2023.0.2              amazonlinux
net-snmp-utils.x86_64                   1:5.9.3-2.amzn2023.0.2              amazonlinux
```
