### ISSUE TITLE
dnf reposync  amazonlinux  - ERROR

### ISSUE THREAD

**Issue by subhashsapkal** [amazonlinux/amazon-linux-2023#165]
while running
dnf reposync -id amazonlinux

Below error gets displayed:
RE:[CASE 10491348151] Error libss-1.45.6-5.amzn2022.x86_64 Download target '/blobstore/678daa1a1aa2043326286ab91cda70642486365bca112b435970c6ea375fb304/libss-1.45.6-5.amzn2022.x86_64.rpm' is outside of download path

**Comment by stewartsmith** [comment]
Work is being done to address this: https://github.com/rpm-software-management/dnf-plugins-core/pull/457

**Comment by subhashsapkal** [comment]
@stewartsmith , 

Any update on this issue?

**Comment by subhashsapkal** [comment]
@stewartsmith 

Any update on this repository bug?

Subhash
New York

**Comment by stewartsmith** [comment]
This should be fixed in the 2023.0.20230315 GA release.

We are also working on getting the support upstream.
