### ISSUE TITLE
[Package Request] - `wireguard-tools`

### ISSUE THREAD

**Issue by mwberry** [amazonlinux/amazon-linux-2023#167]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

`wireguard-tools` - the userspace tooling to interact with the Wireguard kernel module

**Is this an update to existing package or new package request?**

New package requeset

**Is this package available in Amazon Linux 2?**

Yes, via `epel`

**Number of users impacted**

Uncertain. Wireguard is a popular secure tunnel protocol and has built-in support in Linux since kernel 5.6

**Comment by walmartshopper** [comment]
I would like to see this as well.  My use case is to run my own private wireguard VPN server. I am currently running the AL2022 minimal AMI on a 2GB root volume on a t4g.nano instance with a 3 year RI.  It amounts to about $2/month (for up to 100GB traffic, then bandwidth costs kick in).

For now I was able to install wireguard-tools from the Fedora 36 repo and it's working fine with no dependency issues.

**Comment by nmeyerhans** [comment]
We'll be including wireguard-tools in an upcoming AL2023 release. No ETA at this time.

**Comment by stewartsmith** [comment]
On Amazon Linux 2023.0.20230503:
```
bash-5.2# dnf list wireguard-tools
Last metadata expiration check: 0:17:04 ago on Fri May  5 19:34:40 2023.
Available Packages
wireguard-tools.aarch64           1.0.20210914-4.amzn2023            amazonlinux
```
