### ISSUE TITLE
[Bug] - rsyslog default configuration has errors

### ISSUE THREAD

**Issue by petercooperjr** [amazonlinux/amazon-linux-2023#178]
**Describe the bug**
After installing rsyslog, the default /etc/rsyslog.conf that comes with it has duplicated lines which show as errors when the service starts.

**To Reproduce**
1. Start an EC2 instance in us-east-1 with AMI ami-0388d7f179c9861d0 (al2022-ami-minimal-2022.0.20220831.1-kernel-5.15-arm64) and connect to it.
2. Switch to root: `sudo -i`
3. Install rsyslog: `dnf install rsyslog -y`
4. Start the service: `systemctl start rsyslog`
5. Look at log from the service: `journalctl -u rsyslog`
6. Notice that the log contains errors about the contents of the configuration file /etc/rsyslog.conf, about modules already in the config and "error during parsing file"

**Expected behavior**
No errors from startup with the default configuration.

**Screenshots**
```
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal systemd[1]: Starting rsyslog.service - System Logging Service...
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: module 'imuxsock' already in this config, cannot be added  [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/2221 ]
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: error during parsing file /etc/rsyslog.conf, on or before line 24: parameter 'SysSock.Use' not known -- typo in config file? [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/2207 ]
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: module 'imjournal' already in this config, cannot be added  [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/2221 ]
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: error during parsing file /etc/rsyslog.conf, on or before line 27: parameter 'StateFile' not known -- typo in config file? [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/2207 ]
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: [origin software="rsyslogd" swVersion="8.2204.0-1.amzn2022.0.3" x-pid="9866" x-info="https://www.rsyslog.com"] start
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: imjournal: No statefile exists, /var/lib/rsyslog/imjournal.state will be created (ignore if this is first run): No such file or directory [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/2040 ]
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal systemd[1]: Started rsyslog.service - System Logging Service.
Sep 01 10:36:27 ip-172-31-55-125.ec2.internal rsyslogd[9866]: imjournal: journal files changed, reloading...  [v8.2204.0-1.amzn2022.0.3 try https://www.rsyslog.com/e/0 ]
```

**Additional context**
While log files were all in `/var/log` in Amazon Linux 2, in Amazon Linux 2022 the default is to just have logs in the systemd journal. If the log files need to be created for easy integration with other systems that read them, rsyslog needs to be installed. However, the default configuration shouldn't include those duplicated sections. (And from my reading of the rsyslog documentation, it should be more efficient to integrate with the journal using just the imuxsock input module rather than imjournal, though perhaps Amazon Linux 2022 needs to use imjournal for some reason.)

And for what it's worth, the "other systems that read them" that I'm using is the amazon-cloudwatch-agent. Really it'd be great if the standard cloudwatch agent could just read from the journal directly rather than needing to have the logs in a file first. There are third-party programs available to send logs straight from the journal to cloudwatch logs, but it seems like something Amazon should just provide out-of-the-box.

**Comment by keithaws** [comment]
This issue has been resolved with the release of `rsyslog-8.2204.0-3.amzn2023.0.2`.
