### ISSUE TITLE
[Package Request] - NVIDIA Container Toolkit

### ISSUE THREAD

**Issue by amrragab8080** [amazonlinux/amazon-linux-2023#183]
Managed to get a workflow of successfully installing the NVIDIA driver (515.x) and Docker on AL2022 (20220831 - release) - however missing the [NVIDIA Container Toolkit ](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installation-guide)which is series of packages and dependencies.

nvidia-container-toolkit

For anyone wanting to run accelerated workloads in container.

**Comment by ozbenh** [comment]
This is now supported by nVidia directly: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/supported-platforms.html, their instructions for installing their dnf repo on AL2023 just work
