### ISSUE TITLE
[php-zip] - php zip extension

### ISSUE THREAD

**Issue by KenAir** [amazonlinux/amazon-linux-2023#195]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
php-zip extension

**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2?**
yes

**Number of users impacted**

**Comment by regattaman** [comment]
Migrated to new AWS server with linux 2022 but no longer have php-zip extension (php 8.1.7)

**Comment by bwaters** [comment]
please add php-zip

**Comment by bwaters** [comment]
so workaround you can build it with

sudo yum install php8.1-devel php-pear libzip libzip-devel
sudo pecl install zip
echo "extension=zip.so" | sudo tee /etc/php.d/20-zip.ini

**Comment by jacques** [comment]
Any ETA on getting this onto package to not have to install via pecl?

**Comment by katzueno** [comment]
We want php-zip

**Comment by ozbenh** [comment]
We are evaluating inclusion of this package in our next quarterly release

**Comment by kgrycuk** [comment]
For people using elastic beanstalk like me, add a config file like this to .ebextensions

```
files:
  "/etc/php.d/98_zip.ini":
    mode: "000644"
    owner: root
    group: root
    content: |
      extension=zip.so
commands:
  01_remove_old_config:
    command: "rm -f /etc/php.d/98_zip.ini.bak"
  02_install_stuff:
    command: "dnf -y install libzip libzip-devel"
  03_install_more_stuff:
    command: "pecl install zip"
```

**Comment by BobDankert** [comment]
> For people using elastic beanstalk like me, add a config file like this to .ebextensions
> 
> I'm using the pre-packaged php 8.2 elb image as of 8/17/23
> 
> ```
> files:
>   "/etc/php.d/98_zip.ini":
>     mode: "000644"
>     owner: root
>     group: root
>     content: |
>       extension=zip.so
> commands:
>   01_remove_old_config:
>     command: "rm -f /etc/php.d/98_zip.ini.bak"
>   02_install_stuff:
>     command: "dnf -y install libzip libzip-devel"
>   03_install_more_stuff:
>     command: "pecl install zip"
> ```

If you are using PHP 8.2 EB, you shouldn't need to create a PHP ini file to load the zip extension, this will be added automatically by the `pecl install zip` command. If you review the logs, you should see that listed at the bottom of the log for the command.

**Comment by kgrycuk** [comment]
> > For people using elastic beanstalk like me, add a config file like this to .ebextensions
> > I'm using the pre-packaged php 8.2 elb image as of 8/17/23
> > ```
> > files:
> >   "/etc/php.d/98_zip.ini":
> >     mode: "000644"
> >     owner: root
> >     group: root
> >     content: |
> >       extension=zip.so
> > commands:
> >   01_remove_old_config:
> >     command: "rm -f /etc/php.d/98_zip.ini.bak"
> >   02_install_stuff:
> >     command: "dnf -y install libzip libzip-devel"
> >   03_install_more_stuff:
> >     command: "pecl install zip"
> > ```
> 
> If you are using PHP 8.2 EB, you shouldn't need to create a PHP ini file to load the zip extension, this will be added automatically by the `pecl install zip` command. If you review the logs, you should see that listed at the bottom of the log for the command.

I must've read the line "As of PHP 8.2.0, php_zip.dll DLL must be enabled in php.ini. Previously, this extension was built-in."
from the windows section of https://www.php.net/manual/en/zip.installation.php

Let me double check

**Comment by santiagosantamaria** [comment]
> so workaround you can build it with
> 
> sudo yum install php8.1-devel php-pear libzip libzip-devel sudo pecl install zip echo "extension=zip.so" | sudo tee /etc/php.d/20-zip.ini

i did this with dnf and pecl 
but get the same error Class "ZipArchive" not found,
could anyone do this with php 8.2.9?

**Comment by BobDankert** [comment]
These are the commands I used, tested on the PHP 8.2.7 server using AMI ami-085405593c57273c3:

# Currently AL2023 doesn't support php-zip, so we have to install it manually. See https://github.com/amazonlinux/amazon-linux-2023/issues/195
sudo dnf install libzip libzip-devel
sudo pecl install zip

**Comment by ozbenh** [comment]
php-zip has now been released as part of AL2023.2 for php 8.2

**Comment by ozbenh** [comment]
Note: We released it as a separate `php8.2-zip` subpackage, not as part of `php8.2-common`

**Comment by gregory-claeyssens** [comment]
Would be great if it could have been added for PHP 8.1 as well.
