### ISSUE TITLE
[Package Request] - Missing Packages Libreswan

### ISSUE THREAD

**Issue by xavierpajona** [amazonlinux/amazon-linux-2023#198]
Hello,

As we are reviewing Amazon Linux 2022, we are really missing  the packages mlocate and Libreswan.
mlocate is more of a convenience thing, but very standard accross all linux distros as far as I know.
Libreswan is really central to our business and it would make it impossible for us to consider AmazonLinux2022 if it were not available.
Both were available on amazon Linux 2, and are also available standard on ubuntu 22.04, Redhat 8, etc.

Thanks for your help !

**Comment by stewartsmith** [comment]
`mlocate` is available in AL2022. Will keep this open for Libreswan request.

**Comment by waltercool** [comment]
+1 on this.

Amazon Linux 2 had amazon-linux-extras to enable epel, then install libreswan, but now as removed, we have no good options.

Suggestions to install libreswan under AL2023?

**Comment by nmeyerhans** [comment]
libreswan is available as of the AL2023.3 release just published.
