### ISSUE TITLE
[Bug] - Remove duplicate packages

### ISSUE THREAD

**Issue by elsaco** [amazonlinux/amazon-linux-2023#215]
AL2022 Version 2022.0.20221019

`pkgconf` and `pkgconf-pkg-config` are both installed. `pkgconf-pkg-config` is being pulled in as a dependency for `bash-completion`. This package was superseded by `pkgconf`.

**Comment by stewartsmith** [comment]
`pkgconf-pkg-config` is a wrapper around `pkgconf`, and is even provided by the same source package, and it exists for backwards compatibility. Is the request here to finish migrating packages away from using it and deprecate the wrapper?
