### ISSUE TITLE
[Bug] - Cannot upgrade to 2022.0.20221103 - python3-pip-wheel conflicts

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#220]
**Describe the bug**
I'm trying to upgrade my brand-new install of AL2022 - 2022.0.20220630 - to the latest release.

**To Reproduce**
Upgrade current instance to 2022.0.20221103
1. dnf distro-sync
```
Last metadata expiration check: 0:54:42 ago on Mon 14 Nov 2022 08:50:42 AM UTC.
Dependencies resolved.
Nothing to do.
Complete!
```
2. dnf upgrade --releasever=2022.0.20221103
```
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/share/python-wheels from install of python3-pip-wheel-21.3.1-2.amzn2022.0.4.noarch conflicts with file from package python-setuptools-wheel-53.0.0-2.amzn2022.noarch
  file /usr/share/python-wheels from install of python3-pip-wheel-21.3.1-2.amzn2022.0.4.noarch conflicts with file from package python-pip-wheel-21.0.1-4.amzn2022.noarch
```

**Expected behavior**
Complete upgrade to current release

**Comment by daniejstriata** [comment]
To upgrade I had to remove `python-setuptools-wheel` and `python-pip-wheel`

**Comment by christophershirk** [comment]
I've got the same issue.  How did you manage to remove those two python dnf packages without rendering your system unusable?

**Comment by stewartsmith** [comment]
It's best to launch a new AMI with a GA release of AL2023. There are a few bugs upgrading between Tech Preview releases that need different work-arounds.
