### ISSUE TITLE
[Package Request] - ccze

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#224]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
ccze

CCZE, a fast log colorizer written in C, intended to be a drop-in replacement for colorize. I use this to colorize tail's output when monitoring logs.

https://src.fedoraproject.org/rpms/ccze

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2?**
Yes

**Number of users impacted**

**Comment by daniejstriata** [comment]
Here is the RPM and SRPMS build from the SRC Package from EPEL9 for x86_64

[ccze-0.2.1-27.amzn2022.x86_64.zip](https://github.com/amazonlinux/amazon-linux-2022/files/10386220/ccze-0.2.1-27.amzn2022.x86_64.zip)
[ccze-0.2.1-27.amzn2022.src.zip](https://github.com/amazonlinux/amazon-linux-2022/files/10386221/ccze-0.2.1-27.amzn2022.src.zip)

**Comment by ozbenh** [comment]
The upstream for this appears dead, it hasn't been updated in Fedora for years and depends on PCRE1 which we are trying to deprecate, so unfortunately we cannot support this package.
