### ISSUE TITLE
[Package Request] - python3.10-pip

### ISSUE THREAD

**Issue by tiadobatima** [amazonlinux/amazon-linux-2023#228]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`python3.10-pip`.
Or preferably, have the `pip` module included in the `python3.10` package.

**Is this an update to existing package or new package request?**
New package for `python3.10`.
A `python3-pip` package already exists, but it installs only under `python3.9's site-packages`.

**Is this package available in Amazon Linux 2?**
Not sure. 

**Number of users impacted**
I imagine everyone trying to use `python3.10`. Without `pip` readily available, python is borderline useless. I'd love to hear if there's a workaround we can use until `pip` for 3.10 is included in one of the next releases.

**Comment by matejsp** [comment]
You can use:
```
python3.10 -m ensurepip --upgrade
```

**Comment by stewartsmith** [comment]
In the GA release of AL2023 (2023.0.20230315 - released today) we have `python3.11` available, as well as `python3.11-pip`. We do not currently have plans to have Python 3.10 alongside it. Please create a new issue if 3.10 is needed over 3.11.
