### ISSUE TITLE
[Package Request] - Python 3.11

### ISSUE THREAD

**Issue by cedar10bits** [amazonlinux/amazon-linux-2023#231]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
Python 3.11

**Is this an update to existing package or new package request?**
New package request. And also 3.9 and 3.10 should be available.

**Is this package available in Amazon Linux 2?**
Not sure.

**Number of users impacted**
Not sure. But I imagine a lot of people want to use the latest and faster python.
https://docs.python.org/3/whatsnew/3.11.html#summary-release-highlights

**Comment by matejsp** [comment]
Yes we would like to have latest python 3.11.

**Comment by matejsp** [comment]
3.10 is also gone https://github.com/amazonlinux/amazon-linux-2023/issues/274

**Comment by stewartsmith** [comment]
In the GA release of AL2023 (2023.0.20230315 - released today) we have `python3.11` available, as well as `python3.11-pip`.
