### ISSUE TITLE
[Package Request] Fedora Official Repositories

### ISSUE THREAD

**Issue by jlarmstrongiv** [amazonlinux/amazon-linux-2023#232]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
Many packages from the fedora official repositories.  It would be nice to have, just like how CentOS / Amazon Linux 2 had the option to enable Amazon Linux Extras and the EPEL repository.

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2?**
Sometimes

**Number of users impacted**
All

As a workaround, I use this bash script to enable the fedora official repositories:

```bash
#!/usr/bin/env bash
set -euo pipefail

# references
# - all files https://src.fedoraproject.org/rpms/fedora-repos/tree/f35
# - script https://src.fedoraproject.org/rpms/fedora-repos/blob/rawhide/f/fedora-repos.spec

stable_enabled=1
releasever=36
expire_value='7d'

curl --silent --location "https://src.fedoraproject.org/rpms/fedora-repos/raw/f$releasever/f/fedora-modular.repo" --output "/etc/yum.repos.d/fedora-modular.repo"
curl --silent --location "https://src.fedoraproject.org/rpms/fedora-repos/raw/f$releasever/f/fedora.repo" --output "/etc/yum.repos.d/fedora.repo"
curl --silent --location "https://src.fedoraproject.org/rpms/fedora-repos/raw/f$releasever/f/fedora-updates-modular.repo" --output "/etc/yum.repos.d/fedora-updates-modular.repo"
curl --silent --location "https://src.fedoraproject.org/rpms/fedora-repos/raw/f$releasever/f/fedora-updates.repo" --output "/etc/yum.repos.d/fedora-updates.repo"

for repo in /etc/yum.repos.d/fedora{,-modular,-updates,-updates-modular}.repo; do
    sed -i -e "s/\$releasever/${releasever}/" -e "/^enabled=/ s/AUTO_VALUE/${stable_enabled}/" -e "/^metadata_expire=/ s/AUTO_VALUE/${expire_value}/" $repo || exit 1
done

curl --silent --location "https://src.fedoraproject.org/rpms/fedora-repos/raw/f$releasever/f/RPM-GPG-KEY-fedora-$releasever-primary" --output "/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-primary"

keyfile="/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-primary"
for arch in x86_64 aarch64; do
    # replace last part with $arch (fedora-20-primary -> fedora-20-$arch)
    ln -s $keyfile ${keyfile%-*}-$arch
done
```

**Comment by deleugpn** [comment]
Does this workaround allows you to enable EPEL 9 by any chance?

**Comment by jbergman-apiture** [comment]
I don't believe it does as there is a closed issue saying it's not in scope. 

https://github.com/amazonlinux/amazon-linux-2022/issues/225

**Comment by jbergman-apiture** [comment]
Any updates on this?  I need to know where to go to get the packages that aren't in AL2022.  It feels like a hacky way of getting there.  But it works.

**Comment by daniejstriata** [comment]
> Any updates on this? I need to know where to go to get the packages that aren't in AL2022. It feels like a hacky way of getting there. But it works.

Can you find the package you need from here?
https://src.fedoraproject.org/
using those could work as long as the dependencies are satisfied. I had to scratch around to find all the packages needed from F34 and F36 but in my case it worked in the end. The F34 repos have been archived. 
https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/34/Server/x86_64/os/Packages/

**Comment by jbergman-apiture** [comment]
@daniejstriata yes the package is available.  I just cringe when I have to use a script to enable a repo that cant be enabled just by setting it to enabled from dnf.  Does not seem production worthy.

**Comment by daniejstriata** [comment]
@jbergman-apiture I agree. I think they should just take the whole Fedora server base and rebuild it for AL2022. That they are picking packages from different Fedora releases are making things very interesting for us. 

With RHEL 7 not getting all packages fixed anymore, Amazon will be left to support AMZN2. We're all looking forward to AL2022 but it's not there yet. AMZN2 is amazing. I believe that AL2022 will get there.

**Comment by jbergman-apiture** [comment]
@daniejstriata  totally agree.  Since AL2022 it is upstream of Fedora, they should just enable the entire repo.  The fact that there is no plan for EPEL is also concerning.  This is also interesting.  Fight off the AL2022 FAQs

>  Major releases of Amazon Linux will be based in part on the current version of the upstream Fedora Linux distribution, though Amazon may choose to add or replace specific packages from other non-Fedora upstreams (e.g. Linux kernel is sourced from kernel.org’s Long Term Support choices and is maintained specifically for Amazon’s Linux products). 

I have a feeling this is why the timeline was pushed out 2 years.  We still need time to test with AL2 is EOL around the same time.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/ug/relationship-to-fedora.html:

> Amazon Linux 2023 (AL2023) maintains its own release and support life cycles independent of Fedora. AL2023 provides updated versions of open-source software, a larger variety of packages, and frequent releases. This preserves the familiar RPM-based operating systems.
> The Generally Available (GA) version of AL2023 isn't directly comparable to any specific Fedora release. The AL2023 GA version includes components from Fedora 34, 35, and 36. Some of the components are the same as the components in Fedora and some are modified. Other components more closely resemble the components in CentOS 9 Streams or were developed independently. The Amazon Linux kernel is sourced from the long-term support options that are on kernel.org, chosen independently from Fedora.

We do not currently have plans to do something along the lines of building every Fedora package for Amazon Linux 2023.
