### ISSUE TITLE
[Package Request] - haproxy

### ISSUE THREAD

**Issue by mjmayer** [amazonlinux/amazon-linux-2023#234]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
haproxy : TCP/HTTP proxy and load balancer for high availability environments

**Is this an update to existing package or new package request?**
no

**Is this package available in Amazon Linux 2?**
yes

**Number of users impacted**

**Comment by daniejstriata** [comment]
I compile the following from the src package here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=2097048

[haproxy-2.7.0-1.amzn2022.x86_64.zip](https://github.com/amazonlinux/amazon-linux-2022/files/10386301/haproxy-2.7.0-1.amzn2022.x86_64.zip)
[haproxy-2.7.0-1.amzn2022.src.zip](https://github.com/amazonlinux/amazon-linux-2022/files/10386304/haproxy-2.7.0-1.amzn2022.src.zip)

**Comment by matejsp** [comment]
+1 for this

**Comment by nmeyerhans** [comment]
We'll be including haproxy in an upcoming release.

**Comment by stewartsmith** [comment]
Looks like we missed closing this issue, but we did ship `haproxy` in AL2023.1 back in July (see https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.0-AL2023.1.html )
