### ISSUE TITLE
[Package Request] - mold

### ISSUE THREAD

**Issue by konkueror** [amazonlinux/amazon-linux-2023#240]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
mold: A Modern Linker https://github.com/rui314/mold#mold-a-modern-linker

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2?**
not available. 

**Number of users impacted**
all of users who need faster linker.

**Comment by ozbenh** [comment]
Unfortunately we do not currently plan to support this package
