### ISSUE TITLE
[Package Request] - Runc 1.1.4 (update request from 1.1.3)

### ISSUE THREAD

**Issue by bogbert** [amazonlinux/amazon-linux-2023#244]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
The version 1.1.3 of runc introduced an annoying regression that has been fixed in version 1.1.4 (see https://github.com/opencontainers/runc/releases)
Amazon Linux 2022 currently ships with 1.1.3 (package runc-1.1.3-1.amzn2022.0.1), it should update the package to 1.1.4

**Is this an update to existing package or new package request?**
Update

**Comment by samueloph** [comment]
runc has been updated to `1.1.4-1.amzn2023.0.1` in Amazon Linux 2023, thank you for reporting this @bogbert and @lesinigo
