### ISSUE TITLE
[Feature Request] - Enable swap space by default

### ISSUE THREAD

**Issue by KevinAtSesam** [amazonlinux/amazon-linux-2023#245]
**Is your feature request related to a problem? Please describe.**
Swap memory is an integral part of the Linux Kernel. It helps the memory allocation in the Kernel a lot, when there is some swap space available. Even if it's only a fraction of the available system memory, having a bit of headroom in case of emergencies is always welcome.

Red Hat on the matter
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_storage_devices/getting-started-with-swap_managing-storage-devices

Other enterprise solutions like RHEL and Suse come with swap pre-configured, because it's so important.

More so, there are multiple AWS Products that support swap, but not by default:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-store-swap-volumes.html
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-swap.html

This actually creates some rather annoying scenarios: When you want to use swap, you'll have to configure it at different locations, every time things like the auto-scaling logic change and refresh instances.

**Describe the solution you'd like**
The solution would be fairly straight-forward: Have the base system image come with a limited swap-file pre-configured. I would aim at no more then 1 GB. This will mean that smaller EC2 instances will have more swap by comparison, but it also means that for larger servers with more memory, it really only exits as a fallback.

- [ ] Create 1GB swap-file on instance creation
- [ ] Enable swap space usage 

**Describe alternatives you've considered**
A user could manually configure it, but that would take a lot of effort when using advanced features like auto-scaling. You could add this as a configurable setting to the related components, but knowing how hard it is to get such things well integrated in a UI, I would  not recommend that.

**Summary**
Adding a small base swap-file can help with all kinds of expected memory-shuffles, and unexpected troubles.

**Comment by mhitza** [comment]
Just a note, you could also use cloud-init (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) to setup a swapfile 

```
#cloud-init
swap:
  filename: /swap.img
  size: "auto" # or size in bytes
  maxsize: 10485760   # size in bytes
```
https://cloudinit.readthedocs.io/en/latest/topics/examples.html#adjust-mount-points-mounted

**Comment by stewartsmith** [comment]
Adding the AL2025-candidate label as this would be disruptive to change in a GA release of Amazon Linux.

The cloud-init setup is how we would recommend enabling this if you need it.

Another option for a future AL release is to look into enabling zswap or similar by default on smaller instance types.

**Comment by stewartsmith** [comment]
FYI in the [AL2023.2 release notes](http://localhost:8000/linux/al2023/release-notes/relnotes-2023.2.20230920.html) we have noted that `zram` based swap is now enabled by default for instance types with less than 800MB of memory. This is to help these extremely memory constrained instance types deal with more workloads.

**Comment by KevinAtSesam** [comment]
@stewartsmith Your link seems to be pointing to your local network[ (Public release notes)](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html), but nonetheless it's good to hear that AL2023 will be doing something in situations where OOM crashes are most common.

As for the 800 MB memory cut-off, I would have put it a little higher so that both t4g.nano and t4g.micro are affected.


Either way, it's good to see that you address this issue and I assume that you based your cut-off on internal metrics and common EC2 crashes.Unless somebody want to add something, or somebody really wants to increase the cut-off, I think that this issue is properly completed.

**Comment by stewartsmith** [comment]
I'd copy/pasted that localhost URL into *two* places that I did correct, and this one that I did not. Apologies about that!

We came to this cut off for now based on some of the workloads we were looking at, especially around boot-up and `dnf` invocations while certain agents were enabled and running, as well as the trade-off of what we could have a high confidence of being safe to do for existing users. We stuck with the <1GB instance types as these get a *lot* tighter in these scenarios, while 1GB and above can be made to happily do useful work out of the box, and we didn't want to suddenly affect their performance. It is something we'll consider for AL2025 though

**Comment by Spunkie** [comment]
From a user perspective the 800m cutoff over 1GB is asinine. 

On the low end AWS has always used RAM to aggressively push users to a higher compute tier than needed. This cut off just seems like a way to protect that dark pattern.

**Comment by ozbenh** [comment]
Note that this is simply the default settings, customers can simply create a `/etc/systemd/zram-generator.conf` file with different settings if desired (see https://github.com/systemd/zram-generator). We chose to limit it to the smallest instance types as to alleviate the worst of the problem without taking too much risk of potentially disrputive (unlikely but...) changes to other setups. We are likely to bump that default limit significantly in a new major version of the distribution

**Comment by KevinAtSesam** [comment]
@stewartsmith 
> We stuck with the <1GB instance types as these get a lot tighter in these scenarios, while 1GB and above can be made to happily do useful work out of the box, and we didn't want to suddenly affect their performance. It is something we'll consider for AL2025 though

Totally reasonable. It's not something to change too quickly, and a change like this will have diminishing returns once servers get bigger.
