### ISSUE TITLE
[Package Request] - Snap package manager

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#248]
I need to be able to install snap packages, but I have issues installing snap itself.

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2?**
Not officially.
https://people.canonical.com/~mvo/snapd/amazon-linux2/

**Number of users impacted**
unknown

**Comment by bboozzoo** [comment]
For reference, the packaging files are in https://github.com/bboozzoo/snapd-amazon-linux which are based on the snapd package I maintain for Fedora/EPEL..

**Comment by daniejstriata** [comment]
Any update on the inclusion of snap packages to AL2023?

**Comment by daniejstriata** [comment]
Thanks for adding flatpak to `al2023`. I'd still need snapd to install certbot. Using it with pip does not prove to be stable in the longrun. I miss many renewals as the certbot agent had issues with the host's python libraries. Once I moved to the snap version all my issues went away. Ideally I'd like to install certbot using snap. They are not going to support flatpak. https://github.com/certbot/certbot/issues/8515

**Comment by stewartsmith** [comment]
The issues with snap that are called out in the certbot issue are things we also share concerns about in relation to adding snap to Amazon Linux - and why adding flatpak was a much easier decision for us to make.

I'll note that RPMs for Amazon Linux can be built on COPR, so if somebody wants to maintain snap for Amazon Linux, the Fedora tools for building custom repositories of packages will produce RPMs built for Amazon Linux.

For certbot specifically, we'll try and work on a solution here that matches everyone's needs.

**Comment by ozbenh** [comment]
I'm tentatively closing this issue as we don't plan to ship/support snap. That said, we are still investigating certbot

**Comment by daniejstriata** [comment]
The recommended install method for certbot should be safe for the host's python as it is creating a new virtual environment. This was not historically the case. I'm installing all new certbots using the recommend install mentioned in #444
