### ISSUE TITLE
[Package Request] - libssl.so

### ISSUE THREAD

**Issue by b3rgman** [amazonlinux/amazon-linux-2023#252]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
libcrypto.so, libmysqlclient.so and libssl.so

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2?**
Yes it is available.
It says that these 3 packages are included with openssl but I am not seeing them.

```
error: Failed dependencies:
	libcrypto.so.10()(64bit) is needed by ossec-hids-agent-1:3.6.0-14954.amzn2.art.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) ossec-hids-agent-1:3.6.0-14954.amzn2.art.x86_64
	libmysqlclient.so.18()(64bit) is needed by ossec-hids-agent-1:3.6.0-14954.amzn2.art.x86_64
	libssl.so.10()(64bit) is needed by ossec-hids-agent-1:3.6.0-14954.amzn2.art.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by ossec-hids-agent-1:3.6.0-14954.amzn2.art.x86_64
```

**Number of users impacted**
My organization but it could also effect others.

**Comment by jbergman-apiture** [comment]
Wanted to add I sym linked these to the versions I need and this still did not work.  So something else is going on here.

**Comment by stewartsmith** [comment]
The package you're trying to install is built for Amazon Linux 2, it will need to be rebuilt for Amazon Linux 2022 and the dependencies it provides.
