### ISSUE TITLE
[Package Request] - NodeJs 16

### ISSUE THREAD

**Issue by jbergman-apiture** [amazonlinux/amazon-linux-2023#258]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
NodeJs 16
**Is this an update to existing package or new package request?**
New Package.  You offer NodeJs 18.
**Is this package available in Amazon Linux 2?**
Yes
I need NodeJs 16 before jumping to NodeJs 18. 
**Number of users impacted**
My organization and possibly others

**Comment by jbergman-apiture** [comment]
I did find this.  
https://github.com/nodesource/distributions/issues/1367

**Comment by stewartsmith** [comment]
Since NodeJS 16 has reached its End of Life, it's not something we'll be looking at to add to Amazon Linux 2023.

I'm sorry we couldn't help you with this intermediary step for migrating to NodeJS 18, which is the minimum NodeJS version we ship as part of Amazon Linux 2023.
