### ISSUE TITLE
[Package Request] - Python3.8 and pip

### ISSUE THREAD

**Issue by frmZtH** [amazonlinux/amazon-linux-2023#260]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

Python3.8

**Is this an update to existing package or new package request?**

New package request. Why removed Python3.8 from AL2022, and there are only Python3.9 and Python3.10 available.

**Is this package available in Amazon Linux 2?**

We can use amazon-linux-extras enable python3.8 to install Python3.8 in AL2.

Hope we can use yum to install python3.8 in AL2022, such use "yum install -y python3.8", and also pip can be installed upgraded 

**Number of users impacted**
Not clear, but there are still a large number of people who use python3.8.

**GA release ?**

By the way, I want to ask when can we get the GA al2022 ?

**Comment by ZhangPei25** [comment]
I have same problem, packages used in the projects have dependency on python3.8, only python3.8 works

**Comment by stewartsmith** [comment]
As per https://devguide.python.org/versions/ the EoL of Python 3.8 is October of 2024, which is around 5 months away now. Thus, we are not looking at adding Python 3.8 to AL2023 at this point in time.
