### ISSUE TITLE
[Package Request] - PHP 8.2

### ISSUE THREAD

**Issue by sunaoka** [amazonlinux/amazon-linux-2023#264]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

PHP 8.2

**Is this an update to existing package or new package request?**

New package request.

**Is this package available in Amazon Linux 2?**

No.

**Number of users impacted**

Not known.
However, the current PHP 8.1 offering will be retired from active support on November 25, 2023.

https://www.php.net/supported-versions.php

**Comment by nmeyerhans** [comment]
We'll be including php 8.2 in an upcoming AL2023 release. No ETA at this time, but keep an eye out for it in the repositories and Release Notes.

**Comment by beeradmoore** [comment]
Hey @nmeyerhans. It's a few months on, just checking in that this is still planned and hasn't been shelved for the near future?

We are wanting to move to AL2023 servers but also wish to do it at the same time we move to php8.2. I have been getting notifications for the last 4 updates since this to see if it is time to move but it is still not time yet 😂

**Comment by nmeyerhans** [comment]
Hi @beeradmoore. Yes, php 8.2 is coming soon. We are targeting our upcoming [quarterly release](https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html) for the 8.2 introduction.

**Comment by beeradmoore** [comment]
Awesome, thanks for confirming @nmeyerhans

**Comment by sunaoka** [comment]
We found that PHP 8.2 was added on [2023.1.20230628](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230628.html)!
Thank you very much!

```
$ rpm -q system-release
system-release-2023.1.20230628-0.amzn2023.noarch
```

```
$ dnf info php8.2
Last metadata expiration check: 0:07:46 ago on Thu 29 Jun 2023 12:39:00 AM UTC.
Available Packages
Name         : php8.2
Version      : 8.2.7
Release      : 1.amzn2023.0.1
Architecture : aarch64
Size         : 14 k
Source       : php8.2-8.2.7-1.amzn2023.0.1.src.rpm
Repository   : amazonlinux
Summary      : PHP scripting language for creating dynamic web sites
URL          : http://www.php.net/
License      : PHP and Zend and BSD and MIT and ASL 1.0 and NCSA and Boost
Description  : PHP 8.2 is an HTML-embedded scripting language. PHP 8.2 attempts to make it
             : easy for developers to write dynamically generated web pages. PHP 8.2 also
             : offers built-in database integration for several commercial and
             : non-commercial database management systems, so writing a
             : database-enabled webpage with PHP 8.2 is fairly simple. The most common
             : use of PHP 8.2 coding is probably as a replacement for CGI scripts.
```

**Comment by stewartsmith** [comment]
Ahh yes, I was waiting for the docs to go live before looking through the issues to mention that :)

**Comment by beeradmoore** [comment]
Browser just let me know the docs updated, been monitoring it 😂

Thanks all! Looking forward to playing with AL2023 and php8.2
