### ISSUE TITLE
Amazon linux 2022 AMI for EC2 is not available in the new regions

### ISSUE THREAD

**Issue by chenbb1** [amazonlinux/amazon-linux-2023#269]
AMI al2022-ami-2022 is not available on the new regions including: 
ap-southeast-3
ap-south-2
eu-central-2
eu-south-2
ap-southeast-4

The only available AMI is al2022-ami-ecs

**Comment by sktomer** [comment]
Hello @chenbb1 ,

AL 2022 is in tech preview phase and we are working on getting it to new regions asap. We will be addressing this issue in the next release. 

Regards,
Sumit

**Comment by chenbb1** [comment]
Hi,

Thank you,
When is the next release ?

Thanks,
Chen

**Comment by stewartsmith** [comment]
The latest release just went out, a quick look now shows at least `ap-southeast-4` having AL2023 AMIs, and the other regions should also have them. Enjoy!
