### ISSUE TITLE
[Package Request] - pdsh

### ISSUE THREAD

**Issue by jfacevedo** [amazonlinux/amazon-linux-2023#270]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`pdsh`

Original request was for:
iftop, inotify-tools, daemonize, pdsh, lustre
See https://github.com/amazonlinux/amazon-linux-2023/issues/270#issuecomment-1536700226

**Is this an update to existing package or new package request?**
new packages request

**Is this package available in Amazon Linux 2?**
It is possible to have them in AL2 through EPEL, however EPEL8 in AL2022 shows unresolved dependency errors when trying to install pdsh

$ sudo yum install pdsh
 Problem: conflicting requests
  - nothing provides libreadline.so.7()(64bit) needed by pdsh-2.34-5.el8.aarch64
  - nothing provides libhistory.so.7()(64bit) needed by pdsh-2.34-5.el8.aarch64

**Number of users impacted**
It is not clear. I am testing upgrading our base AMI to AL2022 to migrate soon from AL2.

**Comment by DLM-unipd** [comment]
Please add lustre client package

**Comment by halfdime-code** [comment]
AL2023 provides `readline-8` (which provides both of the missing libraries), not 7. `dnf provides 'libreadline*' 'libhistory*'`

Installing packages from EPEL onto Amazon Linux is unsupported.

**Comment by stewartsmith** [comment]
As of Amazon Linux 2023.0.20230503:

```
bash-5.2# dnf list iftop inotify-tools daemonize
Last metadata expiration check: 0:08:10 ago on Fri May  5 19:34:40 2023.
Available Packages
daemonize.aarch64                 1.7.8-5.amzn2023                   amazonlinux
iftop.aarch64                     1.0-0.30.pre4.amzn2023             amazonlinux
inotify-tools.aarch64             3.22.1.0-4.amzn2023                amazonlinux
```

Since https://github.com/amazonlinux/amazon-linux-2023/issues/309 is open for Lustre, I'm going to keep this issue open to track `pdsh` (and rename the issue accordingly)
