### ISSUE TITLE
[Bug] - Amazon Linux 2022 security advisories prior to 2023 seem to be missing

### ISSUE THREAD

**Issue by westonsteimel** [amazonlinux/amazon-linux-2023#273]
**Describe the bug**

We saw [this announcement](https://alas.aws.amazon.com/announcements/2023-002.html) which indicates that past advisories should still be accessible; however, they seem to be unreachable

**To Reproduce**

https://alas.aws.amazon.com/AL2022/ALAS-2022-062.html results in 

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>P31GQ2H3DXBHZBC7</RequestId>
  <HostId>CSrp77mSqBkZ0ZFQXOaYezWohFoWoJt+i/ErnMZZlQBDDPSv4SYNHbIOOsEdlao0qVFYWniM410=</HostId>
</Error>
```

**Expected behavior**
We expect prior advisory data to still be accessible

**Comment by theadilsonribeiro** [comment]
Hi @westonsteimel,  this issue should be resolved. Thanks.
