### ISSUE TITLE
upgrade - AL2022 to AL2023

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#280]
Hi,

How can I upgrade to AL2023 from AL2022? I ran `dnf update` but I'm not notified of any Distro update.

**Comment by nmeyerhans** [comment]
The upgrade isn't officially supported, and we recommend you launch a new instance based on an AL2023 AMI. However, you can perform an in-place update from AL2022 to AL2023 using the following process:

```plain
curl -LO 'https://al2023-repos-us-west-2-de612dc2.s3.dualstack.us-west-2.amazonaws.com/core/guids/cf9296325a6c46ff40c775a8e2d632c4c3fd9d9164014ce3304715d61b90ca8e/x86_64/../../../../blobstore/aa1fb0c8819d700b85e1be91e54c4f45a1c1592cf661f1d17ee3e973e67733ce/amazon-linux-repo-s3-2023.0.20230222-0.amzn2023.noarch.rpm'

curl -LO 'https://al2023-repos-us-west-2-de612dc2.s3.dualstack.us-west-2.amazonaws.com/core/guids/cf9296325a6c46ff40c775a8e2d632c4c3fd9d9164014ce3304715d61b90ca8e/x86_64/../../../../blobstore/d0f72024771c44d43edd48ac774716e4c9c2535838dc144bfc5638c996926ab9/system-release-2023.0.20230222-0.amzn2023.noarch.rpm'

sudo dnf -y install amazon-linux-repo-s3-2023.0.20230222-0.amzn2023.noarch.rpm system-release-2023.0.20230222-0.amzn2023.noarch.rpm

sudo dnf update
sudo dnf remove --oldinstallonly
```

This will pull in a large number of package updates, as everything has been rebuilt for AL2023.

**Comment by Prabhatsharmaa321** [comment]
Do we have this option available for AL2 to AL2023 in-place upgrade?

**Comment by bfelianowex** [comment]
hello @nmeyerhans 
is there a link for the latest version also? version 2023.2.20230920

https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html

thank you

**Comment by jmcpheters** [comment]
after the 'sudo dnf update' I get:

(568/569): perl-podlators-4.14-458.amzn2023.0.2.noarch.rpm                                                                                                                                                                1.0 MB/s | 112 kB     00:00
(569/569): perl-SelectSaver-1.02-477.amzn2023.0.3.noarch.rpm                                                                                                                                                              126 kB/s |  13 kB     00:00
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                      14 MB/s | 350 MB     00:24
Amazon Linux 2023 repository                                                                                                                                                                                              1.7 MB/s | 1.8 kB     00:00
Importing GPG key 0xD832C631:
 Userid     : "Amazon Linux <amazon-linux@amazon.com>"
 Fingerprint: B21C 50FA 44A9 9720 EAA7 2F7F E951 904A D832 C631
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2023
Is this ok [y/N]: y\
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test

Which is the same place it got stuck before. Could it just be taking long?
