### ISSUE TITLE
[Feature Request] - missing squashfs for AL2023

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#283]
I'm booting the latest kernel 6.1.12-19.43.amzn2023.x86_64. It does not have squashfs anymore. It is needed for various software to operate like certbot on snapd. It was also removed for AL2022 before it was added back.

This was fixed here:
https://github.com/amazonlinux/amazon-linux-2023/issues/223

Please add it back.

**Comment by nmeyerhans** [comment]
Can you provide more details about what's actually missing? The module is enabled in the kernel and I'm able to create an mount a squashfs filesystem using the packaged squashfs-tools:

```plain
[ec2-user@ip-10-0-0-224 ~]$ uname -a
Linux ip-10-0-0-224.us-west-2.compute.internal 6.1.12-19.43.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb 23 23:37:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-10-0-0-224 ~]$ sudo mount -t squashfs test.img /mnt/
[ec2-user@ip-10-0-0-224 ~]$ findmnt /mnt 
TARGET SOURCE     FSTYPE   OPTIONS
/mnt   /dev/loop0 squashfs ro,relatime,seclabel,errors=continue
[ec2-user@ip-10-0-0-224 ~]$ lsmod|grep squash
squashfs               73728  1
lz4_decompress         28672  1 squashfs
```

**Comment by daniejstriata** [comment]
@nmeyerhans Thanks for your feedback. I gave it a try and it seems that squashfs is only loaded once used. Where with older distros like AMZN2 it was always loaded.

`cat /proc/filesystems  | grep  squashfs` has no output until I actually mount an image using squashfs.

I've not been able to install snap on AL2022 but I'll try on AL2023 and revert back here should squashfs be a problem.

**Comment by nmeyerhans** [comment]
> cat /proc/filesystems  | grep  squashfs has no output until I actually mount an image using squashfs.

That won't show any output until you've actually loaded the squashfs kernel module, which happens automatically when you try to mount a squashfs filesystem.

**Comment by daniejstriata** [comment]
Although Squashfs may have appeared to be unavailable at first, it is actually working. I installed Snap from the FC36 packages and they worked fine.
