### ISSUE TITLE
[Bug] - amazon-linux-extras: command not found on 2023.0.20230315.0

### ISSUE THREAD

**Issue by wojaczek** [amazonlinux/amazon-linux-2023#290]
We used to run amazon-linux-extras to install various additional packages on amazonlinux. Starting from the latest push command disappeared. 

**To Reproduce**
FROM public.ecr.aws/amazonlinux/amazonlinux:latest
RUN amazon-linux-extras install python3.8
 => ERROR [ 2/13] RUN amazon-linux-extras install python3.8                                                            1.3s

**Expected behavior**
Proceed with python3.8 installation

**Comment by wojaczek** [comment]
I found that **python-devel** is not there. In my usecase I need that to compile pycurl module, and this one, in turn, is required to run celery on SQS. I'd greatly appreciate adding this to the package base.

**Comment by nmeyerhans** [comment]
> I found that python-devel is not there. In my usecase I need that to compile pycurl module, and this one, in turn, is required to run celery on SQS. I'd greatly appreciate adding this to the package base.

You want `python3-devel`.  The standard in the python community is that unversioned "python" refers to python 2, which we do not ship.  Python 3 packages would typically be named `python3-*`

**Comment by wojaczek** [comment]
Yeah, i looked at Python3, i See python3.9 and python3.11, but for none of
them devel package exists, as per the page:
https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages.html
Regards
Olek

czw., 16 mar 2023, 21:10 użytkownik Noah Meyerhans ***@***.***>
napisał:

**Comment by nmeyerhans** [comment]
They're definitely there:
```
$ dnf list python3.11-devel python3-devel
Last metadata expiration check: 1:46:11 ago on Thu Mar 16 13:08:07 2023.
Installed Packages
python3-devel.x86_64                       3.9.16-1.amzn2023.0.3                    @amazonlinux
Available Packages
python3.11-devel.x86_64                    3.11.2-2.amzn2023.0.6                    amazonlinux 
```

The page you cited lists only source (main) packages, not subpackages.  python3-devel is a subpackage of python3, which is listed there.

**Comment by stewartsmith** [comment]
FYI, a couple of months ago we did add the binary RPMs to all the package comparison pages in the AL2023 documentation. So you can now see more in-depth changes between AL2 and AL2023.
