### ISSUE TITLE
[Feature Request] - AL 2023 on Lambda

### ISSUE THREAD

**Issue by GrahamCampbell** [amazonlinux/amazon-linux-2023#303]
**Is your feature request related to a problem? Please describe.**

Is AL 2023 coming to Lambda? Is there a roadmap for this? How will quarterly releases be treated by Lambda?

**Describe the solution you'd like**

AL 2023 available on Lambda for both x86_64 and arm64.

**Describe alternatives you've considered**

**Additional context**

**Comment by theRocket** [comment]
I have considered building my own image based on AL2023 for my ruby-based lambda runtime. The Dockerfile looks like this:
```
FROM amazonlinux:2023

RUN dnf install -y ruby \
  && dnf clean all
```
This adds Ruby 3.2 to the image which is the supported version going forward (2.7 is deprecated).

However, I would prefer to have this runtime supported in Lambda rather than building a custom image as it is a lot simpler to set up apps using the serverless framework.

**Comment by Talal916** [comment]
Hello @stewartsmith , is there an ETA for this? I see it was moved to Coming Soon and would appreciate if there was a rough estimate of release date?

**Comment by GrahamCampbell** [comment]
As I understand, it is coming in the next few months.

**Comment by ozbenh** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-amazon-linux-2023/

**Comment by stewartsmith** [comment]
With [the announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-amazon-linux-2023/) that @ozbenh pointed to, I'm going to resolve this issue as completed. Further documentation and more runtimes will follow.

See the [Introducing the Amazon Linux 2023 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/) blog post for more information.

One thing I particularly like is how much smaller the AL2023 base image is: 40MB versus the 100MB of AL2! This is thanks to the [AL2023 minimal container image](https://docs.aws.amazon.com/linux/al2023/ug/minimal-container.html).
