### ISSUE TITLE
[Package Request] - IPA Font

### ISSUE THREAD

**Issue by yasokada-lc** [amazonlinux/amazon-linux-2023#305]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
ipa-gothic-fonts.noarch
ipa-mincho-fonts.noarch
ipa-pgothic-fonts.noarch
ipa-pmincho-fonts.noarch
**Is this an update to existing package or new package request?**
new package
**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
available in Amazon Linux 2
amzn2-core
**Any additional information you'd like to include. (use-cases, etc)**
Japanese font used for rendering file reports.
The latest version 004.01 is now available.
https://moji.or.jp/ipafont/

**Comment by ozbenh** [comment]
These fonts will be added in an upcoming release

**Comment by stewartsmith** [comment]
These packages have been added in the just released AL2023.2 release.

```
bash-5.2# dnf search 'ipa*fonts'
Amazon Linux 2023 repository                                                                                                         11 MB/s |  19 MB     00:01
Last metadata expiration check: 0:00:01 ago on Thu Sep 21 00:52:02 2023.
===================================================================== Name Matched: ipa*fonts ======================================================================
ipa-gothic-fonts.noarch : Japanese Gothic-typeface OpenType font by IPA
ipa-mincho-fonts.noarch : Japanese Mincho-typeface OpenType font by IPA
ipa-pgothic-fonts.noarch : Japanese Proportional Gothic-typeface OpenType font by IPA
ipa-pmincho-fonts.noarch : Japanese Proportional Mincho-typeface OpenType font by IPA
```

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
