### ISSUE TITLE
[Package Request] - atop

### ISSUE THREAD

**Issue by rmarable** [amazonlinux/amazon-linux-2023#306]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
atop - https://www.atoptool.nl/downloadatop.php

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
atop for amzn2 is curently available through EPEL, which I understand is not supported by Amazon Linux 2023.

**Any additional information you'd like to include. (use-cases, etc)**
atop is a useful performance monitoring tool that should be included as a standard package.

**Comment by nmeyerhans** [comment]
We'll be adding atop to Amazon Linux 2023 in an upcoming release. I don't have an ETA at this time.

**Comment by stewartsmith** [comment]
You can now install `atop` directly from the Amazon Linux 2023 repositories.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
