### ISSUE TITLE
[Package Request] - Google Authenticator

### ISSUE THREAD

**Issue by derek1287** [amazonlinux/amazon-linux-2023#307]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
google-authenticator

**Is this an update to existing package or new package request?**
New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, via EPEL

**Any additional information you'd like to include. (use-cases, etc)**
This package is necessary for securing EC2 instances with 2-Factor Authentication, and is even recommended via this AWS blog how-to post from 2017 (which is now out of date, considering that A) the package is not available, and B) the edits prescribed by the article to the SSH/PAM configuration do NOT work on AL2023): https://aws.amazon.com/blogs/startups/securing-ssh-to-amazon-ec2-linux-hosts/

**Comment by worpet** [comment]
As mentioned above, https://aws.amazon.com/blogs/startups/securing-ssh-to-amazon-ec2-linux-hosts/ recommends to install google-authenticator to get MFA, but without EPEL this is no longer possible. Is there an alternate MFA package included in Amazon Linux 2023 that supports the same functionality? Otherwise, please add google-authenticator.

**Comment by GiladE** [comment]
+1

**Comment by trondude** [comment]
+1 here. We use this as extra security for bastion ssh servers and cannot migration to AWS 2023 Linux without it.

**Comment by ec-max** [comment]
+1

**Comment by juergens73** [comment]
This is important also to us. How can we install the google-authenticator on AL2023. Please provide a solution

**Comment by ozbenh** [comment]
We are evaluating inclusion of this package in our next quarterly release

**Comment by derek1287** [comment]
As a temporary workaround, you can use this command on AL2023:

**x86_64 architectures**:
`dnf install -y https://dl.fedoraproject.org/pub/epel/7Server/x86_64/Packages/g/google-authenticator-1.04-1.el7.x86_64.rpm`

**ARM architectures**:
`dnf install -y https://dl.fedoraproject.org/pub/epel/7Server/aarch64/Packages/g/google-authenticator-1.04-1.el7.aarch64.rpm`

**Comment by ozbenh** [comment]
This is an *ancient* version, we recomment at least 1.09...the one from Fedora might install properly

**Comment by ozbenh** [comment]
Right, I was just offering a stop-gap. Google Authenticator is rather self contained with very little dependencies so "foreign" builds are likely to work fine. That said, stay tuned for our next quarterly release

**Comment by stewartsmith** [comment]
You can now install `google-authenticator` directly from the Amazon Linux 2023 repositories.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
