### ISSUE TITLE
[Package Request] - lustre-client for Amazon Linux 2023

### ISSUE THREAD

**Issue by rmarable** [amazonlinux/amazon-linux-2023#309]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
lustre-client

**Is this an update to existing package or new package request?**
This package existed in Amazon Linux 2.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes - https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html

**Any additional information you'd like to include. (use-cases, etc)**
I am having difficulty parsing why this functionality wouldn't be included in Amazon Linux 2023.

**Comment by rmarable** [comment]
This is critical functionality for HPC workflows.

**Comment by stewartsmith** [comment]
```
$ git log -n1 --pretty=oneline be65f9ed267fd7d8b3146b7c4be9ecdd3e0aa3ed
be65f9ed267fd7d8b3146b7c4be9ecdd3e0aa3ed staging: lustre: delete the filesystem from the tree.
$ git describe --contains be65f9ed267fd7d8b3146b7c4be9ecdd3e0aa3ed
v4.18-rc1~83^2~5
```

You can nicely view the commit on GitHub too: https://github.com/torvalds/linux/commit/be65f9ed267fd7d8b3146b7c4be9ecdd3e0aa3ed

It appears that the Lustre developers have failed to get their code into a state where this can be in the upstream kernel, and even their out-of-tree code does not seem to support modern kernels.

As such, this really puts the code in a state where it does not meet our bar for inclusion in Amazon Linux.

I understand that there's a variety of use cases for this, and I'm reaching out to the FSx Lustre team about their plans around addressing this.

As it is, I'm going to currently mark the issue as `wontfix` as that would be our default position for other bits of code that have gone through this process in the kernel. I'll keep the issue open though until we can either hear further from the FSx Lustre team on any associated plans, or complete some Documentation.

**Comment by bsimon36** [comment]
Is there an update from the FSx Lustre team?

**Comment by jacobwolfaws** [comment]
Hi @rmarable @bsimon36 we plan to release support for AL 2023 Lustre client by the end of Q1 2024.

**Comment by danVSS** [comment]
@jacobwolfaws Is there any revised timelines on this issue? Our is it already resolved? The docs seem to imply that the package is added since instructions for AL2023 with a minimum kernel of 6.1.79-99.167.amzn2023 being required are presented: https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html

**Comment by jacobwolfaws** [comment]
Hi @danVSS, you, this issue is resolved! 
@stewartsmith @rmarable can one of you please mark this issue as resolved and close it? I don't believe I'm able to do so

**Comment by rmarable-flaretx** [comment]
Thanks @jacobwolfaws - please give my best to the AL2023 and FSX teams.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html there is `lustre-client` available in AL2023.4
