### ISSUE TITLE
[Package Request] - iscsi-initiator-utils for Amazon Linux 2023

### ISSUE THREAD

**Issue by raywang** [amazonlinux/amazon-linux-2023#312]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
iscsi-initiator-utils

**Is this an update to existing package or new package request?**
This package existed in Amazon Linux 2, and removed in Amazon Linux 2023
https://docs.aws.amazon.com/linux/al2023/release-notes/removed-packages.html

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes - https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html

**Any additional information you'd like to include. (use-cases, etc)**
Need the packages to use iscsi volumes

**Comment by kalgecin** [comment]
any reason why this package was removed?

**Comment by nmeyerhans** [comment]
We plan on re-enabling iscsi-initiator-utils in upcoming AL2023 update. No ETA at this time, by look for it in the repositories and Release Notes.

**Comment by stewartsmith** [comment]
This was added in AL2023.1, see [the release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230628.html) for details, or the package comparison up at: https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.0-AL2023.1.html
