### ISSUE TITLE
[Package Request] - mtr

### ISSUE THREAD

**Issue by Kogoon** [amazonlinux/amazon-linux-2023#313]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
mtr - Network diagnostic tool combining 'traceroute' and 'ping'

**Is this an update to existing package or new package request?**
new package 

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
mtr is available in Amazon Linux 2

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by playphil** [comment]
mtr is an essential tool for network troubleshooting 
https://en.wikipedia.org/wiki/MTR_(software)
https://packages.fedoraproject.org/pkgs/mtr/mtr/

**Comment by nmeyerhans** [comment]
We'll be providing mtr in a future update of AL2023. We don't have an ETA at this time.

**Comment by stewartsmith** [comment]
The `mtr` package is now available as of Amazon Linux 2023.0.20230503, and is now listed in https://docs.aws.amazon.com/linux/al2023/release-notes/version-compare.html
