### ISSUE TITLE
[Bug] - al2023 Systemd complains about an Alias directive that previously worked

### ISSUE THREAD

**Issue by irvingpop** [amazonlinux/amazon-linux-2023#314]
**Describe the bug**
Hi, I'm testing a package on AL2023 and getting a confusing Systemd error.

Specifically [this line](https://github.com/honeycombio/refinery/blob/main/refinery.service#L14):
```
[Install]
Alias=refinery refinery.service
```

It previously worked on AL2022, and AL1 & 2.  But with AL2023 (2023-03-22 release), I'm getting:
```
# systemctl enable refinery.service
Failed to enable unit: Cannot alias refinery.service as refinery.
```

**To Reproduce**
1. Install [this package](https://github.com/honeycombio/refinery/releases/download/v1.20.0/refinery-1.20.0-1.x86_64.rpm)  or simply craft a systemd unit file that contains the following:
  ```
  [Install]
  Alias=refinery refinery.service
  ```
2.  Run `systemctl enable refinery`  

**Expected behavior**
In reading the Systemd docs, I'm guessing that this Alias directive may not be necessary - but it had worked in past releases, and so at a minimum I'm looking for some justification to change it (and what the [Install] section should look like).

**Additional context**
I work for the company which makes the aforementioned software, although I'm not a direct maintainer of it.

**Comment by nmeyerhans** [comment]
I'm a bit surprised this ever worked, actually.  At best it was redundant, but it's not clear that it was ever even valid. Going back as far as AL2's systemd 219, the documentation indicates that aliases must specify the same suffix as the original unit file. An alias without a suffix at all has never been documented as being valid or meaningful, and systemd commands like `systemctl` would automatically apply a `.service` suffix to unqualified arguments (so, e.g. even in AL2, `systemctl status sshd` was equivalent to `systemctl status sshd.service` with no explicit aliases involved.)

A usual `[Install]` section does not normally need to specify an `Alias=` directive at all. Most likely the only line you'll need there is a `WantedBy=` directive indicating the services or targets that trigger the activation of this service. `WantedBy=multi-user.target` is a good place to start.

**Comment by irvingpop** [comment]
hi @nmeyerhans thanks for confirming that - I'll open a PR there.  Hopefully this issue helps future travelers 🙂
