### ISSUE TITLE
[Package Request] - lftp and mutt

### ISSUE THREAD

**Issue by JTMosaic** [amazonlinux/amazon-linux-2023#318]
Please consider including the following packages for Amazon Linux 2023

- mutt.x86_64 : A text mode mail user agent
- lftp.x86_64 : A sophisticated file transfer program

Both packages are available on Linux 2, base repo:

5:mutt-1.5.21-29.amzn2.0.1.x86_64 : A text mode mail user agent
lftp-4.4.8-12.amzn2.1.x86_64 : A sophisticated file transfer program

**Comment by stewartsmith** [comment]
`mutt` has been added in https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230906.html and we'll talk more about it in the AL2023.2 release notes.

**Comment by stewartsmith** [comment]
We also added `lftp` in https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.0.20230614.html (but forgot to update here, sorry!).

So with that, we have added both of these requests, so I'll resolve this issue.
