### ISSUE TITLE
zip package missing 

### ISSUE THREAD

**Issue by melincredo** [amazonlinux/amazon-linux-2023#320]
Hi Team,

Unable to install php-zip on server with Amazon Linux 2023 as well as unable to find.

Also wasn't able to install certbot hence had to use pip option to get it done.
https://certbot.eff.org/instructions?ws=apache&os=pip

Followed below and then ran pecl install -f libsodium to get libsodium installed 
https://www.procustodibus.com/blog/2022/10/install-libsodium-on-amazon-linux-2022/

Please suggest at earliest for zip.

Regards,
Mehul

**Comment by daniejstriata** [comment]
It seems multiple packages are mentioned here. I saw from another post that `libsodium` will probably not be added: https://github.com/amazonlinux/amazon-linux-2023/issues/204

Is this request opened for `zip` or `php-zip`?

**Comment by Dhurba123a** [comment]
Anyone got the solution? I'm facing this issue too.

**Comment by nawazsharif** [comment]
I am fetching the same issue any solution?

**Comment by btribulski** [comment]
> 
I've tried 

sudo yum install php8.1-zip
sudo yum install php-zip

and getting no match.

**Comment by bwaters** [comment]
so workaround you can build it with

sudo yum install php8.1-devel php-pear libzip libzip-devel
sudo pecl install zip
echo "extension=zip.so"  | sudo tee /etc/php.d/20-zip.ini

**Comment by btribulski** [comment]
> so workaround you can build it with
> 
> sudo yum install php8.1-devel php-pear libzip libzip-devel sudo pecl install zip echo "extension=zip.so" | sudo tee /etc/php.d/20-zip.ini

Thank you so much! That worked.

**Comment by prettypet2137** [comment]
It works well, thank you very much!

**Comment by emmanuelkorir** [comment]
Thank you

**Comment by ozzeruk** [comment]
To update this, as of mid-August 2023, PHP 8.2 is shipping with Amazon Linux 2023.

These instructions worked correctly for me.

```
sudo dnf install php8.2-devel php-pear libzip libzip-devel
sudo pecl install zip
echo "extension=zip.so" | sudo tee /etc/php.d/20-zip.ini
```

**Comment by stewartsmith** [comment]
Please see https://github.com/amazonlinux/amazon-linux-2023/issues/195 for tracking the inclusion of `php-zip`

We've had a few requests for this, and we prefer to consolidate into a single issue for each issue so that it's easier to track and that everybody can be kept updated.
