### ISSUE TITLE
[Package Request] - AWS SDK for Python (boto3)

### ISSUE THREAD

**Issue by lowchoonkeat** [amazonlinux/amazon-linux-2023#322]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
boto3

**Is this an update to existing package or new package request?**
new package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes. can install via pip3 install boto3

**Comment by andrew-pickin-epi** [comment]
Perhaps more relevant: 
**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
```yum install python3-boto3

=================================================================================================================================
 Package                        Arch                    Version                                Repository                   Size
=================================================================================================================================
Installing:
 python3-boto3                  noarch                  1.21.33-1.amzn2.0.1                    amzn2-core                  173 k

Transaction Summary
=================================================================================================================================
Install  1 Package
```

**Comment by kivengh** [comment]
Hi,
There is any plan to include boto3 in Amazon Linux 2023 ? The AWS integration is the main argument to use Amazon Linux.

**Comment by nmeyerhans** [comment]
boto3 will be included in an upcoming AL2023 release.

**Comment by nmeyerhans** [comment]
Done as of the AL2023.3 release just published.
