### ISSUE TITLE
[Package Request] - Packages for virtual GUI (xfce4, xfce4-goodies, xrdp, tigervnc-server)

### ISSUE THREAD

**Issue by silverlining-cloud** [amazonlinux/amazon-linux-2023#324]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
xfce4, xfce4-goodies, xrdp, tigervnc-server

**Is this an update to existing package or new package request?**
New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, all of them

**Any additional information you'd like to include. (use-cases, etc)**
Setting up a virtual desktop

**Comment by stewartsmith** [comment]
I'm going to close this issue and refer over to https://github.com/amazonlinux/amazon-linux-2023/issues/47 for tracking the larger graphical desktop environment ask.
