### ISSUE TITLE
[Package Request] - python-pkgconfig

### ISSUE THREAD

**Issue by sebsto** [amazonlinux/amazon-linux-2023#325]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
python-pkgconfig

**Is this an update to existing package or new package request?**
new package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Available in EPEL 

**Any additional information you'd like to include. (use-cases, etc)**
These are teh python bindings for pkgconfig. Required by multiple development toolchains

**Comment by sebsto** [comment]
https://en.wikipedia.org/wiki/Gold_(linker)

**Comment by ozbenh** [comment]
This has shipped as part of AL2023.2

**Comment by ozbenh** [comment]
Note: The package name is `python3-pkgconfig`
