### ISSUE TITLE
[Package Request] - sshpass

### ISSUE THREAD

**Issue by matejsp** [amazonlinux/amazon-linux-2023#338]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
sshpass -> The sshpass utility helps administrators more easily manage SSH connections in scripts.

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes, sshpass-1.06-1.amzn2.0.1.x86_64 

**Any additional information you'd like to include. (use-cases, etc)**
we use it together with ansible (ansible is installed via pip).

**Comment by matejsp** [comment]
Working temp alternative:
```
dnf install https://rpmfind.net/linux/fedora/linux/releases/36/Everything/aarch64/os/Packages/s/sshpass-1.09-3.fc36.aarch64.rpm
```
or 
```
dnf install https://rpmfind.net/linux/fedora/linux/releases/36/Everything/aarch64/os/Packages/s/sshpass-1.09-3.fc36.x86_64.rpm
```

**Comment by stewartsmith** [comment]
This has now been included in the Amazon Linux 2023 repositories.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
