### ISSUE TITLE
[Package Request] - dotnet 7.0 support

### ISSUE THREAD

**Issue by sonicparke** [amazonlinux/amazon-linux-2023#346]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
dotnet 7.0 is missing. 

The specific package we need is `dotnet-sdk-7.0`

https://learn.microsoft.com/en-us/dotnet/core/install/linux-fedora

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Is this an update to existing package or new package request?**
dotnet 6 is and should remain available so I guess this is a new request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

**Any additional information you'd like to include. (use-cases, etc)**
dotnet 7.0 includes AOT compiling which we would like to use in lambda

Thanks!

**Comment by james-astra** [comment]
Is this still not supported?

**Comment by stewartsmith** [comment]
I'm going to close this in favor of https://github.com/amazonlinux/amazon-linux-2023/issues/601
