### ISSUE TITLE
[Package Request] - iperf2

### ISSUE THREAD

**Issue by akiyano** [amazonlinux/amazon-linux-2023#347]
package name iperf2

new package

available in AL2 via EPEL7

iperf2 is different than iperf3 in some behaviors, which makes it a better tool for performance testing in some cases.

**Comment by FireballDWF** [comment]
iperf2 also has support for testing multicast, while iperf3 does not

**Comment by FireballDWF** [comment]
Workaround: dnf install -y https://rpmfind.net/linux/fedora/linux/releases/38/Everything/x86_64/os/Packages/i/iperf-2.1.9-1.fc38.x86_64.rpm successfully installs

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html there is `iperf` version 2.1.9 in AL2023.4 - does this satisfy this request?

**Comment by FireballDWF** [comment]
yes
