### ISSUE TITLE
[Package Request] - flatpak

### ISSUE THREAD

**Issue by skolo-cfd** [amazonlinux/amazon-linux-2023#349]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Flatpak is a useful installer for packages, now that EPEL sources have been discontinued in AL2023.
flatpak-1.12.4-1.amzn2022.0.1.src
flatpak-builder-1.2.2-1.amzn2022.0.1.src

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
It was available in AL2022, as 
flatpak-1.12.4-1.amzn2022.0.1.src
flatpak-builder-1.2.2-1.amzn2022.0.1.src

**Any additional information you'd like to include. (use-cases, etc)**
flatpak can be used to install all kinds of other packages via docker

**Comment by stewartsmith** [comment]
`flatpak` is in the repos as pert the https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230906.html release, and we'll cover it more in the AL2023.2 release notes.
