### ISSUE TITLE
[Package Request] - libzip-devel

### ISSUE THREAD

**Issue by samarart27** [amazonlinux/amazon-linux-2023#352]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

**_libzip-devel_** is missing, and current libzip in AL2023 is libzip 1.7.3-4.amzn2023.0.3

**Is this an update to existing package or new package request?**

_new package request_

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

_Yes
 libzip-devel.x86_64                    1.3.2-1.amzn2.0.1             @amzn2-core
And it's not listed in the differences or in removed packages_

**Any additional information you'd like to include. (use-cases, etc)**

It's needed in order to build the ZIP extension for PHP with **pecl install zip**

**Comment by samarart27** [comment]
Sorry, not listed in the package listing but found it in DNF...  Package listing should be updated.

Best regards

**Comment by ozbenh** [comment]
The package listing doesn't contain subpackages. If it did, for example, you would get the gazillion glibc langpacks or texlive subpackagtes, it would make the list rather hard to digest.

Typically -devel packages are subpackages of the main binary and as such not listed in the package list online.
