### ISSUE TITLE
[Package Request] - Docker 23

### ISSUE THREAD

**Issue by hallm4** [amazonlinux/amazon-linux-2023#354]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
docker 23.0.6 ( https://docs.docker.com/engine/release-notes/23.0/ )

**Is this an update to existing package or new package request?**
update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes, in fact al2 has 20.10.23, and al2023 has 20.10.17 which went *backwards*

**Any additional information you'd like to include. (use-cases, etc)**
related to https://github.com/amazonlinux/amazon-linux-2023/issues/186 -- but I think this should be highlighted as an update to the entire docker package.

**Comment by ozbenh** [comment]
FYI AL2023 now has 20.10.23. I can't yet comment on 23.x

**Comment by stewartsmith** [comment]
We are looking at Docker 24 and if/how to bring it in while ensuring compatibility for customers.

**Comment by stewartsmith** [comment]
Docker 24 is now available in Amazon Linux 2023.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
