### ISSUE TITLE
[Package Request] - Preinstall findutils

### ISSUE THREAD

**Issue by Joe-Zer0** [amazonlinux/amazon-linux-2023#355]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
It would be helpful if "findutils" was preinstalled in Amazon Linux 2023.  This package has commands "find", "locate", "xargs".  I am used to having these commands readily available in Linux systems.

**Is this an update to existing package or new package request?**
This is an existing package that I think would be good to have preinstalled.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, it is currently preinstalled in Amazon Linux 2.

**Any additional information you'd like to include. (use-cases, etc)**
I am currently using the amazonlinux:2023 docker image.  Thanks for your consideration!

**Comment by nmeyerhans** [comment]
>  This is an existing package that I think would be good to have preinstalled.

Agreed, this should be installed by default on the Amazon Linux 2023 AMI.  However,

>  I am currently using the amazonlinux:2023 docker image. Thanks for your consideration!

The container images are intended to be minimal, with the intent being to reduce the required size of your derivative containers are much as possible.  The same goes for the Amazon Linux "minimal" AMI variant.

So, the plan at the moment is to preinstall findutils on the standard AMI, but not on the container image or the minimal AMI.

**Comment by stewartsmith** [comment]
FYI https://docs.aws.amazon.com/linux/al2023/ug/al2023-container-ami.html has been added to the documentation, which covers every RPM that is installed on the Minimal AMI and if it is in the container images or not.
