### ISSUE TITLE
[Bug] - motd resets when new AL2023 update is available

### ISSUE THREAD

**Issue by adrianmace** [amazonlinux/amazon-linux-2023#358]
**Describe the bug**
We remove the `update-motd` utility and replace the `/etc/motd` file with our own static text. This works fine, until a new release of AL2023 becomes available. After that time, when connecting to the instance, we see that a file which contains only the AL bird logo has been placed in `/usr/lib/motd.d` and appended to the end of our existing motd.

**To Reproduce**
1. Execute the following:
```shell
#!/usr/bin/env bash
set -euo pipefail

# Remove Amazon's dynamic motd updater utility.
dnf remove update-motd -y || true
rm /etc/motd || true
rm -rf /etc/motd.d || true
rm /usr/lib/motd || true
rm -rf /usr/lib/motd.d || true

# Update the motd with our own.
cat > /etc/motd << 'END'
Hello, World!
END
```
2. Connect via SSH and observe that only our `Hello, World!` motd is displayed.
3. Wait until there is a new release of Amazon Linux 2023
4. Connect via SSH and obverse that the motd includes both `Hello, World!` _and the Amazon Linux 2023 standard motd_.
5. Observe that there is a file located at `/usr/lib/motd.d/30-banner`.

**Expected behavior**
The banner never returns if deleted.

**Screenshots**

```
Warning: Permanently added 'i-03ded9f344b7xxxxx' (ED25519) to the list of known hosts.
Hello, World!
   ,     #_
   ~\_  ####_        Amazon Linux 2023
  ~~  \_#####\
  ~~     \###|
  ~~       \#/ ___   https://aws.amazon.com/linux/amazon-linux-2023
   ~~       V~' '->
    ~~~         /
      ~~._.   _/
         _/ _/
       _/m/'
Last login: Fri May 26 00:02:16 2023 from 127.0.0.1
```

**Additional context**
It is very likely this is PEBKAC and that I am not disabling / uninstalling the correct update-motd utility, but I could not find any other service that looked related.

**Comment by adrianmace** [comment]
🤦🏻‍♂️User Error

## Explanation

The account in which this AMI was being deployed into had SSM Patch Manager configured, with an association set on all instances. This was executing the Patch Baseline for AL2023.

The baseline executed `dnf update system-release --releasever 2023.0.20230517 -y` to update the release to the latest available (likely to continue checking for and patching what it could).

The upgrade of the `system-release` package seems to include replacing the contents of `/usr/lib/motd.d/30-banner` with the stock AL2023 banner as shown above.

## Next Steps

I will leave this issue open for a maintainer to review. I would like see the behaviour changed so that upgrading `system-release` does not modify the `/usr/lib/motd.d/30-banner` contents if it does not exist or has non-standard contents.

**Comment by stewartsmith** [comment]
Oh, so there is a way to override that behavior, and it's not by editing or removing anything in `/usr` - as you'll get the behavior you observe if you do.

Check out https://man7.org/linux/man-pages/man8/pam_motd.8.html and you should be able to `touch /etc/motd/30-banner` and then you won't get the AL logo as this will override the file in `/usr`

**Comment by adrianmace** [comment]
Thank you @stewartsmith for that explanation. It makes complete sense, and I never thought to dig into the `pam_motd` docs 🤦🏻‍♂️

**Comment by stewartsmith** [comment]
It is a change from how it worked on AL2, and thus probably worth something explicit in the docs on it - which I'll ensure to chase up after the long weekend.

Part of the reason I chose the new route was to make it easy for people to do things like what you're doing here.

**Comment by vjarnot** [comment]
> Oh, so there is a way to override that behavior, and it's not by editing or removing anything in `/usr` - as you'll get the behavior you observe if you do.
> 
> Check out https://man7.org/linux/man-pages/man8/pam_motd.8.html and you should be able to `touch /etc/motd/30-banner` and then you won't get the AL logo as this will override the file in `/usr`

For the other searchers out there, I assume you mean `/etc/motd.d/30-banner`?
