### ISSUE TITLE
[Package Request] - Cloud utils

### ISSUE THREAD

**Issue by rambangaru** [amazonlinux/amazon-linux-2023#360]
cloud-utils package is supposed to be included in Amazon Linux 2023 as per the documentation but how ever `yum install cloud-utils` did not find the package. I have tried yum update/upgrade before yum install/search

**Is this an update to existing package or new package request?** existing package as per documentation

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.** it is available in AL2 via EPEL - `amazon-linux-extras install -y epel`

**Any additional information you'd like to include. (use-cases, etc)** https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-al2023-20230501.html where it says cloud-utils included in AL2023

**Comment by ozbenh** [comment]
It exists in a slimmed down variant with basically only `cloud-utils-growpart`. The reason for that is the rest of the package depends on `qemu-img` which we currently don't ship (as we don't ship qemu).

**Comment by rambangaru** [comment]
Initially I thought the same but I noticed `cloud-utils-growpart` in removed package section that is where I got confused more https://docs.aws.amazon.com/linux/al2023/release-notes/removed-packages.html

Thank you for the explanation, if we could update the package list, means

1) remove the cloud-utils-growpart from removed package section
2) remove clopud-utils from available package and add cloud-utils-growpart instead

this makes it clear. 

Once again thank you for the explanation

**Comment by rambangaru** [comment]
Should I leave the issue open for doc update or can I close it?

**Comment by stewartsmith** [comment]
Leave it open, we can close it when we Update the package list to include binary RPMs rather than just source RPMs

**Comment by stewartsmith** [comment]
FYI the docs update shouldn't be too long now, I've managed to get all the code that feeds into it working and updated, and have verified that `cloud-utils-growpart` shows up.

**Comment by stewartsmith** [comment]
This should all be updated now. Please let us know if there's any further issues with the docs.
