### ISSUE TITLE
[Package Request] - php-imap

### ISSUE THREAD

**Issue by regattaman** [amazonlinux/amazon-linux-2023#363]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
php-imap  imap support for PHP

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by jafferabbas** [comment]
Is there any release schedule for this?

**Comment by ozbenh** [comment]
After some investigations, it appears that `php-imap` relies on an underlying library `libc-client` (which originates from `pine`) which has been completely unmaintained for more than a decade. The Fedora package has been marked dead 14 years ago.

Considering the security implications of this, we chose not to package `php-imap` at this point. It is also not in Fedora and I don't believe it's available on any RHEL variant either.
