### ISSUE TITLE
[Package Request] - git-lfs

### ISSUE THREAD

**Issue by kmoad** [amazonlinux/amazon-linux-2023#365]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
git-lfs

**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
I don't know. [Stackoverflow suggests](https://stackoverflow.com/questions/71448559/git-large-file-storage-how-to-install-git-lfs-on-aws-ec2-linux-2-no-package/71466001#71466001) it's available using `amazon-linux-extras`

**Any additional information you'd like to include. (use-cases, etc)**
This is widely used in git repos. I specifically want it to get weights from huggingface.

The [installation instructions](https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md) from the git-lfs repo do not work.

**Comment by kmoad** [comment]
It can be installed manually by downloading https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-linux-amd64-v3.3.0.tar.gz

**Comment by jeffb4** [comment]
The CentOS 9 Stream package also works for installing `git-lfs` https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/git-lfs-3.2.0-1.el9.x86_64.rpm

**Comment by stewartsmith** [comment]
You can now install `git-lfs` directly from the Amazon Linux 2023 repositories.

The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
