### ISSUE TITLE
[Package Request] - smartmontools

### ISSUE THREAD

**Issue by raywang** [amazonlinux/amazon-linux-2023#366]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
smartmontools: Tools for monitoring SMART capable hard disks

**Is this an update to existing package or new package request?**
no

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, in AL2

**Comment by ozbenh** [comment]
Out of curiosity, which supported EC2 systems have a use for this ?

**Comment by daniejstriata** [comment]
I'm also wondering how this is used in EC2.

**Comment by raywang** [comment]
Hi,

I just confirmed with the customer.

They're hoping to use Amazon Linux 2023 both on cloud and on-prem (KVM and VMware, I understand AL2023 is not support on-prem yet), and also some of their on-prem softwaresneed this tool to get the information from hard disks. So the lack of this package may results in the lack of the tool to monitor the hard disk on-prem (if we support on-prem in the future)

Hope that helps
