### ISSUE TITLE
[Package Request] - stress-ng

### ISSUE THREAD

**Issue by Preskton** [amazonlinux/amazon-linux-2023#368]
**What package is missing from Amazon Linux 2023? Please describe and include package name.** `stress-ng`

**Is this an update to existing package or new package request?** Existing package.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.** Yes, and per https://docs.aws.amazon.com/linux/al2023/release-notes/new-packages.html#:~:text=stress-,stress%2Dng,-SuperLU it should be available in AL23.

After doing an update, attempting a `dnf install` doesn't work.
```
$ sudo dnf install stress-ng
Last metadata expiration check: 1:18:55 ago on Wed Jun  7 17:19:24 2023.
All matches were filtered out by exclude filtering for argument: stress-ng
Error: Unable to find a match: stress-ng
```

**Comment by daniejstriata** [comment]
Release 2023.0.20230517 already has the package requested:
 stress-ng                  x86_64               0.15.05-1.amzn2023                     amazonlinux               2.3 M

**Comment by Preskton** [comment]
ack - after upgrading that looks good to me. Thanks for the quick repsonse! :)
