### ISSUE TITLE
[Package Request] - helm

### ISSUE THREAD

**Issue by M8torr** [amazonlinux/amazon-linux-2023#370]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
helm

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
It is available in Fedora repositories https://packages.fedoraproject.org/pkgs/golang-helm-3/helm/
Project site https://helm.sh/docs/intro/install/

**Any additional information you'd like to include. (use-cases, etc)**
Helm is a package manager for Kubernetes

**Comment by ajf-firstup** [comment]
Appears to be a dupe of https://github.com/amazonlinux/amazon-linux-2023/issues/94 (which already has +4 votes)?

**Comment by stewartsmith** [comment]
Yep, does look like it is a duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/94 - resolving.
