### ISSUE TITLE
[Missing Documentation] - Release Notes Are Missing For `2023.0.20230614`

### ISSUE THREAD

**Issue by mikemhenry** [amazonlinux/amazon-linux-2023#373]
**What topic is missing from the current Amazon Linux 2023 documentation? Please be specific.**
The release notes for `2023.0.20230614` are missing. This page: https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html only has the release notes up to `2023.0.20230607`

**Comment by craigbw** [comment]
The release notes have been updated both on the [AL2023 Release Notes page](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html) and here in GitHub

**Comment by mikemhenry** [comment]
Thanks!
