### ISSUE TITLE
[Package Request] - pwgen

### ISSUE THREAD

**Issue by jamesp9** [amazonlinux/amazon-linux-2023#374]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
`pwgen`

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
```
# yum info pwgen
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
238 packages excluded due to repository priority protections
Available Packages
Name        : pwgen
Arch        : x86_64
Version     : 2.08
Release     : 1.el7
Size        : 26 k
Repo        : epel/x86_64
Summary     : Automatic password generation
URL         : http://sf.net/projects/pwgen
License     : GPL+
Description : pwgen generates random, meaningless but pronounceable passwords. These
            : passwords contain either only lowercase letters, or upper and lower case, or
            : upper case, lower case and numeric digits. Upper case letters and numeric
            : digits are placed in a way that eases memorizing the password.
```

**Any additional information you'd like to include. (use-cases, etc)**
Have used previously in automation.
Also handy for generating passwords.

**Comment by nmeyerhans** [comment]
Hi @jamesp9. We'll work on including pwgen in an upcoming release. I don't have an ETA at this time, but we'll try to provide more info as it gets closer to shipping.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.1-AL2023.2.html this was added in AL2023.2, resolving.
