### ISSUE TITLE
[Package Request] - hiredis

### ISSUE THREAD

**Issue by neilcook** [amazonlinux/amazon-linux-2023#376]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

hiredis

This is the C client library supported and provided by the redis developers.

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

It is available in Amazon Linux 2, via EPEL.

**Any additional information you'd like to include. (use-cases, etc)**

My use-case is that I am an Open-Source developer and I have customers who want to use my software on Amazon Linux 2023 (they are using Amazon Linux 2 currently), but to build packages for AL 2023 I need libhiredis.

**Comment by rokhmanov** [comment]
Looking forward to have this package included please.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - `hiredis` is now in AL2023.4

**Comment by stewartsmith** [comment]
I'll also note that https://aws.amazon.com/elasticache/redis/ is an AWS service that `hiredis` can be used to connect to.
