### ISSUE TITLE
[Package Request] - getdns

### ISSUE THREAD

**Issue by neilcook** [amazonlinux/amazon-linux-2023#378]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

getdns

getdns is a modern asynchronous C DNS client library

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Available in Amazon Linux 2 via EPEL

**Any additional information you'd like to include. (use-cases, etc)**

I'm an Open Source software developer, and I'd like to build packages for Amazon Linux 2023 for users who are currently using Amazon Linux 2, but I need getdns to do so.

**Comment by stewartsmith** [comment]
Out of interest, what packages end up using `getdns` that are being sought by users?

**Comment by neilcook** [comment]
I'm the developer/maintainer of https://github.com/PowerDNS/weakforced/

This package has a very large user whose entire installation runs on AWS. They're currently using Amazon Linux 2, and would like to move to Amazon Linux 2023, but I can't build packages for 2023 without the libraries I've asked for.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - this is now part of AL2023.4
