### ISSUE TITLE
[Package Request] - rsyslog-gnutls

### ISSUE THREAD

**Issue by DaveB93** [amazonlinux/amazon-linux-2023#384]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

rsyslog-gnutls.x86_64                 8.24.0-57.amzn2.2.0.2          @amzn2-core

**new package request**

**Is this package available in Amazon Linux 2? ** : yes

**Any additional information you'd like to include. (use-cases, etc)** 
currently using this for syslog to graylog

**Comment by ozbenh** [comment]
We do ship `rsyslog-openssl`, would it work for your use case ?

**Comment by DaveB93** [comment]
We’re shipping the logs to graylog,  I’ll have a look at it tomorrow
________________________________

**Comment by DaveB93** [comment]
after some tweaking this does seem to work for me.  ( it took a bit more tweaking than I thought it should, but was probably just a newer vs older version problem.   )  if someone else is trying to do this the documentation page is here: https://www.rsyslog.com/doc/master/concepts/ns_ossl.html

**Comment by ozbenh** [comment]
Thanks. I am going to close this request
