### ISSUE TITLE
[Feature Request] - libffi is really outdated

### ISSUE THREAD

**Issue by matejsp** [amazonlinux/amazon-linux-2023#386]
**Is your feature request related to a problem? Please describe.**
When trying to install some rpms from fedora distros like firefox (for headless testing) or other packages they require libffi.so.8 but AL2023 supports libffi.so.6.

**Describe the solution you'd like**
Support for latest libffi so I can crossompile or use missing RPMs from fedora.

AL2 - libffi-3.0.13-18.amzn2.0.2.x86_64 (3.0 was released in 2013)
AL2023 - libffi-3.1-28.amzn2023.0.2.x86_64 (3.1 was released in 2014)
latest - libffi-3.4.4 (release in 2022)
Fedora 37 - libffi-3.4.4-1.fc37
Fedora 38 - libffi-3.4.4-2.fc38
Fedora 36 - libffi-3.4.2-8.fc36

**Describe alternatives you've considered**
Trying to build firefox manually on AL2023 but there are missing libs ...

**Additional context**

**Comment by matejsp** [comment]
```
bash-5.2# dnf install https://yum.oracle.com/repo/OracleLinux/OL9/appstream/x86_64/getPackage/firefox-102.12.0-1.0.1.el9_2.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL9/baseos/latest/aarch64/getPackage/oracle-indexhtml-9-4.0.1.el9_2.noarch.rpm
Last metadata expiration check: 1:04:24 ago on Sat Jul  1 05:30:53 2023.
firefox-102.12.0-1.0.1.el9_2.x86_64.rpm                                                                                                                                                        10 MB/s | 107 MB     00:10    
oracle-indexhtml-9-4.0.1.el9_2.noarch.rpm                                                                                                                                                      78 kB/s | 256 kB     00:03    
Error: 
 Problem: conflicting requests
  - nothing provides libffi.so.8()(64bit) needed by firefox-102.12.0-1.0.1.el9_2.x86_64
  - nothing provides libffi.so.8(LIBFFI_BASE_8.0)(64bit) needed by firefox-102.12.0-1.0.1.el9_2.x86_64
  - nothing provides libffi.so.8(LIBFFI_CLOSURE_8.0)(64bit) needed by firefox-102.12.0-1.0.1.el9_2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by ozbenh** [comment]
So while we do NOT support running binaries built for foreign distributions on Amazon Linux 2023, it is true that our `libffi` leaves somewhat to be desired.

Unfortunately, the new version is an ABI change. We are experimenting with the possibility of updating it nonetheless along with providing a compat-3.1 package however we cannot promise at this stage that this is something we will release.

**Comment by trivikr** [comment]
Related: Question on discussions for recommended way to install Firefox is at https://github.com/amazonlinux/amazon-linux-2023/discussions/418

**Comment by trivikr** [comment]
FYI: I created request for package libdbusmenu in https://github.com/amazonlinux/amazon-linux-2023/issues/425

**Comment by ozbenh** [comment]
`libffi` has been updated to version 3.4.4 as part of AL2023.2. Note that this is an ABI incompatible change to `libffi.so.8` from `libffi.so.6`. We have kept the earlier version available as part of a `compat-libffi3.1` package which will be kept around at least until AL2023.3, though all dependencies on `libffi` that we ship have been now rebuilt to use the newer library
