### ISSUE TITLE
[Package Request] - mock

### ISSUE THREAD

**Issue by yavor-atanasov** [amazonlinux/amazon-linux-2023#387]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
`mock` is a standard tool for building RPMs. It was available on Amazon LInux 2 and also found in EPEL (main docs page: https://rpm-software-management.github.io/mock/)

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
It is in the list of packages present in Amazon Linux 2 but removed in 2023: https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.1-AL2.html

Also present in EPEL for RHEL distros.

**Any additional information you'd like to include. (use-cases, etc)**
We use `mock` extensively in our CI/CD pipelines to build rpm packages. It's a pretty core fedora/RHEL package and we were surprised it's not found in AL2023. 

As a separate thing, it would be good to understand your thinking in including/excluding packages in AL2023.

**Comment by stewartsmith** [comment]
The only reason it isn't there is that those of us on the AL development team have been using AL2 hosts as the hosts for development, thus the `mock2` Extra in AL2 has been the `mock` that we've been using, and we didn't want to necessarily package the packaging tools that we weren't using yet to build the OS.

That all being said, it's very much about time we had `mock` and friends in AL2023.

**Comment by yavor-atanasov** [comment]
Thank you, Stewart. Do you guys plan to have an extras repository for those packages (like in AL2)?

**Comment by stewartsmith** [comment]
As per the [FAQ](https://aws.amazon.com/linux/amazon-linux-2023/faqs/)

> Q: Does AL2023 have Amazon-Linux-Extras like AL2?

> A: No, AL2023 does not have extras. For higher-level software packages like language runtimes, we will use the quarterly release where we will add major/minor updates to packages as separate namespaced packages in addition to the default package provided in the repository. For example, default Python version in Amazon Linux 2023 may be 3.8, but we will add Python 3.9 (python39) as a separate namespaced package whenever it is made available. These additional packages will closely follow their upstream release cadence and support model and their support policies can be accessed by the package manager for compliance and security use cases. Default packages will continue to be supported throughout the life of AL2023.

So we would just be adding the packages to the main repository, and adding them to the appropriate [support statements here](https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html)

**Comment by yavor-atanasov** [comment]
> For higher-level software packages like language runtimes, we will use the quarterly release where we will add major/minor updates to packages as separate namespaced packages

I think the `python` example is an easy one, because the way different versions of python are packaged already allows them to be installed easilly side by side. They are not published as different versions of the same package, but as _different packages altogether_. That's why in (RH)EL python versions are offered as different `dnf` modules, so you can potentially enable and install all of them:

```
# dnf module list python*
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:11:48 ago on Wed Jul 12 07:47:32 2023.
Rocky Linux 8 - AppStream
Name            Stream         Profiles                Summary
python27        2.7 [d]        common [d]              Python programming language, version 2.7
python36        3.6 [d]        build, common [d]       Python programming language, version 3.6
python38        3.8 [d]        build, common [d]       Python programming language, version 3.8
python39        3.9 [d]        build, common [d]       Python programming language, version 3.9

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

In contrast, a package like `nodejs` (and many others) are not packaged in a way that allows side-by-side install of different versions. And thus in (RH)EL they are provided as different _streams_ of the `nodejs` module, so you can only enable and install one of those:

```
# dnf module list nodejs
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:15:52 ago on Wed Jul 12 07:47:32 2023.
Rocky Linux 8 - AppStream
Name           Stream         Profiles                                      Summary
nodejs         10 [d]         common [d], development, minimal, s2i         Javascript runtime
nodejs         12             common [d], development, minimal, s2i         Javascript runtime
nodejs         14             common [d], development, minimal, s2i         Javascript runtime
nodejs         16             common [d], development, minimal, s2i         Javascript runtime
nodejs         18             common [d], development, minimal, s2i         Javascript runtime

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

I'm bringing up `dnf` modules because they are a way of offering new backwards incompatible versions of various packages (and also that's kind of like `amazon-linux-extras` works, although as far as I can see it provides a similar interface to modules, but just uses regular repos underneath).

Going back to the quote above saying you will provide major versions as "separate namespaced packages", does that mean that, for example with `nodejs`, you will be packaging newer versions as `nodejs20`, `nodejs22` etc?

Both `dnf modules / amazon-linux-extras` and "separate namespaced packages" are valid ways of providing newer packages, but as users arguably we are less interested in having _multiple versions of packages installed at the same time_, but rather we just want to upgrade a package to a newer version on a given system (machine/container). So the `dnf modules / amazon-linux-extras` approach seems more ergonomic.

I appreciate this is tangential to this issue's topic, however it is relevant for a package like `mock` as well. And the way you provide packages impacts the way dependencies are managed.

**Comment by stewartsmith** [comment]
> Do you have any plan to add mock in AMZN2023 ?

Yes.

**Comment by kivengh** [comment]
> > Do you have any plan to add mock in AMZN2023 ?
> 
> Yes.
Good, can you tell us when it be released ?

**Comment by denisgabriel5** [comment]
Hi @stewartsmith, it has been exactly 7 months since you said that you will be adding `mock` to AL2023. Can you give an approximate date for when that will happen?

**Comment by daniejstriata** [comment]
I tried to build `mock` in COPR but it requires `usermode` which required `gtk2` as one of many dependencies.

**Comment by stewartsmith** [comment]
This should make it into the next point release. I just have some tests left to write and it should be good to ship.

**Comment by daniejstriata** [comment]
I see a new version of mock was added to 2023.4: 
```
mock-5.4-1.amzn2023.0.1
mock-core-configs-39.2-1.amzn2023
```

**Comment by halfdime-code** [comment]
Please give the mock a test and see if it meets your requirements. I'll close this out when we hear back from you.

**Comment by stewartsmith** [comment]
Note that our `mock` package requires the explicit `sudo` rather than the (gah... i forget what it's called... it's yet another elevate to `root`) package. This is so we have fewer code paths that can be used to get to `root`, and can thus focus on the standard `sudo` paths.

**Comment by stewartsmith** [comment]
See https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html for it being added, resolving
