### ISSUE TITLE
[Package Request] - Docker Engine

### ISSUE THREAD

**Issue by kenwdelong** [amazonlinux/amazon-linux-2023#400]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
docker-ce
docker-ce-cli
containerd.io
docker-buildx-plugin
docker-compose-plugin

**Is this an update to existing package or new package request?**
It looks like Docker has changed the way it packages everything.
https://docs.docker.com/engine/install/fedora

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Unknown

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by nmeyerhans** [comment]
Hi @kenwdelong. Can you clarify your request? We already ship docker packages, although our package metadata and corresponding structure is unrelated to what's packaged upstream.  It's unlikely that we're going to restructure our packaging to mirror what's done upstream unless somebody can provide a compelling reason to do so.

Of the plugins and components you've listed, the only one we're missing in our packaging is docker-compose-plugin. That was previously requested in #186 and we're tracking it there.

**Comment by kenwdelong** [comment]
Ok, I didn't realize you were changing the package names.  I went to install docker-compose, which led me to docker-compose-plugin, which led me to the new package structure.

I think #186 covers my needs!

**Comment by nmeyerhans** [comment]
Thanks for the update. I'll resolve this issue.
