### ISSUE TITLE
[Bug] - ami-072ec8f4ea4a6f2cf - getting logged out of ssh session when using any dnf or yum command

### ISSUE THREAD

**Issue by Saptorshi7** [amazonlinux/amazon-linux-2023#404]
**Describe the bug**
I am getting logged out of ssh session when using any dnf or yum command.

**To Reproduce**
1. Log in to EC2 using SSH.
2. Run yum <parameter> from ec2-user or root.
3. Getting logged out of session

**Expected behavior**
Yum command should work as expected.

**Screenshots**
[ec2-user@ip-x-x-x-x ~]$ sudo yum update
Connection to x.x.x.x closed by remote host.
Connection to x.x.x.x closed.

[root@ip-x-x-x-x ~]$ yum update
Killed
Connection to x.x.x.x closed by remote host.
Connection to x.x.x.x closed.

**Comment by stewartsmith** [comment]
What instance type are you using? Is it one of the `.nano` ones? Do you have SSM enabled?
You could be getting bitten by the OOM Killer, as these instance types with only 512MB RAM are quite resource constrained (and enabling SSM can certainly use up a bunch of extra memory).

We're investigating what we can do to make it a bit harder to hit OOM with a bunch of workloads, including a selection of DNF transactions.

As a workaround, you can look at enabling some swap space on the instance, either on disk or using zram.

**Comment by Saptorshi7** [comment]
Hi @stewartsmith ,

Yes I launched a t3a.nano instance. I'm not sure if SSM was enabled.
I think it is enabled by default...

So right now, the latest AMI cannot be used with nano instance types without swap?

**Comment by stewartsmith** [comment]
If you have SSM configure sim your AWS account to manage all instances then that will be enough.

The reason I call SSM out is that the SSM and CloudWatch agents themselves use a decent chunk of memory, and when SSM is doing it's association dance shortly after launch, running the various SSM documents leaves very little memory for other tasks.

In my recent test, it left as little as 97MB available for any user initiated process. Without SSM enabled for the instance, it was ~280MB.

As someone who remembers the "eMacs stands for Eight Megs And Constantly Swapping" joke, as well as what Windows 95 was like with the minimum requirements of 4MB RAM, I feel distinctly my age when I say that "97MB of memory isn't much room for any workload".

These smaller Instance types are resource constrained and you are going to hit limitations one way or another.

**Comment by stewartsmith** [comment]
FYI in the [AL2023.2 release notes](http://localhost:8000/linux/al2023/release-notes/relnotes-2023.2.20230920.html) we have noted that `zram` based swap is now enabled by default for instance types with less than 800MB of memory. This should help alleviate what is likely being hit in this issue. As such, I'll close this issue for now. If still seeing such problems, we can dive into what could be other causes.
