### ISSUE TITLE
[Bug] - "Connection to X closed by remote host" avec "sudo yum"

### ISSUE THREAD

**Issue by rimiti** [amazonlinux/amazon-linux-2023#407]
After creating an EC2 instance (**t3a.micro**) with AMI: **ami-06935448000742e6b**

When, I connect me though SSH and I type:

```
sudo yum check-update
```

The SSH connection is directly closed.

Screenshot:
![screenshot_2023_07_26_16h41-36@2x](https://github.com/amazonlinux/amazon-linux-2023/assets/28003749/11d12c40-1d4e-4115-a78c-1335dd58ecdd)

How to solve it?
Regards,

**Comment by ozbenh** [comment]
Which region is this AMI ID from ?

**Comment by ozbenh** [comment]
Ah found it in `eu-west-1`  :-)

**Comment by ozbenh** [comment]
Hrm... I just tried launching that same AMI in the same region on a t3a and cannot reproduce your issue:
```
$ sudo yum check-update
Last metadata expiration check: 0:01:00 ago on Thu Jul 27 03:15:11 2023.
============================================================================================================================================
WARNING:
  A newer release of "Amazon Linux" is available.

  Available Versions:

  Version 2023.1.20230725:
    Run the following command to upgrade to 2023.1.20230725:

      dnf upgrade --releasever=2023.1.20230725

    Release notes:
     https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html

============================================================================================================================================
[ec2-user@ip-172-31-45-7 ~]$ 
```
Do you have SSM enabled in your account ? can you run "free" and "ps faux" after ssh'ing in ?

**Comment by ozbenh** [comment]
I can reproduce on a `t3a.nano` ... the instance is basically running out of memory. We are looking at options to see what we can do to help but in the meantime, I recommend adding a swapfile

**Comment by ozbenh** [comment]
Another approach that worked for me is to enable `zram` ...  as root:
```
# modprobe zram
# zramctl -a lz4hc -f -s 128M
/dev/zram0
# mkswap /dev/zram0
Setting up swapspace version 1, size = 128 MiB (134213632 bytes)
no label, UUID=fc175470-d144-4aae-b440-ecac3273a9bb
# swapon /dev/zram0
```
Fedora comes with scripts to make this easier and appears to enable it by default, we are going to investigate what's the best approach for AL2023 going forward.

**Comment by rimiti** [comment]
Yes, it has been launch with a `t3a.nano`.
I just change the AMI for `ami-02df7c0eecb64fb85` and it now working well.

**Comment by ozbenh** [comment]
That's an ARM AMI, you switched to an ARM instance type then ? How much memory does it have ?

**Comment by stewartsmith** [comment]
FYI in the [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) we have noted that `zram` based swap is now enabled by default for instance types with less than 800MB of memory. This should help alleviate what is likely being hit in this issue.

(release notes URL will be live in not too much time)
