### ISSUE TITLE
[Package Request] - container-selinux

### ISSUE THREAD

**Issue by zackbradys** [amazonlinux/amazon-linux-2023#409]
**What package is missing from Amazon Linux 2023? Please describe and include package name.** 
* container-selinux-2.205

**Is this an update to existing package or new package request?** 
* Update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.** 
* Available in various public external sources.

**Any additional information you'd like to include. (use-cases, etc)**
* Various technologies and organizations rely or require SELinux. It appears container-selinux has not be updated from container-selinux-2.189 when it was originally included in AL2023. Specifically, I'm requesting for it to be updated to meet the requirements of rke2-selinux, a dependency for the open source Rancher Kubernetes Engine 2 (RKE2).
* Additionally, it would beneficial to continue to update the package based on similar RPM based distributions of Linux.

**Comment by dweomer** [comment]
> * Additionally, it would beneficial to continue to update the package based on similar RPM based distributions of Linux.

This is the big one for me. I mean, in the least please do consider a one-time update of the `container-selinux` package to the [current el8 stream version](http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/container-selinux-2.218.0-1.module_el8+454+d7ef4b8d.noarch.rpm) but ideally this should keep up with [el9 stream](https://mirror.stream.centos.org/9-stream/AppStream/source/tree/Packages/container-selinux-2.219.0-1.el9.src.rpm).

**Comment by stewartsmith** [comment]
What issues are you seeing with the current package?

**Comment by zackbradys** [comment]
I would not say any direct issues with `container-selinux v2.189`, but my main concern is compatibility with various commercial products, open-source projects, and security/feature updates to the package itself. It is important to ensure you are upgrading/updating all packages, if there are no breaking changes. Most linux distributions have are stabilized at versions above the one included in `AL2023`, such as `container-selinux v.2.205` or even `container-selinux v2.18.0`

Specifically, my issue related to Rancher Kubernetes RKE2 and its `rke2-selinux` package/policies requiring and depending on `container-selinux v2.205` or above.

Comparing the recent changes, there's a lot of value missing by not upgrading the package:
* Exact version in other distros: https://pkgs.org/download/container-selinux
* `v2.189.0` to `v2.205.0` - https://github.com/containers/container-selinux/compare/v2.189.0...v2.205.0
* `v2.189.0` to `v2.218.0` - https://github.com/containers/container-selinux/compare/v2.189.0...v2.218.0

**Comment by zackbradys** [comment]
Hey @stewartsmith, any questions or concerns related to this? Are we going to see this added to the roadmap?

**Comment by zackbradys** [comment]
Hey @stewartsmith, I'm curious if there is an update on this issue?

**Comment by ozbenh** [comment]
Sorry for the delay, we have engineers working on selinux investigating this as we speak.

**Comment by zackbradys** [comment]
Appreciate the update! Glad to hear it

**Comment by zackbradys** [comment]
Hey @ozbenh and @stewartsmith, how is the investigation going? Any update?

**Comment by ozbenh** [comment]
We recently updated it to `container-selinux-2.222.0-325.amzn2023`, does that solve your issues ?

**Comment by zackbradys** [comment]
Awesome news! Thank you for the update. I will do some testing and validation and update the ticket accordingly. @ozbenh

**Comment by zackbradys** [comment]
Appreciate all the work from the AL2023 Team! It looks like it is resolved 🚀🚀
