### ISSUE TITLE
[Package Request] - Update Cairo to version 1.17.6 

### ISSUE THREAD

**Issue by Gakeikei** [amazonlinux/amazon-linux-2023#411]
Cairo 1.17.6  is not supported in AL2023. As Cairo 1.17.4, supported in AL2023 now, has color rendering issue, the issue can cause critical business impact. Please help to add Cairo 1.17.6 in AL2023 repositories.

**Comment by ozbenh** [comment]
Thanks, we'll look into it asap

**Comment by sktomer** [comment]
Available from AMI/container version 2023.1.20230825.0
