### ISSUE TITLE
[Bug] - amazonlinux:latest docker-image yum conflicts

### ISSUE THREAD

**Issue by vegaaz** [amazonlinux/amazon-linux-2023#416]
**Describe the bug**
When running the latest version of the amazonlinux docker-image and try to install curl, you will get a conflict error message.

**To Reproduce**
1. run latest amazonlinux docker-image
2. run 'yum update && yum install curl'

**Expected behavior**
Yum will check if there is a new version of curl and install it.

**Screenshots**
![amazonlinux_error](https://github.com/amazonlinux/amazon-linux-2023/assets/61321118/57fef6ce-fffe-4aa8-b6b3-a7df800a6a74)

**Comment by stewartsmith** [comment]
Have a look at https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#curl-minimal

By default, we install a minimal version of curl which doesn't include support for more esoteric protocols, and thus both has fewer dependencies and is less likely to be affected by curl CVEs. You can swap this for the full curl package if needed, but for most people the minimal should suffice.
