### ISSUE TITLE
[Feature Request] - Update toolbx image on quay.io

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#420]
**Is your feature request related to a problem? Please describe.**
There is a toolbx image for amzn2 and AL2022. Will it be possible to update the images used by Toolbx to use the AL2023 images instead?
https://github.com/toolbx-images/images/issues/93

**Describe the solution you'd like**
I would find it extremely convenient if I can use toolbx to run local images of AL2023. Then I won't need to pop into Docker instance each time I want to test a new package. I could do most of my work jumping into toolbx to test compatibility with packages. They team over at toolbx just have not gone and updated to use AL2023 instead.

**Comment by stewartsmith** [comment]
My PR has been merged upstream, resolving.

**Comment by daniejstriata** [comment]
I tested it yesterday. I found my user could not `sudo` but I could `su -` and the update sudoers with my username explicitly, even though my user was added to wheel group and wheel is supposed to sudo.
