### ISSUE TITLE
[Package Request] - mod_security

### ISSUE THREAD

**Issue by AdamJCavanaugh** [amazonlinux/amazon-linux-2023#429]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Security module for the Apache HTTP Server

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes

**Any additional information you'd like to include. (use-cases, etc)**
Allow pretty straightforward upgrade from AL:2 to AL:2023

**Comment by stewartsmith** [comment]
The announcement on https://www.modsecurity.org/ was the reason we weren't including mod_security from the start on AL2023, as it lead us to very much want to wait and see what happened with the upstream project.

If there's places you can point to that contain good information on the current and future state of the upstream project, that would be valuable.

**Comment by AdamJCavanaugh** [comment]
I understand sponsorship of ModSecurity has ended, but the open source project continues to receive updates. I won't pretend to understand any of the state of the project with or without Trustwave. I was having TLS 1.3 issues in AL2 and hoped an upgrade to AL2023 might be the answer.

If an update from the mod_security project on their future is needed for the package to be added, then I'm fine for this issue to be closed.

**Comment by D1987S** [comment]
Any updates? The missing mod_security package is blocking me to upgrade to AL2023 which I was really looking forward to.

**Comment by AnthonyDawson** [comment]
Same as above; cannot upgrade to AL2023 unless you provide security packages like mod sec and fail2ban. Will soon move to Huawei temporarily unless there is imminent news.

**Comment by illph8ed** [comment]
See the announcement from OWASP [here](https://owasp.org/blog/2024/01/09/ModSecurity.html)

> By formally assuming custodianship of the entire project, OWASP can now steer ModSecurity’s development with a holistic view, fostering even tighter integration between the core rule set and the underlying framework. Trustwave, while stepping down from its custodial role, expresses immense gratitude for its time with ModSecurity.

> The future of ModSecurity is brighter than ever. Under OWASP’s stewardship, this powerful WAF is poised to further solidify its position as a cornerstone of web application security, protecting countless websites against the ever-evolving threat landscape. We, as an industry, can all stand to benefit from this open-source collaboration, empowering developers, and security professionals alike to build and maintain safer applications in the years to come.

**Comment by prophoto** [comment]
Can we please get an update here? This is a very important package and should be included.

**Comment by tkaya-ipsi** [comment]
Is there a workaround for this in the meantime?

**Comment by boeschl** [comment]
What else is required if OWASP already communicated the direction and follow up of the product?
Is this something just to try to push AWS WAF service ?

**Comment by AnthonyDawson** [comment]
That's my conclusion!

**Comment by AnthonyDawson** [comment]
I moved to Ubuntu linux has everything you need and good support.

**Comment by D1987S** [comment]
> What else is required if OWASP already communicated the direction and follow up of the product? Is this something just to try to push AWS WAF service ?

I think so

**Comment by ozbenh** [comment]
We don't generally withdraw packages to "push a service". This needs to be re-evaluated internally.

**Comment by ozbenh** [comment]
One thing we noticed while looking at it more closely is that 2.x is in maintenance mode, but 3.x isn't out yet ... this doesn't neccessarily bode well for a package we would have to support for several years unfortunately. We are still digging though.

**Comment by ozbenh** [comment]
Ah it is there, it's just been broken down differently ... `libmodsecurity` has the core, then there are separate "connectors"

**Comment by ozbenh** [comment]
Sadly it's also not ready for Apache (https://github.com/owasp-modsecurity/ModSecurity-apache) ... there's only an nginx connector around.  Apparently v2 is still the goto option for Apache, though it's in maintainance mode.

**Comment by ozbenh** [comment]
We are looking at adding `mod_security` 2.x to an upcoming AL2023 release.

**Comment by ozbenh** [comment]
AL2023.6 is out with
```
Name         : mod_security
Version      : 2.9.7
Release      : 6.amzn2023.0.1
Architecture : aarch64
Size         : 267 k
Source       : mod_security-2.9.7-6.amzn2023.0.1.src.rpm
Repository   : amazonlinux
Summary      : Security module for the Apache HTTP Server
URL          : http://www.modsecurity.org/
License      : Apache-2.0
Description  : ModSecurity is an open source intrusion detection and prevention engine
             : for web applications. It operates embedded into the web server, acting
             : as a powerful umbrella - shielding web applications from attacks.
```
The release notes should be available shortly

**Comment by D1987S** [comment]
I have installed on the first instance and is working properly! 👌
Thanks again.

**Comment by paulez** [comment]
We have released mod_security and mod_security_crs with the Amazon Linux 2023.6 release. Please refer to release notes for [2023.6.20241010](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.6.20241010.html).
