### ISSUE TITLE
[Bug] - /etc/cron.d is missing

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#432]
**Describe the bug**
I find that `/etc/cron.d` is missing by default and I had to create it. I use many crons in there when I don't want them to run daily or hourly but on a time of my choosing. Should the directory not be there by default?

**Comment by matejsp** [comment]
You need to install it 
```
# dnf install chrony
```

**Comment by stewartsmith** [comment]
https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#cron

Does suggest that the move to systemd timers as the preferred approach, and that you can still enable classic cron as an option.

**Comment by daniejstriata** [comment]
Thanks for clarification @stewartsmith, I did not immediately connect the dots that /etc/cron.d is `cronie` specific but the other `/etc/cron.*` directories are not.
