### ISSUE TITLE
[Bug] - mysql_secure_installation does not remove blank password

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#439]
**Describe the bug**
I installed the mariadb server:
`mariadb105-server-10.5.18-1.amzn2023.0.1.aarch64`
and ran the `mysql_secure_installation` command where I updated the root password. After it completed I am still able to login with any or no password. 
Remote access is locked down as configured.

**To Reproduce**
1. Install and start mariadb server
2. run `mysql_secure_installation`
3. change root password
![image](https://github.com/amazonlinux/amazon-linux-2023/assets/13314239/d9cb173b-8788-41ab-ad76-ffb747714da2)
4. log in to mysql using root always succeeds 

**Expected behavior**
Running `mysql_secure_installation` should change root access.

**Screenshots**
Login always succeeds on the local host:
![image](https://github.com/amazonlinux/amazon-linux-2023/assets/13314239/bd14ba03-abc4-4bb4-a640-b02baf273760)
![image](https://github.com/amazonlinux/amazon-linux-2023/assets/13314239/b26e48b2-e178-4890-87de-0e800cf684cf)

**Comment by limmike** [comment]
Root login in mariadb 10.4.3 and higher uses [unix_socket](https://mariadb.com/kb/en/authentication-plugin-unix-socket/). 
Only system root user is able to connect, other users such as ec2-user are unable to. 

```
[~]$ whoami
ec2-user
[~]$ mysql -uroot -p
Enter password:
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
[ec2-user@ip-172-31-23-222 ~]$ sudo mysql -uroot -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1185435
Server version: 10.5.18-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB [(none)]> show create user root@localhost;
+----------------------------------------------------------------------------------------------------+
| CREATE USER for root@localhost                                                                     |
+----------------------------------------------------------------------------------------------------+
| CREATE USER `root`@`localhost` IDENTIFIED VIA mysql_native_password USING 'invalid' OR unix_socket |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

**Comment by daniejstriata** [comment]
Thank you for your clarification!
