### ISSUE TITLE
[Package Request] - pipx to cleanly install Python packages

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#446]
I would appreciate that pipx be made available to AL2023. This will help me to install python packages without messing up dependencies as pipx will contain the python application in its own environment.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No.

**Comment by elsaco** [comment]
@daniejstriata in absence of a package you could install `pipx` using  `python3 -m pip install --user pipx` command. If you don't have `python3-pip` installed already, add it before running the command. Detailed instructions are at https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/

Sample run on latest release of AL2023:

```
[ec2-user: ~]$ pipx install cowsay
  installed package cowsay 6.0, installed using Python 3.9.16
  These apps are now globally available
    - cowsay
done! ✨ 🌟 ✨
[ec2-user: ~]$ cowsay -t moo
  ___
| moo |
  ===
   \
    \
      ^__^
      (oo)\_______
      (__)\       )\/\
          ||----w |
          ||     ||
```
