### ISSUE TITLE
[Package Request] - AWS Corretto 21

### ISSUE THREAD

**Issue by pluralistix** [amazonlinux/amazon-linux-2023#449]
Hey dear people from AL202~2~3.

While it would be perfectly possible, to install it from yum.corretto.aws, we'd like to avoid to install different versions of Corretto from different packagers/maintainers. And so I would be nice, if it could apear in that

```
❯ docker run amazonlinux:2023 dnf search corretto-devel -q 2>/dev/null
========================= Name Matched: corretto-devel =========================
java-1.8.0-amazon-corretto-devel.x86_64 : Amazon Corretto development environment
java-11-amazon-corretto-devel.x86_64 : Amazon Corretto 11 development tools
java-17-amazon-corretto-devel.x86_64 : Amazon Corretto 17 development tools
```

list (after (presumingly) September 19  😄 ) 

Thank you
Christian

**Comment by stewartsmith** [comment]
(while not committing to anything), I will comment that you're not the only one to think of that :)

**Comment by stewartsmith** [comment]
```
bash-5.2# dnf search java-21-amazon-corretto
...
java-21-amazon-corretto-devel.aarch64 : Amazon Corretto 21 development tools
java-21-amazon-corretto-headless.aarch64 : Amazon Corretto headless development environment
java-21-amazon-corretto-javadoc.aarch64 : Amazon Corretto 21 API documentation
java-21-amazon-corretto-jmods.aarch64 : Amazon Corretto 21 jmods
```

Corretto 21 is part of AL2023.2. The [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) will be up shortly mentioning this.
