### ISSUE TITLE
[Bug] - CPU info from /proc/cpuinfo

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#455]
Maybe not a bug, but on Graviton CPU I get no CPU Name on AL2023 and only the info listed below. Is that intended or can it be improved? I get a lot of extra info on Intel/AMD like:
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
stepping	: 7
microcode	: 0x5003005
cpu MHz		: 3100.618
cache size	: 36608 KB
fpu		: yes
```

from a `t4g.small`:

`cat /proc/cpuinfo`
```
processor	: 0
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 1
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

```
lscpu works as expected.

**Comment by sam-aws** [comment]
The content of `/proc/cpuinfo` is architecture dependent, so this is "expected" in the sense that this is what an arm64 kernel will currently output: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/kernel/cpuinfo.c#n177
AL2023 shouldn't differ from upstream here, do you see different fields on other arm64 devices?

**Comment by daniejstriata** [comment]
@sam-aws That for looking into this. I had a look my my raspberry-pi and found you are correct. The output is similar.
