### ISSUE TITLE
[Package Request] - redis

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2023#457]
Can you please package redis 6 or 7 with AL2023?
https://redis.io/

I installed redis from the `amzn2extra-redis6` AL2 repo on my old install that I want to migrate to AL2023.

**Comment by limmike** [comment]
Install as follows
```
sudo dnf install -y redis6
```

If it helps, there is a [CloudFormation template](https://github.com/aws-samples/ec2-lamp-server) that install LAMP stack, certbot, redis and other packages on AL2023. You can refer to [AL2023 user-data](https://github.com/aws-samples/ec2-lamp-server/blob/main/AmazonLinux-2023-LAMP-server.yaml).

**Comment by daniejstriata** [comment]
Thanks for sharing the CloudFormation template too!
