### ISSUE TITLE
[Package Request] - ftp, iptraf-ng, ncdu, pbzip2, tmpwatch

### ISSUE THREAD

**Issue by mbialozor** [amazonlinux/amazon-linux-2023#469]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
ftp, iptraf-ng, ncdu, pbzip2, tmpwatch

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Amazon Linux 2:
ftp.aarch64          0.17-67.amzn2.0.2    @amzn2-core
iptraf-ng.aarch64    1.1.4-7.amzn2        @amzn2-core
ncdu.aarch64         1.14.1-1.el7         @epel      
pbzip2.aarch64       1.1.12-1.el7         @epel
tmpwatch.aarch64     2.11-5.amzn2.0.1     @amzn2-core

Fedora 37:
ftp.x86_64           0.17-90.fc37     fedora 
iptraf-ng.x86_64     1.2.1-6.fc37     fedora 
ncdu.x86_64          1.19-1.fc37      updates
pbzip2.x86_64        1.1.13-7.fc37    fedora 
tmpwatch.x86_64      2.11-23.fc37     fedora 

**Any additional information you'd like to include. (use-cases, etc)**
Packages are available from standard Fedora repositories.

**Comment by ozbenh** [comment]
Anyh chance you can break this up into a request per package ? Additionally, I don't think we want to carry the legacy `ftp` client, why would you use that ? not only the protocol itself is insecure and inefficient, but the client is cumbersome... you can do `ftp` transfers with `curl` just fine (including with `curl-minimal` which is our default) and we do ship `lftp` which supports `ftp` among others.

**Comment by mbialozor** [comment]
Hi @ozbenh. Sure, I can create separate requests. Regarding ftp package, in general, I agree with you. Let me check if we can switch to other solutions.

**Comment by mbialozor** [comment]
@ozbenh, there you go:

- https://github.com/amazonlinux/amazon-linux-2023/issues/484
- https://github.com/amazonlinux/amazon-linux-2023/issues/485
- https://github.com/amazonlinux/amazon-linux-2023/issues/486
- https://github.com/amazonlinux/amazon-linux-2023/issues/487

Let me close this request then.
