### ISSUE TITLE
[Bug] - 'curl-minimal' package depends on 'grub2-efi-aa64-ec2' package

### ISSUE THREAD

**Issue by mbialozor** [amazonlinux/amazon-linux-2023#470]
**Describe the bug**
There are two packages with 'curl' utility available on AL2023:
- curl
- curl-minimal (installed by default)

When I try to remove `curl-minimal` package, DNS also tries to remove `grub2-efi-aa64-ec2` (grub image used with EC2 on efi-aa64 systems). I'm not sure how curl relates to grub images, but I'd like to use the full version of this tool.

**To Reproduce**
```
08:56:23 (root@al2023 ~)$ dnf remove curl-minimal
Error: 
 Problem: The operation would result in removing the following protected packages: grub2-efi-aa64-ec2
(try to add '--skip-broken' to skip uninstallable packages)
```

**Expected behavior**
Possibility to remove `curl-minimal` and install `curl`.

**Additional context**
`08:55:57 (root@al2023 ~)$ cat /etc/system-release
Amazon Linux release 2023 (Amazon Linux)
`

**Comment by stewartsmith** [comment]
Try 'dnf swap' rather than remove.

What dnf isn't showing you with a simple 'dnf remove curl-minimal' is the dependency chain that ends up there (it'll be long). The 'swap' operation will do the remove and install in the same transaction, thus 'dnf' can check for satisfied dependencies at the end of the swap of 'curl-minimal' to 'curl'.

Out of interest, what makes you need curl over curl-minimal?

**Comment by mbialozor** [comment]
Hi @stewartsmith. Thanks for the tip, indeed it work as expected.
`13:16:43 (root@al2023 ~)$ dnf swap curl-minimal curl
Last metadata expiration check: 1 day, 1:40:26 ago on Wed Sep 27 11:38:43 2023.
Dependencies resolved.

 Package                                                  Architecture                                        Version                                                             Repository                                               Size

Installing:
 curl                                                     aarch64                                             8.2.1-1.amzn2023.0.3                                                amazonlinux                                             338 k
Removing:
 curl-minimal                                             aarch64                                             8.2.1-1.amzn2023.0.3                                                @System                                                 385 k

Transaction Summary
Install  1 Package
Remove   1 Package
`

Now I have to figure out how to do this via Ansible module: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
It looks like it's impossible for the moment: https://github.com/ansible/ansible/issues/29857

> Out of interest, what makes you need curl over curl-minimal?
In general, we aim to configure AL2023 the same way as all of our AL2 are. If 'curl-minimal' functionality is sufficient, we'll switch to it.

**Comment by stewartsmith** [comment]
`curl-minimal` is almost certainly sufficient, and has the benefit of disabling a lot of the features that have been repeat stars in `curl` CVEs, as well as it has a smaller batch of dependencies (which also end up having a selection of CVEs).

**Comment by ozbenh** [comment]
It might be worth re-opening a feature request for ansible (or submitting a pull request with a change) to ansible since using minimal packages such as curl-minimal is now percolating into Fedora and possibly RHEL.

**Comment by mbialozor** [comment]
Thank you Guys. We can consider this case as closed. Have a good day!

**Comment by mbialozor** [comment]
Thank you Guys. We can consider this case as closed. Have a good day!
