### ISSUE TITLE
Please add support for GRE tunneling protocol 

### ISSUE THREAD

**Issue by vkgarg2023** [amazonlinux/amazon-linux-2023#478]
Please add support for GRE in Amazon  Linux 2023

**Comment by stewartsmith** [comment]
I assume you just mean the `ip_gre` kernel module?

```
bash-5.2# rpm -qf /usr/lib/modules/*/kernel/net/ipv4/ip_gre.ko
kernel-6.1.55-75.123.amzn2023.aarch64
```

It's there already :)

Feel free to re-open if there's another missing piece you're looking for.
