### ISSUE TITLE
[Package Request] - AWS Elastic Fabric Adapter (EFA)

### ISSUE THREAD

**Issue by bryantbiggs** [amazonlinux/amazon-linux-2023#488]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
- EFA-enabled kernel & drivers

**Is this an update to existing package or new package request?**
- New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
- No

**Any additional information you'd like to include. (use-cases, etc)**
- Docs https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable
 
 Note: this would be a single package for the host level requirements (kernel and drivers). libfabric and OpenMPI shown in the docs are already available in AL2023 RPMs, and for containerized workloads these are installed in the container and not on the host. This package is the equivalent of `./efa_installer.sh --minimal` for the EFA installer

**Comment by stewartsmith** [comment]
The EFA installer now supports Amazon Linux 2023, and the documentation has been updated to reflect that.

**Comment by bryantbiggs** [comment]
@stewartsmith do you happen to have a link to the updated documentation, my searching has failed me

**Comment by stewartsmith** [comment]
> @stewartsmith do you happen to have a link to the updated documentation, my searching has failed me

It's actually the same docs as mentioned in the original filing of this issue, it's just that AL2023 is mentioned there now: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable
