### ISSUE TITLE
[Package Request] - openarc, opendkim, spamassassin-milter, spamassassin-milter-postfix, boinc-client

### ISSUE THREAD

**Issue by samarart27** [amazonlinux/amazon-linux-2023#49]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
EPEL 8

**Is this an update to existing package or new package request?**
Update from EPEL 7 on AL2 extras.

**Is this package available in Amazon Linux 2?**
Yes, EPEL 7 is available thru AL2 extras.

**Comment by stewartsmith** [comment]
Since AL2022 is derived from Fedora and not CentOS 8 or RHEL8, directly mapping in EPEL8 is unlikely to have the result you're looking for as not many of EPEL package dependencies would be resolvable.

Are there specific packages you are looking for? We'd prefer at looking into bringing them into Amazon Linux.

**Comment by samarart27** [comment]
Sure thing, had to go look and compare the current included and removed packages with some of the ones I'm using. I see now some are already included, but I'm missing some of them:

certbot.noarch  1.3.0-1.el7
  
fail2ban-firewalld.noarch  0.10.5-2.el7  but I see  firewalld  0.9.4-1.amzn2022 

I see the included opendmarc but I'm missing openarc.x86_64 1.0.0-0.1.Beta0.el7  and opendkim.x86_64  2.11.0-0.1.el7 

I also see spamassassin being removed so I guess it would be useless to ask for spamass-milter.x86_64  0.4.0-7.el7 and spamass-milter-postfix.noarch  0.4.0-7.el7 

And I know this one is just asking for too much boinc-client.x86_64 7.16.1-4.el7

I can make anything I need so well, I was just asking for the EPEL repository because it made things easier...

Best regards...

**Comment by mightypenguin** [comment]
(Not amazon support)
I've had success using pip to install certbot.

You do have to somehow get a newer version of pip and find the magic versions of dependent python libraries like "cryptography" but it IS possible.

**Comment by samarart27** [comment]
Thanks... I'll wait for the GA release and then start testing with it... I'm also waiting for a new availability zone to be closer before moving/updating anything...

**Comment by singhpaul** [comment]
We'd also like to see **fail2ban** and **fail2ban-firewalld** included as OS packages please.

And while we were able to install **certbot** with PIP using the instructions [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2022.html#letsencrypt-2022) it would be great to see this as part of a standard OS package as well.

**Comment by stewartsmith** [comment]
Going to use https://github.com/amazonlinux/amazon-linux-2023/issues/383 to track `fail2ban` separately.

**Comment by ozbenh** [comment]
`certbot` seems to install fine with `pip install certbot` ... it does display an alarming error about `awscli` which I believe can be ignored, the end result gets installed nonetheless.

We are looking into the `awscli` error... it seems to relate to a combination of two things:
* A too restrictive version dependency in the PyPI version of `awscli` on `python-cryptography` which probably should be addressed by the `awscli` team (we've engaged with them)
* `pip` being unable to detect that `awscli` is already installed as an RPM package

That said, it appears that the install succeeds nonetheless despite the scary error message.

As for actually packaging `certbot`, it requires a fairly significant amount of python module dependencies that we do not currently ship, so while we would like to eventually package it, it's not going to happen in the immediate future unfortunately.

**Comment by ozbenh** [comment]
So for installing `certbot` via pip, see my comment here: https://github.com/amazonlinux/amazon-linux-2023/issues/87#issuecomment-1687307291

**Comment by stewartsmith** [comment]
`spamassassin` has shipped with AL2023.4 as per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html

**Comment by ozbenh** [comment]
`fail2ban` has now shipped as well
