### ISSUE TITLE
[Package Request] - etckeeper, etckeeper-dnf, etckeeper-bzr

### ISSUE THREAD

**Issue by nomike** [amazonlinux/amazon-linux-2023#499]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

etckeeper.noarch : Store /etc in a SCM system (git, mercurial, bzr or darcs)
etckeeper-dnf.noarch : DNF plugin for etckeeper support
etckeeper-bzr.noarch : Support for bzr with etckeeper

**Is this an update to existing package or new package request?**

New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

EPEL

**Any additional information you'd like to include. (use-cases, etc)**

Automatically manages /etc in a version control system. The DNS plugin allows to automatically get new commits on every run of DNF. This allows for traceability of config file changes.

**Comment by daniejstriata** [comment]
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/69
There is no bazaar package for AL2023 so etckeeper-bzr is not going to build without fixing that dependency.

**Comment by nomike** [comment]
Duplicate of #69.

Bazar is optional. It would also work fine without bazar support for most users.
