### ISSUE TITLE
[Bug] - Not obvious a1 isn't supported -  Kernel panic with a1 instance type

### ISSUE THREAD

**Issue by troyriley42** [amazonlinux/amazon-linux-2023#50]
When initializing an a1 instance type with the AL2022 arm OS the instance receives a kernel panic.

[    1.060420] Run /init as init process
[    1.069460] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004
[    1.072308] CPU: 0 PID: 1 Comm: init Not tainted 5.10.75-82.359.amzn2022.aarch64 #1
[    1.075312] Hardware name: Amazon EC2 a1.medium/, BIOS 1.0 11/1/2018
[    1.077824] Call trace:
[    1.078830]  dump_backtrace+0x0/0x1dc
[    1.080318]  show_stack+0x24/0x34
[    1.081665]  dump_stack+0xd0/0x12c
[    1.083046]  panic+0x158/0x36c
[    1.084287]  do_exit+0x3e8/0x440
[    1.085596]  do_group_exit+0x44/0xac
[    1.087041]  get_signal+0x174/0x908
[    1.088436]  do_signal+0x1bc/0x29c
[    1.089803]  do_notify_resume+0x10c/0x33c
[    1.091416] Kernel Offset: disabled
[    1.092812] CPU features: 0x0240022,21002008
[    1.094515] Memory Limit: none
[    1.095754] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004 ]---

1. Create an instance with AMI ami-0c3c6bc06281e0c6c or ami-08c954b5b118f85d1 using any of the a1 instance types
2. View the console logs once available
3. Kernel panic will be in the logs

**Expected behavior**
AL2022 Arm AMIs will be able to start on a1 instance types

**Additional context**
Instances using the m6g start properly, and are usable.

**Comment by stewartsmith** [comment]
We do mention in the User Guide that only Graviton 2 and higher is supported, and that means a1 instances are not.

This is to enable better optimization for Graviton 2 and beyond.

Are there places we could better document this?

**Comment by troyriley42** [comment]
Thanks for pointing this out. I didn't realize a1 instances were not Graviton 2 compatible.

**Comment by troyriley42** [comment]
I'll close this issue as it is known a1 instances aren't a valid type for AL2022.

**Comment by stewartsmith** [comment]
Actually, since the error message here is really not obvious as to what is the matter, I'm going to reopen the issue so we can use it to track ensuring we give an error message that is obvious what's wrong.

**Comment by troyriley42** [comment]
Ok, sounds good. Really if there was a link, or some added documentation around what is and isn't valid Graviton 2 instance types that would be helpful. Perhaps explicitly stating these items, or that a1 isn't a Graviton 2 environment in the FAQs for AL2022 arm. I must admit I did see something about Graviton 2 in the documentation, but that bit of information didn't really mean much to me by itself.

**Comment by ozbenh** [comment]
This should be improved now. Closing
