### ISSUE TITLE
[Package Request] - cabextract

### ISSUE THREAD

**Issue by mbialozor** [amazonlinux/amazon-linux-2023#504]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
cabextract

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes (from EPEL)

**Any additional information you'd like to include. (use-cases, etc)**
cabextract is a program which can extract files from cabinet (.cab) archives.

**Comment by stewartsmith** [comment]
Looks like https://src.fedoraproject.org/rpms/cabextract is in EPEL, and not in AL2 https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL2.html or AL1 https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL1.html

**Comment by tpthaler** [comment]
I need this as well, as it's a requirement to install the Microsoft Fonts package (which is critical to many applications).

**Comment by tpthaler** [comment]
@mbialozor if you build it "cabextract" from the source, and then run your rpm -ivh --nodeps package-name.rpm; that is the work around I did.

**Comment by mbialozor** [comment]
@tpthaler, yup, I also need "cabextract" as the Microsoft Fonts dependency. As we use Amazon Linux under mission critical applications I can't (and don't want to) rely on anything compiled from source. We need proper support from OS vendor.

**Comment by tpthaler** [comment]
@mbialozor as a temporary (easy) stop gap; I found that if you have installed the fonts on a similar architecture AWS Linux 2 instance (from: /usr/share/fonts/msttcore/) to your new AWS Linux 2023 instance that they work properly.

**Comment by mbialozor** [comment]
Nice hacking, @tpthaler :).

**Comment by tpthaler** [comment]
> Nice hacking, @tpthaler :).

out of desperation.... so far very unimpressed with AWS Linux 2023. Makes me feel like I'm back in the 90's.

**Comment by mbialozor** [comment]
> Makes me feel like I'm back in the 90's.
@tpthaler, isn't is a fantastic feeling? You feel like teenager again :D.

**Comment by stewartsmith** [comment]
`cabextract` is now part of the AL2023.3.20240205 release.
