### ISSUE TITLE
[Package Request] - supervisor

### ISSUE THREAD

**Issue by jbarmanet** [amazonlinux/amazon-linux-2023#505]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
supervisor 

**Is this an update to existing package or new package request?**
New package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes it was available in Linux 2 via EPEL, it was installed this way:
```
sudo amazon-linux-extras enable epel
sudo yum install -y epel-release
sudo yum -y update
sudo yum -y install supervisor
```

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by stewartsmith** [comment]
The https://src.fedoraproject.org/rpms/supervisor package appears in EPEL, and wasn't in AL1 https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL1.html or AL2 https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL2.html - and it does seem like there's a heavy overlap here with `systemd` functionality.

Why not just use `systemd`?
