### ISSUE TITLE
[Package Update Request] - PostgreSQL 15.4

### ISSUE THREAD

**Issue by GrahamCampbell** [amazonlinux/amazon-linux-2023#509]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

postgres 15.4

**Is this an update to existing package or new package request?**

Update. Current version is 15.0.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

N/A

**Any additional information you'd like to include. (use-cases, etc)**

Needed by bref: https://github.com/brefphp/aws-lambda-layers/pull/122/files#r1328637947.

**Comment by GrahamCampbell** [comment]
cc @stewartsmith

**Comment by stewartsmith** [comment]
Agree that we should update PostgreSQL 15 to the latest minor release of it.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20231018.html - there's PostgreSQL 15.4 in AL2023 now, resolving.
