### ISSUE TITLE
[Package Update Request] - libsodium 1.0.19

### ISSUE THREAD

**Issue by GrahamCampbell** [amazonlinux/amazon-linux-2023#513]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

libsodium 1.0.19

**Is this an update to existing package or new package request?**

Update. Current version is very old.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

N/A

**Any additional information you'd like to include. (use-cases, etc)**

Needed by bref: https://github.com/brefphp/aws-lambda-layers/pull/122/files#r1350635922.

**Comment by GrahamCampbell** [comment]
cc @stewartsmith

**Comment by GrahamCampbell** [comment]
Well, kinda. 1.0.18 is years old, though. ;)

**Comment by ozbenh** [comment]
Yes but the whole world is built against 1.0.18, there is no telling what will break if we just "update" to the latest. This is true of almost all your other update requests. Amazon Linux isn't meant to track every latest upstream of every project out there, we need to provide some form of stability, especially ABI stablility. The balance between this and "newness" is why we have a 2 years major release cadence.

**Comment by GrahamCampbell** [comment]
Would you consider the bump in 2023.3?

**Comment by ozbenh** [comment]
Probably not. Not without very very good justifications.

**Comment by GrahamCampbell** [comment]
These two are important reasons to upgrade:

> * New AEADs: AEGIS-128L and AEGIS-256 are now available in the crypto_aead_aegis128l_*() and crypto_aead_aegis256_*() namespaces. AEGIS is a family of authenticated ciphers for high-performance applications, leveraging hardware AES acceleration on x86_64 and aarch64. In addition to performance, AEGIS ciphers have unique properties making them easier and safer to use than AES-GCM. They can also be used as high-performance MACs.
> * The HKDF key derivation mechanism, required by many standard protocols, is now available in the crypto_kdf_hkdf_*() namespace. It is implemented for the SHA-256 and SHA-512 hash functions.

**Comment by jedisct1** [comment]
1.0.19 is fully backwards-compatible.

**Comment by stewartsmith** [comment]
There's an soname bump for the newer `libsodium` - so anyone building against it will need to rebuild. For the one package in AL2023 that depends on it (`php8.2`, specifically the sodium module), we'll do a rebuild to catch this.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - the updated `libsodium` is part of AL2023.4

**Comment by GrahamCampbell** [comment]
Thanks @stewartsmith. How do we know what version of AL2023 is used by Lambda?
