### ISSUE TITLE
[Package Request] - Curl 8.4.0

### ISSUE THREAD

**Issue by RaresMiliton** [amazonlinux/amazon-linux-2023#517]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
curl 8.4.0
libcurl 8.4.0

**Is this an update to existing package or new package request?**
Update, as it resolves security issues - https://github.com/curl/curl/discussions/12026

**Any additional information you'd like to include. (use-cases, etc)**
I saw that Amazon Linux AMI is on the distros mailing list, but I want to know if the update will be addressed in the next repository release

**Comment by samueloph** [comment]
Hello @RaresMiliton,

The two CVEs listed have already been fixed on the package for the 8.3.0 version (we backport fixes).

You can see the details at:
https://alas.aws.amazon.com/AL2023/ALAS-2023-377.html
