### ISSUE TITLE
[Package Request] - fetchmail

### ISSUE THREAD

**Issue by tickerBerkin** [amazonlinux/amazon-linux-2023#524]
Fetchmail:  a remote mail retrieval and forwarding utility

New package request

Is available in Amazon Linux 2, also Fedora
Source       : fetchmail-6.4.37-1.fc37.src.rpm
URL          : http://www.fetchmail.info/

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - this is now part of AL2023.4
