### ISSUE TITLE
[Bug] - Error occurs for customer when testing yum updates within ansible. Customer is requesting yum ansible module support for Amazon Linux 2022 / AL2022.

### ISSUE THREAD

**Issue by liesenml** [amazonlinux/amazon-linux-2023#53]

**Comment by stewartsmith** [comment]
Ansible is now included in the Amazon Linux 2023 repositories. See the [AL2023.2 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.2.20230920.html) for details.

(release notes are running a bit behind the release, so may take up to a day to appear at that URL from when I'm typing this)
