### ISSUE TITLE
[Package Request] - python 3.11.6 

### ISSUE THREAD

**Issue by rkarthikr** [amazonlinux/amazon-linux-2023#541]
**What package is missing from Amazon Linux 2023? Please describe and include package name.** python 3.11.6 

**Is this an update to existing package or new package request?** Update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.** 

**Any additional information you'd like to include. (use-cases, etc)**  We have identified a bug on 3.11.2 and is preventing us from using it and need to move to python 3.11.6 . This is already supported in Lambda

**Comment by nmeyerhans** [comment]
3.11.6 is available as of the AL2023.3 release just published.
