### ISSUE TITLE
[Bug] - adduser is symlinked to useradd, an incompatible tool

### ISSUE THREAD

**Issue by hawicz** [amazonlinux/amazon-linux-2023#542]
**Describe the bug**
`/usr/sbin/adduser` is symlinked to `/usr/sbin/useradd`, but the latter is not compatible with the command line options that adduser supports.
Compare e.g. https://man7.org/linux/man-pages/man8/useradd.8.html (slightly newer shadow-utils 4.11, vs amazon linux 4.9) with
https://manpages.ubuntu.com/manpages/xenial/en/man8/adduser.8.html

**To Reproduce**
`adduser --disabled-login someuser`
or
`adduser --disabled-password someuser`
or
`adduser --quiet someuser`
or
`adduser --gecos "some gecos" someuser`
or any of the other options that useradd does not support.

**Expected behavior**
`-bash: adduser: command not found`, or if it's going to be there, then it should be a wrapper that translates the command line args when possible, and when it can't, displays an error explaining that it isn't actually the normal adduser command.

**Desktop (please complete the following information):**
 - OS: Amazon Linux 20231030

**Comment by nmeyerhans** [comment]
This configuration is standard and expected in the Fedora world.

```plain
$ docker pull fedora:39                                                  
39: Pulling from library/fedora
Digest: sha256:95c88cea36312cfd73613f1c56d8a8db8e63be5cd884cfc97ba9475d0a45eac5
Status: Image is up to date for fedora:39
docker.io/library/fedora:39
$ docker run -it --rm fedora:39 ls -l /usr/sbin/adduser /usr/sbin/useradd
lrwxrwxrwx 1 root root      7 Aug 16 00:00 /usr/sbin/adduser -> useradd
-rwxr-xr-x 1 root root 145648 Aug 16 00:00 /usr/sbin/useradd
```

The `adduser` script you're referring to is unique to Debian and derivatives.  On Fedora-based systems, `adduser` == `useradd`.

**Comment by hawicz** [comment]
That discrepancy is unfortunate, but thank you for the explanation.
