### ISSUE TITLE
[Package Request] - Tomcat 10

### ISSUE THREAD

**Issue by sdroselius** [amazonlinux/amazon-linux-2023#546]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

Apache Tomcat 10

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Tomcat 10 appears to be available on the Elastic Beanstalk AL2023 platform.

https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.java

Would it be possible to make it available for package install on EC2 AL2023?

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by friarzen** [comment]
This is now a required dependency for new spring-boot apps, it seems.

**Comment by ozbenh** [comment]
We are working on adding this to an upcoming release, thank you.

**Comment by matejsp** [comment]
Spring Boot does not need Tomcat installed on the system. Spring Boot server can be tomcat, jetty or undertow. And it is bundled with application. If you run legacy Spring application, yes then you need tomcat on the system.

**Comment by rturner-edjuster** [comment]
> We are working on adding this to an upcoming release, thank you.

any rough timeline? weeks? months? many months? years?

**Comment by rproserpio** [comment]
> Also, which version? 10.0? 10.1? (10.1 would match the version provided in Elastic Beanstalk Tomcat platforms)

Just as a reminder, 10.0 is superseded and EOL since 2022.

**Comment by ozbenh** [comment]
AL2023.6 is out with
```
Name         : tomcat10
Epoch        : 1
Version      : 10.1.29
Release      : 1.amzn2023.0.1
Architecture : noarch
Size         : 92 k
Source       : tomcat10-10.1.29-1.amzn2023.0.1.src.rpm
Repository   : amazonlinux
Summary      : Apache Servlet/JSP Engine, RI for Servlet 6.0/JSP 3.1 API
URL          : http://tomcat.apache.org/
License      : ASL 2.0
Description  : Tomcat is the servlet container that is used in the official Reference
             : Implementation for the Java Servlet and JavaServer Pages technologies.
             : The Java Servlet and JavaServer Pages specifications are developed by
             : Sun under the Java Community Process.
             : 
             : Tomcat is developed in an open and participatory environment and
             : released under the Apache Software License version 2.0. Tomcat is intended
             : to be a collaboration of the best-of-breed developers from around the world.
```
The release notes will be updated shortly

**Comment by rturner-edjuster** [comment]
It seems Tomcat 10 packages cannot be installed side-by-side with Tomcat 9 packages, even though they have separate config locations, file locations, etc.
`dnf` is unhappy with Tomcat 9 being installed already.
This makes migration awkward.
Any plans to address this?
