### ISSUE TITLE
[Package Request] - NodeJs 20

### ISSUE THREAD

**Issue by bitfrost** [amazonlinux/amazon-linux-2023#549]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Please offer Node 20, the current LTS version
**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by nmeyerhans** [comment]
NodeJS 20 is available with AL2023.3, which we just published.  The packages are named `nodejs20` to avoid conflicting with version 18, which remains available as `nodejs`.

**Comment by bitfrost** [comment]
Thank you!

**Comment by csvan** [comment]
Don't forget to update symlinks after installing the above

```
sudo ln -s -f /usr/bin/node-20 /usr/bin/node
sudo ln -s -f /usr/bin/npm-20 /usr/bin/npm
```

**Comment by kevin-cgc** [comment]
> Don't forget to update symlinks after installing the above (and please do correct me if there is a more appropriate way to do this)

Maybe with `alternatives`?

```
sudo alternatives --install /usr/bin/node node /usr/bin/node-20 90
sudo alternatives --install /usr/bin/npm npm /usr/bin/npm-20 90
```

**Comment by melutovich** [comment]
@nmeyerhans 
Is there any official Amazon Linux 2023 suggested way to switch from node 18 to node 20?

node 18 goes end of life 2025 April 30

And looking forward toward node 22
https://github.com/amazonlinux/amazon-linux-2023/issues/725

**Comment by bitfrost** [comment]
> [@nmeyerhans](https://github.com/nmeyerhans) Is there any official Amazon Linux 2023 suggested way to switch from node 18 to node 20?
node 20 was released as nodejs20 
I suggest:
dnf install -y nodejs20 && dnf clean all
ln -s /usr/bin/node-20 /usr/bin/node
ln -s /usr/bin/npm-20 /usr/bin/npm
