### ISSUE TITLE
[Bug] - AL2023 arm64 enable frame buffer

### ISSUE THREAD

**Issue by lukebakare** [amazonlinux/amazon-linux-2023#559]
**Describe the bug**
Amazon Linux 2023 arm64 image doest not boot.
Image used: https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/kvm-arm64/al2023-kvm-2023.2.20231113.0-kernel-6.1-arm64.xfs.gpt.qcow2

**To Reproduce**
Import the disk image and boot.

**Expected behavior**
VM should boot to login prompt.

**Screenshots**
<img width="502" alt="Screenshot 2023-11-26 at 02 04 53" src="https://github.com/amazonlinux/amazon-linux-2023/assets/59092280/9b6b2bf8-17ea-43cd-9364-81fc4f9c039d">

**Comment by stewartsmith** [comment]
Have you attached the serial console and checked there?

**Comment by lukebakare** [comment]
On the serial port it is showing the expected output, however on the terminal console it just hangs on that screenshot.
Serial port output:

[    1.778132] uhci_hcd 0000:01:00.0: init 0000:01:00.0 fail, -16
[    4.205518] systemd[1]: Started systemd-journald.service - Journal Service.
[    4.241961] systemd-journald[1576]: Received client request to flush runtime journal.
[    4.720314] mousedev: PS/2 mouse device common for all mice
[    4.777858] pps_core: LinuxPPS API ver. 1 registered
[    4.778457] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    4.978583] PTP clock support registered
[    5.013888] e1000e: Intel(R) PRO/1000 Network Driver
[    5.015036] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    5.015727] e1000e 0000:02:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    5.105288] e1000e 0000:02:00.0 0000:02:00.0 (uninitialized): registered PHC clock
[    5.171115] e1000e 0000:02:00.0 eth0: (PCI Express:2.5GT/s:Width x1) 00:0c:29:f6:94:64
[    5.171675] e1000e 0000:02:00.0 eth0: Intel(R) PRO/1000 Network Connection
[    5.172281] e1000e 0000:02:00.0 eth0: MAC: 3, PHY: 8, PBA No: 000000-000
[    5.237307] e1000e 0000:02:00.0 ens160: renamed from eth0
[    5.291028] RPC: Registered named UNIX socket transport module.
[    5.291511] RPC: Registered udp transport module.
[    5.291840] RPC: Registered tcp transport module.
[    5.292168] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    6.114709] random: crng init done
[    7.251553] ISO 9660 Extensions: Microsoft Joliet Level 3
[    7.252322] ISO 9660 Extensions: RRIP_1991A


Amazon Linux 2023
Kernel 6.1.61-85.141.amzn2023.aarch64 on an aarch64 (-)

vm-hostname login:

**Comment by lukebakare** [comment]
This is now resolved with the latest image.
