### ISSUE TITLE
[Feature Request] - Update awscrt to 0.19.17

### ISSUE THREAD

**Issue by lisenet** [amazonlinux/amazon-linux-2023#563]
**Is your feature request related to a problem? Please describe.**
AL2023 comes with `python3-awscrt-0.16.7-1.amzn2023.0.1`. This is outdated and [no longer supported](https://github.com/boto/botocore/blob/develop/setup.py#L33) by the latest version of `boto3` (>=1.33.0).

**Describe the solution you'd like**
Update `awscrt` to `0.19.17`.

**Describe alternatives you've considered**
Freeze `boto3` version to `1.29.7`.

**Comment by nmeyerhans** [comment]
Done as of the AL2023.3 release just published.
