### ISSUE TITLE
[Package Request] - /usr/lib/rpm/rpmdb_verify

### ISSUE THREAD

**Issue by conniefan** [amazonlinux/amazon-linux-2023#564]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Not really a package, but would like this tool:
usr/lib/rpm/rpmdb_verify

**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes

**Any additional information you'd like to include. (use-cases, etc)**
Use case is to check for db corruption

**Comment by ozbenh** [comment]
I believe that `rpm --verifydb` is the new way to do this

**Comment by conniefan** [comment]
> I believe that `rpm --verifydb` is the new way to do this

Thank you!!!
