### ISSUE TITLE
[Package Request] - tomcat_native

### ISSUE THREAD

**Issue by mtallenca** [amazonlinux/amazon-linux-2023#568]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
ELB with Tomcat 10 and Amazon Linux 2023 has tomcat, but is missing package tomcat-native.

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
This package is available in Amazon Linux 2

**Any additional information you'd like to include. (use-cases, etc)**
Attempting to update my environment from Tomcat 8.5 / Amazon Linux 2 to Tomcat 10 / Amazon Linux 2023 - tomcat_native package is missing

**Comment by mtallenca** [comment]
I'm now building tomcat native as part of my server config in .ebextensions.  I've included the file we're using.  It's been used in production for almost a month now.

packages:
  yum:
    apr-devel.x86_64: []
    openssl-devel: []
    gcc: []

files:
  "/tmp/build_tomcat_native.sh":
    owner: root
    group: root
    mode: "000755"
    content: |
      #! /bin/bash
      CONFIGURED=`ls /usr/lib/libtcnative* | wc -l`
      if [ $CONFIGURED = 0 ]
        then
          cd /tmp
          SRC=tomcat-native-2.0.6-src
          TAR=$SRC.tar.gz
          curl https://dlcdn.apache.org/tomcat/tomcat-connectors/native/2.0.6/source/$TAR > $TAR
          tar zxvf $TAR
          cd $SRC/native
          ./configure --with-apr=/usr/bin/apr-1-config --with-java-home=/usr/lib/jvm/java --with-ssl=/usr/include/openssl --prefix=/usr
          make && make install
      fi

container_commands:
    native:
        command: "sh /tmp/build_tomcat_native.sh"

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.6.20241010.html there is now `tomcat-native` in AL2023.6
