### ISSUE TITLE
[Bug] - bash_completion doesn't function as-is after install

### ISSUE THREAD

**Issue by rrehbein** [amazonlinux/amazon-linux-2023#572]
**Describe the bug**

When attempting to use a bash-shell intecatively for some development activities, the bash_completion package does not function without modifying a file it installs. 

**To Reproduce**

1.Create minimal AL2023 instance
- User Data:
```
yum install -y bash-completion
```
2. ssh in as ec2-user or ssm-user and switch to bash
3. Attempt to use bash-completion, eg: `kill -s <tab tab>`

**Expected behavior**

Expecting to see suggested options after double-tab for supported commands.
```sh
ec2-user@ip-.... $ kill -s 

ABRT      CONT      INT       KILL      QUIT ....snip...
```

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version 2023

**Additional context**

A fix:

```sh
sudo chmod +x /etc/profile.d/bash_completion.sh
```

Possibly the rpm's specs are missing the executable bit for the packaged file.

There appear to be other files in `/etc/profile.d` that don't have an executable bit too. Possibly a similar issue for those packages too.

**Comment by rrehbein** [comment]
Closing. It was a misdiagnosis on my part.

**Comment by ozbenh** [comment]
Working fine in my tests ... you haven't actually closed it... should we ?
