### ISSUE TITLE
[Package Request] - golang1.21

### ISSUE THREAD

**Issue by darin-holloway** [amazonlinux/amazon-linux-2023#575]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Staying current with golang release

golang1.21

**Is this an update to existing package or new package request?**

update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Not exactly, but the codebuild team just pushed a brand new amazon linux 2 based image out for this support instead of amazon linux 2023

https://github.com/aws/aws-codebuild-docker-images/blob/master/al-lambda/x86_64/go1.21/Dockerfile

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by michal-sa** [comment]
Go 1.22 has now been released (https://go.dev/blog/go1.22) so maybe it could be updated to that instead of 1.21.

**Comment by darin-holloway** [comment]
Since this request there is updated documentation on golang support in al2023, no timeline commitments, but an acknowledgement that the version of go shipped within al2023 will eventually change during its lifetime.  https://docs.aws.amazon.com/linux/al2023/ug/go.html

**Comment by codypenta** [comment]
Adding an additional data point for PFR justification, go 1.21 and 1.22 add a few wanted features (along with others) but some of the important ones are:

- [Profile guided automation](https://go.dev/blog/pgo)
- [Structured Logging](https://go.dev/blog/slog)
- [net/http.ServeMux](https://go.dev/pkg/net/http#ServeMux)

Pretty much allows defining solid APIs with structured logging and the ability to profile/optimize this api in the standard library ecosystem

**Comment by stewartsmith** [comment]
[AL2023.5](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html) comes with `golang` version `1.22`, so closing this as completed.
