### ISSUE TITLE
[Package Request] - GFS2

### ISSUE THREAD

**Issue by madrover** [amazonlinux/amazon-linux-2023#582]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

Global File System 2 or **GFS2** is a [shared-disk file system](https://en.wikipedia.org/wiki/Clustered_file_system#Shared-disk_file_system) for [Linux](https://en.wikipedia.org/wiki/Linux) computer clusters. GFS2 allows all members of a cluster to have direct concurrent access to the same shared [block storage](https://en.wikipedia.org/wiki/Block_storage), in contrast to [distributed file systems](https://en.wikipedia.org/wiki/Clustered_file_system#Distributed_file_systems) which distribute data throughout the cluster.

Package name: gfs2-utils

**Is this an update to existing package or new package request?**
This is a new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, as per [Packages in Amazon Linux 2 not in Amazon Linux 2023](https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL2.html) it has not been ported though.

**Any additional information you'd like to include. (use-cases, etc)**

We need to implement active/passive high availability features to an application which requires disk based persistence.

**Comment by stewartsmith** [comment]
Do the EFS or FSx services work for your use case?

**Comment by stewartsmith** [comment]
Would FSx Lustre (requested here: https://github.com/amazonlinux/amazon-linux-2023/issues/309) fit the use case then?

**Comment by madrover** [comment]
Talking with the application provider they have suggested to use multiattach EBS with a cluster manager, eg Pacemaker. Since this is a simple active/passive HA architecture and we don't require concurrent access between nodes it seems that approach would be sufficient and we will probably follow that route.
Thanks for your suggestions!

**Comment by stewartsmith** [comment]
> Talking with the application provider they have suggested to use multiattach EBS with a cluster manager, eg Pacemaker. Since this is a simple active/passive HA architecture and we don't require concurrent access between nodes it seems that approach would be sufficient and we will probably follow that route.
> 
> Thanks for your suggestions!

No problem! Glad could help point to what should be a nice and simple solution.

I'm going to close this request for GFS2 as not planned for now. If more data emerges on why GFS2 is needed over the other options, we can always reopen and reconsider.
