### ISSUE TITLE
[Package Request] - Microsoft .NET 8

### ISSUE THREAD

**Issue by nan-coupa** [amazonlinux/amazon-linux-2023#601]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

Microsoft .NET 8:
https://learn.microsoft.com/en-us/dotnet/core/install/linux-fedora

**Is this an update to existing package or new package request?**
New (this should not replace .NET 6)

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

.NET packages are available on Fedora 39:
```
# dnf search dotnet | grep '8.0'
Last metadata expiration check: 0:00:45 ago on Fri Jan  5 22:37:43 2024.
dotnet-apphost-pack-8.0.x86_64 : Targeting Pack for Microsoft.NETCore.App 8.0
dotnet-hostfxr-8.0.x86_64 : .NET command line host resolver
dotnet-runtime-8.0.x86_64 : NET 8.0 runtime
dotnet-sdk-8.0.x86_64 : .NET 8.0 Software Development Kit
dotnet-sdk-8.0-source-built-artifacts.x86_64 : Internal package for building .NET 8.0 Software Development Kit
dotnet-targeting-pack-8.0.x86_64 : Targeting Pack for Microsoft.NETCore.App 8.0
dotnet-templates-8.0.x86_64 : .NET 8.0 templates
```

**Any additional information you'd like to include. (use-cases, etc)**
We want to deploy .NET applications in Amazon Linux 2023. .NET 8 is the latest LTS which will be supported through Nov 2026:
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by stewartsmith** [comment]
`dotnet8.0` is available in AL2023.5, see the [release notes for the first AL2023.5 release](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html) for details.
