### ISSUE TITLE
[Package Request] - HPN-SSH (high performance ssh)

### ISSUE THREAD

**Issue by dirkpetersen** [amazonlinux/amazon-linux-2023#604]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

HPN -SSH is a high performance replacement of OpenSSH: https://www.psc.edu/hpn-ssh-home/hpn-ssh-installation/ 
While OpenSSH offers somewhere between 50 and 150 MiB/s throughput, HPN -SSH can saturate a 10G pipe and will deliver more than 1 GiB/s throughput.

**Is this an update to existing package or new package request?**

No

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

No

**Any additional information you'd like to include. (use-cases, etc)**

I spoke with the syadmins at PSU and they have HPN-SSH as the primary sshd on more then 80% of their machines listening on port 22  while openssh is listening on a higher port as a fallback option . The remaining machines (e.g. core infrastructure) only have openssh installed. 

This would be an awesome optional addition to Amazon Linux since it focuses on performance. If installed by user openssh should be moved to different port.

**Comment by stewartsmith** [comment]
At this time it's not something we're going to consider adding to Amazon Linux. The combination of it being a research project, being security critical component, and the OpenSSH package having a healthy upstream as well as a decent number of downstream patches (in both Fedora and Amazon Linux), all adds up to this being a non-trivial amount of work for what is a relatively minor benefit. We see customers having other methods of bulk data transfer and high performance access in HPC environments, and not relying on SSH.
