### ISSUE TITLE
[Package Request] - php-pecl-redis

### ISSUE THREAD

**Issue by ds00424** [amazonlinux/amazon-linux-2023#606]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
php-pecl-redis

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
available in Amazon Linux 2

**Any additional information you'd like to include. (use-cases, etc)**
We use this php package to check the status of our aws redis server which we use for php sessions among other things
Only alternative I see is to install pear as well as php-devel (yuk) and then do "sudo pecl install redis" which downloads and compiles.
But that's not acceptable for a production server.

TY

**Comment by katzueno** [comment]
Duplicate issue
#328
