### ISSUE TITLE
[Package Request] - php 8.2 current versions

### ISSUE THREAD

**Issue by chris-king-medibank** [amazonlinux/amazon-linux-2023#609]
I am currently sitting on a php defect that appears to be fixed in php 8.2.5 (released 13 Apr 2023)
but this version is not available to me via dnf packages

Amazon Linux 2023 is consistently behind in php versions and does not offer current versions making it hard to support our application.
I would to see that more current versions are available (AL2023 current php version = 8.2.4, latest php version 8.2.14)

Supporting php 8.3 would also be a valid alternative.

Hoping that that do not have to move to alternate distribution or consider building core component from source

**Comment by stewartsmith** [comment]
FYI: https://github.com/amazonlinux/amazon-linux-2023/issues/573 is covering PHP 8.3, will keep this issue as updating 8.2.x

**Comment by chris-king-medibank** [comment]
> FYI: #573 is covering PHP 8.3, will keep this issue as updating 8.2.x

thanks @stewartsmith, two questions from this

1. what date will php 8.3 be available
2. is the policy changing on supporting current php versions within 8.2 and 8.3

**Comment by chris-king-medibank** [comment]
PHP 8.2.9 is now available via packages and I have now bypassed my critical defect.
However the non-current issue still applies with PHP now on 8.2.15 and 8.2.9 being released 6 month ago (August 2023)
https://www.php.net/ChangeLog-8.php#8.2.9

**Comment by chris-king-medibank** [comment]
very happy to see that ```sudo dnf upgrade --releasever=2023.3.20240205``` is now providing php 8.2.15

**Comment by stewartsmith** [comment]
I was wondering if that update made that release. I'll resolve this issue as its tracking an update to PHP 8.2, and that's done.
