### ISSUE TITLE
[Missing Documentation] - Bare-metal installation

### ISSUE THREAD

**Issue by denisgabriel5** [amazonlinux/amazon-linux-2023#613]
Is there any way I could run this bare-metal? Also, what do I need to recompile the kernel using kernel options that I want?

**Comment by stewartsmith** [comment]
Amazon Linux does not currently support being run on bare metal systems. We do support being run on `.metal` EC2 Instance types.

Rebuilding the kernel with custom options is a bit out of scope for what we're looking to have in our documentation. It doesn't differ from the normal methods though.

**Comment by denisgabriel5** [comment]
I want to manually rebuild the kernel and boot it bare-metal. Is there a recommended `.config` file?

**Comment by jwh1981** [comment]
Sorry if I'm resurrecting an ancient thread but I took the default config from the kernel package and then just added in support I needed (in my case compiling in scsi, scsi disk, and then the Intel sata controller). It boots bare metal just fine for me on a Ivybridge Dell.

**Comment by NothinRandom** [comment]
@jwh1981 could you share steps on getting a bootable AL23 on baremetal?  I'm adding in full disk encryption and secure boot and any lessons learned is greatly appreciated.  Thanks
