### ISSUE TITLE
[Package Request] - PostgreSQL-16 client

### ISSUE THREAD

**Issue by syampillai** [amazonlinux/amazon-linux-2023#618]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
PostgreSQL-16 client is not available.

**Is this an update to existing package or new package request?**
No

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No. This package is generally available on other Linux platforms (both RPM-based and DEB-based).

**Any additional information you'd like to include. (use-cases, etc)**
I have migrated to RDS PostgreSQL 16. Now, I can't use any of the AL versions (AL2 or AL2023) to dump my DB because older versions of pg_dump won't work on the server 16.

**Comment by stewartsmith** [comment]
We have https://github.com/amazonlinux/amazon-linux-2023/issues/516 for tracking PostgreSQL 16, so I'll close this issue as duplicate and we can track in that single issue.
