### ISSUE TITLE
[Package Update Request] - Enable php-zip for PHP 8.1

### ISSUE THREAD

**Issue by Jreginato** [amazonlinux/amazon-linux-2023#622]
**Describe the bug**
We are using the Amazon Linux 2023 environment with PHP 8.1, but we are having some problems with the ZIP library.

It is installed on the server, but in PHP it is not recognized using the php -m command.

We've already tried to include extension=zip and other things in php.ini, but it still isn't recognized.

We have already tried to uninstall the library and install it again, but without success.

We also tried to install another type of library, but it generates an incompatibility error with other AWS files.

How can I resolve this? the ZIP is not displayed at all in phpinfo.

**Comment by adereis** [comment]
Hi.

From what I see, the zip module/package is available for `php-8.2`, but not `php-8.1`. I tested it with `php8.2` and `php8.2-zip` installed, and the library is showing up in the output of `php -m`.

If php8.2 works for you, you might want to try the following command:

`sudo dnf install php8.2 php8.2-zip --allowerasing` (please double check the transaction before accepting the proposed changes)

If you need further assistance, please share the list of your php packages installed. You can get that with `rpm -qa | grep php`.

Cheers.

**Comment by stewartsmith** [comment]
`php-zip` for PHP 8.1 is part of AL2023.4 as per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html
