### ISSUE TITLE
[Package Update Request] - Docker 25

### ISSUE THREAD

**Issue by triarius** [amazonlinux/amazon-linux-2023#624]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
[Docker 25.0.1](https://github.com/moby/moby/releases/tag/v25.0.1) is the latest version at the time of writing, but AL2023 does not have it or Docker 25.0.0 yet.

**Is this an update to existing package or new package request?**
Update to existing package.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No

**Any additional information you'd like to include. (use-cases, etc)**
Remote cache support for [ECR has landed](https://aws.amazon.com/blogs/containers/announcing-remote-cache-support-in-amazon-ecr-for-buildkit-clients/), but it looks like Docker needs to be upgraded to a v25 or later to fully support it.

**Comment by mwebber** [comment]
Please, also include `docker compose`, see request #186

**Comment by simonctrlz** [comment]
`docker 25.0.3-1.amzn2023.0.1` seems to have hit the repos.
