### ISSUE TITLE
[Package Request] - python-ldap

### ISSUE THREAD

**Issue by stoynsim** [amazonlinux/amazon-linux-2023#634]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
python-ldap

**Is this an update to existing package or new package request?**
new package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes (amzn2-core repo)

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by paulez** [comment]
python-ldap has been added to Amazon Linux 2023.5 release, see release notes with the added package list: https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html
