### ISSUE TITLE
[Package Update Request] - nodejs 20.11.1 'Iron' (LTS)

### ISSUE THREAD

**Issue by harvey-sg** [amazonlinux/amazon-linux-2023#637]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
nodejs 
**Is this an update to existing package or new package request?**
Please update the existing nodejs20 to 20.11.1 (security release)
**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by matejsp** [comment]
Current version in al2023.4 is 20.11.1-1.amzn2023.0.2.
dnf install nodejs20
