### ISSUE TITLE
[Package Request] - OpenVPN

### ISSUE THREAD

**Issue by danionescu** [amazonlinux/amazon-linux-2023#654]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

openvpn (https://openvpn.net/)

**Is this an update to existing package or new package request?**

New package request.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

It is available in Amazon Linux 2, installable with the following command:

`amazon-linux-extras install epel -y && yum install openvpn -y`

**Any additional information you'd like to include. (use-cases, etc)**

The use case is connecting to a VPN, for secure connections with some API providers.

**Comment by julianf19** [comment]
Same problem!

**Comment by stewartsmith** [comment]
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/79
