### ISSUE TITLE
[Package Request] - Ruby 3.3 and PostgreSQL 16 updates

### ISSUE THREAD

**Issue by toncid** [amazonlinux/amazon-linux-2023#657]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

`ruby3.3`
`postgresql16`

**Is this an update to existing package or new package request?**

New packages, i.e. updates to the current ones available (`ruby3.2` and `postgresql15`).

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

No.

**Any additional information you'd like to include. (use-cases, etc)**

Regular updates to the latest product releases.

**Comment by stewartsmith** [comment]
I've moved the PostgreSQL 15 update to https://github.com/amazonlinux/amazon-linux-2023/issues/717 which was delivered in AL2023.4

**Comment by toncid** [comment]
Thanks @stewartsmith. However, this ticket is about PG v16 and Ruby v3.3. 

Any info when those might be available?

**Comment by stewartsmith** [comment]
No information to share on those at the moment.

**Comment by stewartsmith** [comment]
Since we have other issues for both, I'll close this one and we can track in the individual issues.
