### ISSUE TITLE
[Bug] - Upgrade sudo to 1.9.15p3

### ISSUE THREAD

**Issue by kivengh** [amazonlinux/amazon-linux-2023#664]
**Describe the bug**
We are experiencing a but it the 'sudo' package version include in AMZN2023 (1.9.14-1.p3.amzn2023.0.1). 
Can you upgrade it to 1.9.15p3 (https://bugzilla.sudo.ws/show_bug.cgi?id=1062) ?

**To Reproduce**
It's all is on the sudo bugzilla : https://bugzilla.sudo.ws/show_bug.cgi?id=1062

**Expected behavior**
sudo allowed rules apply to path with relatives names

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/vercmp-AL2023.3-AL2023.4.html `sudo` 1.9.15 is part of AL2023.4
