### ISSUE TITLE
[Package Request] - hiredis

### ISSUE THREAD

**Issue by saxonww** [amazonlinux/amazon-linux-2023#671]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

[hiredis](https://github.com/redis/hiredis), including hiredis, hiredis-devel, and hiredis-debuginfo.

**Is this an update to existing package or new package request?**

New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

The package is not available in Amazon Linux 2. It is available in EPEL, see https://src.fedoraproject.org/rpms/hiredis

**Any additional information you'd like to include. (use-cases, etc)**

This is an optional dependency of syslog-ng, and would be useful for #639.

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.3-AL2023.4.html the `hiredis` package is available as of AL2023.4
