### ISSUE TITLE
[Package Update Request] - nodejs 20.12.1

### ISSUE THREAD

**Issue by harvey-sg** [amazonlinux/amazon-linux-2023#684]
**Is this an update to existing package or new package request?**
Please update the existing nodejs20 to 20.12.1

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/vercmp-AL2023.3-AL2023.4.html in AL2023.4 there is `nodejs20` version 20.12.2
