### ISSUE TITLE
[Package Request] - etckeeper

### ISSUE THREAD

**Issue by adelton** [amazonlinux/amazon-linux-2023#69]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

etckeeper - Store /etc in a SCM system - https://etckeeper.branchable.com/

**Is this an update to existing package or new package request?**

New package in 2022.

**Is this package available in Amazon Linux 2?**

No. But it is in Fedora and EPEL: https://src.fedoraproject.org/rpms/etckeeper

**Number of users impacted**

No idea.

**Comment by daniejstriata** [comment]
I need etckeeper so I took the src package from EPEL9, disabled Bazaar and built the attached:
[etckeeper.zip](https://github.com/amazonlinux/amazon-linux-2023/files/12601182/etckeeper.zip)

**Comment by stewartsmith** [comment]
As per https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.4.20240319.html - `etckeeper` is now part of AL2023.4
