### ISSUE TITLE
[Package Request] - mod_auth_openidc

### ISSUE THREAD

**Issue by eric51893** [amazonlinux/amazon-linux-2023#690]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
[mod_auth_openidc](https://github.com/OpenIDC/mod_auth_openidc) 
mod_auth_openidc is an OpenID Certified™ authentication and authorization module for the Apache 2.x HTTP server that implements the OpenID Connect Relying Party functionality.

**Is this an update to existing package or new package request?**
New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes it is available in Amazon Linux 2 in the amzn2-core repository

**Any additional information you'd like to include. (use-cases, etc)**
There is a dependency apr-util which is then dependent on apr-util-bdb in AL 2.  apr-util-bdb is also not in the AL 2023 yum repositories currently, although apr-util is there already.

apr-util is the apache portable runtime (APR) utilities and apr-util-bdb is Berkley database driver for the same.

**Comment by llcepick** [comment]
This should be updated to very latest version to have all security fixes from https://github.com/OpenIDC/mod_auth_openidc

**Comment by szarkos** [comment]
Package mod_auth_openidc has been released to the AL2023 repositories. Please give it a test and let us know if you have questions.

**Comment by stewartsmith** [comment]
It's in the `2023.6.20241031` release, which is currently rolling out.
