### ISSUE TITLE
[Package Request] - apr-util-bdb

### ISSUE THREAD

**Issue by eric51893** [amazonlinux/amazon-linux-2023#691]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
[Apache Portable Runtime Utilities Berkley database driver](https://apr.apache.org/)
apr-util-bdb 

**Is this an update to existing package or new package request?**
New request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, it is available in Amazon Linux 2 as part of the amzn2-core repository

**Any additional information you'd like to include. (use-cases, etc)**
apr and apr-util are in the current AL2023 ami's yum repositories, but apr-util-bdb is not.

**Comment by stewartsmith** [comment]
https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2023.html#deprecated-bdb

BDB is deprecated in AL2023, and we are not looking on expanding its footprint. We recommend migrating to other embedded database solutions.
