### ISSUE TITLE
[Package Request] - ncdu

### ISSUE THREAD

**Issue by surfaceflinger** [amazonlinux/amazon-linux-2023#695]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

ncdu (doesn't matter if zig or lts from my perspective) https://dev.yorhel.nl/ncdu

**Is this an update to existing package or new package request?**

new.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

https://repology.org/project/ncdu/versions

**Any additional information you'd like to include. (use-cases, etc)**

`sudo du -a / | sort -n -r | head -n 20` is slow and inefficient pain.

just take a look at this beauty.
![image](https://github.com/amazonlinux/amazon-linux-2023/assets/44725111/97beb54d-0794-4007-a8d8-1a3f13827561)

**Comment by daniejstriata** [comment]
Duplicate: https://github.com/amazonlinux/amazon-linux-2023/issues/75

You can build packages in COPR as I've done. Have a look at how I built ncdu2 and gdu:
https://copr.fedorainfracloud.org/coprs/faramirza/al2023/packages/
By adding your CORP repo you can add packages that built on AL2023 either by your own or from Fedora or Centos Stream.
