### ISSUE TITLE
[Package Request] - mod-php

### ISSUE THREAD

**Issue by bgrcsaid** [amazonlinux/amazon-linux-2023#699]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
mod-php

**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
yes, it is included in AL2

**Any additional information you'd like to include. (use-cases, etc)**
We’ve been running LAMP stack for over a decade now using mod_php
It’s reliable, battle tested and has been working great for us.
All our Production and Development environments using LAMP stack are configured with mod_php
We’re talking probably 50+ instances of Apache server with mod_php running across our EC2s and ECS.
And and another few dozens if we include local development environments running on Docker.
Moving now from mod_php to php-fpm on just configuration and redeployment side alone would be heavy lift. Not to mention we’d have to do some performance testing, configurations tweaking etc.

**Comment by stewartsmith** [comment]
I am certainly not saying this is the way we would go for Amazon Linux, but wanted to add the data point of RHEL having deprecated `mod_php`  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.6_release_notes/deprecated_functionality#deprecated-functionality_dynamic-programming-languages-web-and-database-servers

From looking around, I cannot find any evidence that upstream PHP is removing `mod_php` or even deprecating it, but I may be looking in the wrong place.

**Comment by stewartsmith** [comment]
In [AL2023.5](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html), `php8.3-modphp` [has been added](https://docs.aws.amazon.com/linux/al2023/release-notes/new-AL2023.4-AL2023.5.html).

Hopefully this addition helps you move to AL2023.
