### ISSUE TITLE
[Package Request] - Openldap >= 2.6.2

### ISSUE THREAD

**Issue by pampelix** [amazonlinux/amazon-linux-2023#701]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
OpenLdap in version >= 2.6.2

**Is this an update to existing package or new package request?**
Update to existing package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No

**Any additional information you'd like to include. (use-cases, etc)**
It's a requirement for mssql 2022 installation

**Comment by pampelix** [comment]
Works when specifying the RHEL8 repo of mssql server. sorry for the hassle.

**Comment by stewartsmith** [comment]
Note that AL2023 does guarantee to provide any level of compatibility with RHEL8. Binaries built for RHEL8 may work with how these two OSs are today, but there is no guarantee they will continue to work with any future updates to AL2023 or RHEL8.
