### ISSUE TITLE
[Package Request] - Upgrade dnf default system python and libcap

### ISSUE THREAD

**Issue by rtirkeyDiligent** [amazonlinux/amazon-linux-2023#702]
Our system compliance shows there is vulnerability in dnf default system python version 3..9.16 and libcap version 2.48-2.amzn2023.0.3

Can you please update your default dnf system to the latest. If we try to do manually it breaks dnf and yum.

**Comment by stewartsmith** [comment]
Security fixes are backported by the Amazon Linux team. Details of what CVEs are patched is available on https://alas.aws.amazon.com/alas2023.html and https://explore.alas.aws.amazon.com/ also includes not affected and fix pending CVEs.

For specific issues, contacting AWS Security is the best mechanism.

We keep the system python and DNF components at specific versions to ensure continued compatibility with existing deployments - thus the back porting of fixes.
