### ISSUE TITLE
[Bug] - python3 cflags

### ISSUE THREAD

**Issue by mloubout** [amazonlinux/amazon-linux-2023#705]
**Describe the bug**

It looks like the python3 `cflags` are a bit too restrictive in the docker image `public.ecr.aws/amazonlinux/amazonlinux:2023`

**To Reproduce**

```bash
docker run --rm -it public.ecr.aws/amazonlinux/amazonlinux:2023 /bin/bash
```

then, in the docker image

```bash 
bash-5.2# yum install python3-devel
bash-5.2# python3-config --cflags
-I/usr/include/python3.9 -I/usr/include/python3.9  -Wno-unused-result -Wsign-compare  -O2 -ftree-vectorize  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS  -fstack-protector-strong   -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv  -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG  -O2 -ftree-vectorize  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS  -fstack-protector-strong   -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
```

Some of these flags are very problematic, as for example `nvc` (nvidia compiler) does not support `x86-64-v2` making the amazon linux image unusable as a base for `nvc` based workflows (e.g installing `mpi4py` with `nvc` for cross GPU mpi in python)
**Expected behavior**

- `-march` should not be specified here as it should stay generic enough to be run on any CPU ec2 instance
- There shouldn't be duplicates (e.g `-m64` and `-march` are there twice)

**Additional context**

It is also worth mentioning that `public.ecr.aws/amazonlinux/amazonlinux:2` has issues as well that are more problematic as the `cflags` contains c++ exculive flags that breaks some C compilers

```bash
bash-4.2# python3-config --cflags
-I/usr/include/python3.7m -I/usr/include/python3.7m  -Wno-unused-result -Wsign-compare -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv   -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv
```

where you can see for example `-fexceptions` which is a c++-only cflag

**Comment by stewartsmith** [comment]
An `x86-64-v2` baseline is not unique to Amazon Linux, and third party software will need to adapt in order to remain compatible with modern major Linux distributions.
