### ISSUE TITLE
libnsl.so.1 for AL2023

### ISSUE THREAD

**Issue by jbergman-apiture** [amazonlinux/amazon-linux-2023#735]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
libnsl.so.1

**Is this an update to existing package or new package request?**
This is present in AL2 being used with Amazon Corretto devel jdk 1.8

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes it is

**Any additional information you'd like to include. (use-cases, etc)**
This works in AL2 with just the install of amazon-corretto-jdk-devel.  I installed the same package in AL2023 (via dnf) and this lib is not available.

**Comment by stewartsmith** [comment]
If you mean `libnsl` as in NIS / YellowPages, it's been deprecated and no longer present in AL2023. See https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2.html#deprecated-yp-nis

**Comment by elsaco** [comment]
@jbergman-apiture AL2023 does provide `libnsl`:

```
[ec2-user] [~]$ dnf info libnsl
Last metadata expiration check: 0:04:04 ago on Mon Jun 17 16:58:59 2024.
Available Packages
Name         : libnsl
Version      : 2.34
Release      : 52.amzn2023.0.10
Architecture : x86_64
Size         : 64 k
Source       : glibc-2.34-52.amzn2023.0.10.src.rpm
Repository   : amazonlinux
Summary      : Legacy support library for NIS
---cut---
```

The package contents:

```
[ec2-user] [~]$ rpm -qpl libnsl-2.34-52.amzn2023.0.10.x86_64.rpm
/lib64/libnsl.so.1
/usr/lib/.build-id
/usr/lib/.build-id/57
/usr/lib/.build-id/57/08ab8c539114e5eb89918353206096b8c595e4
```

`libnsl` is not a dependency of `java-1.8.0-amazon-corretto` so it won't be pulled just by installing this package. Run `dnf install libnsl`

**Comment by jbergman-apiture** [comment]
@elsaco Thank you for this. I am going to try and install this now and see what happens.

**Comment by jbergman-apiture** [comment]
@elsaco This seems to have worked.  The update was not immediate, but after sometime (~4 mins) the error went away when the application was invoked.  
Thank You! 🎉
