### ISSUE TITLE
[Bug] systemd-resolved stub listener fails to add 127.0.0.53 as `nameserver`

### ISSUE THREAD

**Issue by shantanugadgil** [amazonlinux/amazon-linux-2023#746]
**Describe the bug**

Until the `releasever` `2023.5.20240624` my /etc/resolv.conf looked like (I know it is actually a symlink)

```
# cat /etc/resolv.conf

### trimmed for brevity ###

nameserver 127.0.0.53
options edns0 trust-ad
search eu-west-1.compute.internal
```

After upgrading to the releasever `2023.5.20240624` it becomes:

```
# cat /etc/resolv.conf

### trimmed for brevity ###

nameserver 10.24.0.2
search eu-west-1.compute.internal

```

NOTE: 10.24.x is my AWS VPC subnet

**To Reproduce**
1. Launch an EC2 using the AMI from the 2023.4.NNN releasever
2. Run `dnf clean all && dnf upgrade --releasever=2023.5.20240624`
3. Reboot the machine. Observe that the `nameserver` in `/etc/resolv.conf` is now pointing to the AWS VPC one and NOT the stub listener
4. This breaks my other workflows.

**Expected behavior**
The file `/etc/resolv.conf' should contain the `nameserver` as the stub listener rather than the AWS VPC one.

**Screenshots**
N/A; file contents pasted above

**Desktop (please complete the following information):**
N/A; not needed

**Smartphone (please complete the following information):**
N/A; not needed.

**Additional context**

**Comment by zcobol** [comment]
@shantanugadgil maybe you should explicitly enable the stub listener.

From `systemd-analyze cat-config systemd/resolved.conf`:
```
# /usr/lib/systemd/resolved.conf.d/resolved-disable-stub-listener.conf
# Amazon Linux systems do not use the stub listener by default, so we
# disable it in order to reduce the runtime footprint and to avoid
# triggering https://bugzilla.redhat.com/show_bug.cgi?id=2115094
[Resolve]
DNSStubListener=no
```

**Comment by shantanugadgil** [comment]
Thanks @zcobol this is not a bug. I'll close this.

In my ami build process, I was removing the file `/usr/lib/systemd/resolved.conf.d/resolved-disable-stub-listener.conf`

The update of `systemd-resolved` was bringing back the file.
