### ISSUE TITLE
[Package Update Request] - Node v20.15.1 (LTS) - security release

### ISSUE THREAD

**Issue by harvey-sg** [amazonlinux/amazon-linux-2023#749]
**Is this an update to existing package or new package request?**
Please update the existing nodejs20 to Node v20.15.1 (LTS)

**Comment by stewartsmith** [comment]
as per https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-AL2023.6.html the current `nodejs20` package version is `20.18.0-1.amzn2023.0.2`
