### ISSUE TITLE
[Bug] - When starting clamd service in AL2023.5, the instance became hang and unreachable

### ISSUE THREAD

**Issue by aw-ac3** [amazonlinux/amazon-linux-2023#750]
**Describe the bug**
When starting clamd service, the instance became hang and unreachable.
It's working fine on AL2023.4 releases.

**To Reproduce**
1. Spin up new AL2023 instance version AL2023.5 (any release version)
2. Install clamav package (dnf install clamav)
3. Run 'freshclam -v'
4. As part of the clam update, it will start/restart the clamd. During this, the instance hangs and became unreachable.

**Expected behavior**
Clamd service runs without issues

**Desktop (please complete the following information):**
 - OS: AL2023 2023.5.20240708
 - Clamav package: clamav-0.103.11-1.amzn2023.0.1.x86_64.rpm 

**Additional context**
Clamav/clamd is working fine on AL2023.4 release, with the same clamav package version

**Comment by stewartsmith** [comment]
What instance type are you using (i.e. does it have enough memory)? Can you see any errors on the console?

**Comment by aw-ac3** [comment]
Thanks Stewart, yeah it was the instance size.
Previously, I've tested with micro and small size, and getting the same issue.
Works fine with medium though.

**Comment by aw-ac3** [comment]
closed
