### ISSUE TITLE
[Feature Request] - OOM killer protection for SSM agent

### ISSUE THREAD

**Issue by erpel** [amazonlinux/amazon-linux-2023#766]
When the system is experiencing memory pressure, I've seen many times that ssm-agent gets killed by the OOM killer. This makes it hard to debug the situation if ssm-agent being killed results in being unable to log in and observe the situation.

I'd like ssm-agent to be run with the same OOM killer protections that is applied to SSH (oom score adjustment -1000).

Alternatives would be to stop using SSM for login and switch to SSH, but this puts additional overhead on us, administering user accounts and ssh keys. SSM session manager is a useful feature that would really benefit from added efforts to increase stability.

This old bug https://bugzilla.redhat.com/show_bug.cgi?id=1010429#c0 contains some details about how it used to work with sshd - especially making sure that user processes spawned by the "protected" server don't inherit the strict protection of oom_score_adj -1000.

**Comment by zcobol** [comment]
@erpel like in the case of `sshd` modifying the `oom_adj` parameter should be left to the application, IMO. 

For the end user there's `choom` command to displays and adjusts Out-Of-Memory killer score setting included in the AL2023.

Sample display of `/proc/2151/oom_adj` for process `2151`, the main PID of amazon-ssh-agent on this instance:
```
[ec2-user@ip-x-x-x-x ~]$ choom -p 2151
pid 2151's current OOM score: 679
pid 2151's current OOM score adjust value: 0
```

**Comment by erpel** [comment]
Sounds very reasonable - sorry I mashed the two amazon projects together. I'll transfer this request to the ssm agent GitHub project.
