### ISSUE TITLE
[Feature Request] - DLAMI for AL2023

### ISSUE THREAD

**Issue by gilvikra** [amazonlinux/amazon-linux-2023#778]
**Is your feature request related to a problem? Please describe.**
We should be required to install nvidia binaries on AMIs ourselves for running deep learning frameworks on AWS infra. 

**Describe the solution you'd like**
we need deep learning AMIs vended for Al2023 just like AL2

**Describe alternatives you've considered**
Installing nvidia drivers ourselves in AL2023 AMI

**Additional context**
Manually installing nvidia drivers ourselves is considered a security risk we do not want address ourselves. It should come pre-baked in AMI just like AL2

**Comment by ZzMonsterr** [comment]
+1 since neuron runtime are not supported for JL2 after neuron runtime 2.20.*

**Comment by limmike** [comment]
DL Base AMI for AL2023 was released on 1st November. Release notes at [https://aws.amazon.com/releasenotes/aws-deep-learning-base-gpu-ami-amazon-linux-2023/](https://aws.amazon.com/releasenotes/aws-deep-learning-base-gpu-ami-amazon-linux-2023/)
