### ISSUE TITLE
[Package Request] - Latest NumPy 2.x.x - The installed package is 1.20.0 released on 30 Jan 2021.

### ISSUE THREAD

**Issue by jdmedeiros** [amazonlinux/amazon-linux-2023#779]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
No

**Is this an update to existing package or new package request?**
Update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes

**Any additional information you'd like to include. (use-cases, etc)**
The latest NumPy package available for AL2023 is 1.20.0 and was released on 20 Jan 2021. Since then we have:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/b2b7427d-cfcb-4fd8-810c-167fcc1d6a30">

NumPy is used by many data analysis packages, like keras, pandas, tensorflow, etc., and forcing 1.20.0 means we are forced to use older versions of those packages.

**Comment by ozbenh** [comment]
For python modules, we tend to generally cater to the dependencies of other RPMs through system python. The expectation is that most customers will use a venv and populate it with whatever python and modules versions are required.

AL2023 aims to provide reasonably long term stability and compatibility, so major updates such as this one are potentially a huge risk for customers or ISVs relying on the package set provided by the base distribution.

For example, another populare "enterprise" distribution also doesn't update its version of NumPy for the system python. I will mark it as package request and the team will still have a look but imho it's unlikely we update that one.

**Comment by jdmedeiros** [comment]
I agree. However that does not apply when you run PySpark in a JupyterHub notebook inside an AWS EMR cluster. PySpark will run on all nodes of the cluster and even if we create a bootstrap step to install whatever packages are needed they will not override the dnf/yum installed packages. Please note note that this does not apply to Python or to IPython; in these cases the bootstrap step will do its job.

If we could manager to run the PySpark kernel inside a virtual environment across all nodes, that would solve the problem, but I have not seen it done anywhere and have not been able to do it so far.

**Comment by ozbenh** [comment]
Hrm... bootstrap pip install in the target user dir won't work ? That's odd ....

**Comment by jdmedeiros** [comment]
It is, but I found out why. AWS is running something after the bootstrap script that overrides _some_ of the Python packages that were installed by the script. This is the bootstrap script:

```
#!/bin/bash
sudo python -m pip install --upgrade boto3 keras numpy pandas pillow pyarrow scikit-learn scipy tensorflow pandas

```

and when I check numpy I have 1.20.0 which causes some of the packages installed by the script to fail, such as pandas, keras, etc., but if I start the cluster without a bootstrap script and after the cluster is up I run the same bootstrap script in the primary and core nodes everything works fine and I have the right versions for all the packages:

<img width="361" alt="image" src="https://github.com/user-attachments/assets/45824c95-f794-43c9-812d-6b651224471a">

I am closing this. Thank you.
