### ISSUE TITLE
[amazon-linux-2023 running on openstack Cloud] - Openstack Cloud provider

### ISSUE THREAD

**Issue by allaboutopensource** [amazonlinux/amazon-linux-2023#781]
**Is your feature request related to a problem? Please describe.**
we are using openstack as a private cloud and we need amazon-linux-2023 machines images to run in our environment. At the moment we are using seed.iso for customising the image by mounting the seed.iso to the vm instance. however for that we need to use the configdrive as datasource. Please add openstack as the datasource in the cloud-init of the image. 
**Describe the solution you'd like**
You can add the datasource as openstack in the cloud-init file so that cloud-init file can pick up the instance metadata from the openstack cloud during the runtime.
**Describe alternatives you've considered**

**Additional context**

**Comment by ozbenh** [comment]
Do you use the qcow2 or OVAs ?

**Comment by zcobol** [comment]
@allaboutopensource have you tried to add your instance customization when launching the image?

![openstack_instance_customization](https://github.com/user-attachments/assets/e0cfba4f-6280-4003-95e4-e0d0540cc05d)

@ozbenh OpenStack handles many image formats, even AMI:

![openstack_amzn_image](https://github.com/user-attachments/assets/02d76c9a-169d-4776-9da1-1217d7db435b)

**Comment by ozbenh** [comment]
We don't particularly want to enable any extra datasource in our ec2 AMIs, if anything to avoid risk and reducing launch speed but we can consider this in our onprem images

**Comment by allaboutopensource** [comment]
we are using qcow2 image downloaded from the official amazon site. 
we tried providing cloud-init user/metadata data using the config tab but its not picking up the cloud-init user data then I had to tried using the seed.iso which worked for me.

**Comment by zcobol** [comment]
@allaboutopensource since you're using the `qcow2` image format, instead of adding `seed.iso` mount the image and edit `/etc/cloud/cloud.cfg` directly.

**Comment by allaboutopensource** [comment]
i tried editing the /etc/cloud/cloud.cfg but it did not picked it up post boot.

**Comment by zcobol** [comment]
@allaboutopensource the `seed.iso` is needed for first launch only. Start `al2023-kvm` image outside of `openstack` and customize it, like set user accounts, passwords, etc.  After, import it into `openstack` and launch a new instance:

 
![al2023-openstack](https://github.com/user-attachments/assets/de71bcf5-2bc7-47be-a5dd-fa53e0a72bce)

**Comment by elsaco** [comment]
@allaboutopensource since you're using `seed.iso` as data source for cloud-init, skip the extra step and use the vm's filesystem to host your data. Edit `/etc/cloud/cloud.cfg.d/02_amazon-onprem.cfg` and add `meta-data` and `user-data` from the `seed.iso`.

```
elsaco@RIPPER:~$ cat /etc/cloud/cloud.cfg.d/02_amazon-onprem.cfg
datasource:
  NoCloud:
    meta-data:
      
    user-data: 
     
```

More details at https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html

**Comment by ozbenh** [comment]
Our biggest concern with enabling this new data source by default is that we aren't equipped for testing it, and we do attempt to test what we ship.

**Comment by elsaco** [comment]
The `nocloud` option will read metadata from the files in `/etc/cloud/*.cfg` or if you want to go by the book use the `/var/lib/cloud/seed/nocloud` path. 

Here's an example I used for testing, none of the `/etc/cloud/` files were modified. The `02_amazon-onprem.cfg`defines an array of data sources with `NoCloud`being first the choice: 

`datasource_list: [ NoCloud, AltCloud, ConfigDrive, OVF, VMware, None ]`

```
[elsaco@amzn-test ~]$ tree /var/lib/cloud/seed/
/var/lib/cloud/seed/
└── nocloud
    ├── meta-data
    └── user-data
```

It's the same data from the `seed.iso`  You will notice this entry in the console `DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net]`

`user-data` content used for testing:

```
[elsaco@amzn-test ~]$ sudo cat /var/lib/cloud/seed/nocloud/user-data
#cloud-config
users:
# A user by the name 'ec2-user' is created in the image by default.
  - default
  - name: elsaco
    plain_text_passwd: amznUser
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
```

`- default` creates the `ec2-user` defined in the `/etc/cloud/cloud.cfg` and the 2nd entry creates user `elsaco` with sudo access. Plain text password is used for testing only. Add a password hash for production images.

Also, if you unset all the data sources in `02_amazon-onprem.cfg` when launching a new instance  it will detect the OpenStack setup and try to use it as a data source, however one need to be configured first.

**Comment by ozbenh** [comment]
At this point, we decided not to add this source by default as we cannot test and thus officially support running open openstack

**Comment by allaboutopensource** [comment]
I dont see the directory under /var/lib/cloud/seed/ location for me its empty in the latest images of al-2023
