### ISSUE TITLE
[Package Request] - PHP8.3.8 or higher

### ISSUE THREAD

**Issue by FrankRovotio** [amazonlinux/amazon-linux-2023#782]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
The patch level 8.38 or higher for PHP resolv several security bugs (injection and openssl), please check

https://www.php.net/ChangeLog-8.php#8.3.8

**dnf info php8.3**
Amazon Linux 2023 repository                                                                                                  32 kB/s | 3.6 kB     00:00
Installed Packages
Name         : php8.3
**Version      : 8.3.7**
Release      : 1.amzn2023.0.1
Architecture : x86_64
Size         : 0.0
Source       : php8.3-8.3.7-1.amzn2023.0.1.src.rpm
Repository   : @System
From repo    : amazonlinux
Summary      : PHP scripting language for creating dynamic web sites
URL          : http://www.php.net/
License      : PHP and Zend and BSD and MIT and ASL 1.0 and NCSA and Boost
Description  : PHP 8.3 is an HTML-embedded scripting language. PHP 8.3 attempts to make it
             : easy for developers to write dynamically generated web pages. PHP 8.3 also
             : offers built-in database integration for several commercial and
             : non-commercial database management systems, so writing a
             : database-enabled webpage with PHP 8.3 is fairly simple. The most common
             : use of PHP 8.3 coding is probably as a replacement for CGI scripts.
             :
             : The php package contains the module (often referred to as mod_php)
             : which adds support for the PHP 8.3 language to Apache HTTP Server when
             : running in prefork mode. This module is deprecated.

**dnf update php8.3 --releasever 2023.5.20240819**
Last metadata expiration check: 0:00:26 ago on Thu Aug 22 18:16:08 2024.
Dependencies resolved.
**Nothing to do.**
Complete!

**Is this an update to existing package or new package request?**
It's update to existing package (today until the version 8.3.7)

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by stewartsmith** [comment]
In the [2023.5.20240903](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240903.html) release PHP 8.3 was updated to 8.3.10.
