### ISSUE TITLE
[Package Request] - xerces-c

### ISSUE THREAD

**Issue by mouraddmeiri** [amazonlinux/amazon-linux-2023#787]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
xerces-c, xalan-c
**Is this an update to existing package or new package request?**
new package request
**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes via EPEL repo
**Any additional information you'd like to include. (use-cases, etc)**

**Comment by stewartsmith** [comment]
There is https://github.com/amazonlinux/amazon-linux-2023/issues/703 open for `xerces-c` already, I'm going to resolve this issue as a duplicate and we can track in https://github.com/amazonlinux/amazon-linux-2023/issues/703
