### ISSUE TITLE
[Package Request] - openvpn

### ISSUE THREAD

**Issue by bennettp123** [amazonlinux/amazon-linux-2023#79]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

openvpn

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2?**

No, but it is available in fedora and EPEL 7.

**Number of users impacted**

One or more 😛

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by pablolibo** [comment]
Hey guys, Any new about this package?

**Comment by mabilbao** [comment]
Hey! any updates on this?

**Comment by jacques** [comment]
Remember to 👍🏻 the ticket above to get an idea of people depending on this package.

**Comment by ozbenh** [comment]
We are still evaluating the possibility of adding this to a future release, we'll communicate here when we come to a conclusion,  👍🏻's do help

**Comment by jonjohnston** [comment]
What is the status of this? AL2 EOL is 6-30-2025 and EPEL repo cannot be used at all in AL2023. If you don't plan to support AL2 after that date, I would hope this and many other packages will be supported so many users can upgrade from AL2 to AL2023. This is basically a blocker for us at my company.

**Comment by dredboi** [comment]
I guess this is going nowhere fast. Seriously what a p.i.t.a.

Thankfully I only wasted about 2 hours setting up an EC2 with "Amazon Linux 2023" - and thanks to this roadblock, I have to ditch that and start again from zero with a different distro.

**Comment by jonjohnston** [comment]
Update on this?

**Comment by matthiaskoerner-ba** [comment]
Any news?

**Comment by ozbenh** [comment]
We dropped the ball last year, I got the team to look at it again, I'm hoping to have a final decision soon

**Comment by Complectia** [comment]
OpenVPN and/or access with full compatibility to the Epel repository for other packages is a must for Amazon Linux 2023.  What is the status of implementing this?  Questions have been ongoing for over two years.  We need this now to plan for migration.

**Comment by ozbenh** [comment]
Still working on this, I'm hoping to have an answer soon

**Comment by ozbenh** [comment]
Support for EPEL is not on our agenda. EPEL contains packages built for RHEL9 which is a different distribution with different set of base libraries etc, it's simply not feasible to guarantee that things built for RHEL9 will work in any reasonable way on AL2023 (some might, by chance, some won't...).

In any case, EPEL is fundamentally *unsupported* software. That means that there should be NO difference from a customer standpoint between downloading something from EPEL and "running random software off the internet" or even building yourself.

That said we are looking carefully at packages requests and balancing that with our team ability to maintain and CVE patch them properly. OpenVPN is still being evaluated by the team at this point.

**Comment by ozbenh** [comment]
The team is now looking at adding OpenVPN to an upcoming AL2023 release

**Comment by Complectia** [comment]
Thank you for the update - I think this will be a very important and widely used addition to the Amazon Linux 2023 repository.

**Comment by ozbenh** [comment]
AL2023.6 is out with
```
Name         : mod_security
Version      : 2.9.7
Release      : 6.amzn2023.0.1
Architecture : aarch64
Size         : 267 k
Source       : mod_security-2.9.7-6.amzn2023.0.1.src.rpm
Repository   : amazonlinux
Summary      : Security module for the Apache HTTP Server
URL          : http://www.modsecurity.org/
License      : Apache-2.0
Description  : ModSecurity is an open source intrusion detection and prevention engine
             : for web applications. It operates embedded into the web server, acting
             : as a powerful umbrella - shielding web applications from attacks.
```
The release notes will be updated shortly

**Comment by beeradmoore** [comment]
I had just finished setting up my Ubuntu EC2 as an OpenVPN server 😅

**Comment by Complectia** [comment]
Excellent!  Thank you.

**Comment by uprinter** [comment]
> AL2023.6 is out with
> 
> ```
> Name         : openvpn
> Version      : 2.6.12
> Release      : 1.amzn2023.0.1
> Architecture : aarch64
> Size         : 660 k
> Source       : openvpn-2.6.12-1.amzn2023.0.1.src.rpm
> Repository   : amazonlinux
> Summary      : A full-featured TLS VPN solution
> URL          : https://community.openvpn.net/
> License      : GPLv2
> Description  : OpenVPN is a robust and highly flexible tunneling application that uses all
>              : of the encryption, authentication, and certification features of the
>              : OpenSSL library to securely tunnel IP networks over a single UDP or TCP
>              : port.  It can use the Marcus Franz Xaver Johannes Oberhumers LZO library
>              : for compression.
> ```
> 
> The release notes will be updated shortly

Hello. I'm checking packages in the latest Docker image (https://hub.docker.com/layers/library/amazonlinux/latest/images/sha256-472e2f28b1f94ce0177f26b216ac6c7f3e29848f4e0a68b7cb044eff41190438?context=explore), but don't see that OpenVPN is included. Am I right?

**Comment by stewartsmith** [comment]
Dockerhub can be a bit behind [ECR](https://gallery.ecr.aws/amazonlinux/amazonlinux), so if you `docker pull public.aws.ecr/amazonlinux/amazonlinux` you'll get the latest.

(the reason behind this delay is that Dockerhub updates come behind a PR on GitHub, while we have API access to just push to ECR)

**Comment by stewartsmith** [comment]
But yes, `openvpn` is in AL2023.6, resolving!
