### ISSUE TITLE
[Package Request] - chromium

### ISSUE THREAD

**Issue by bch36** [amazonlinux/amazon-linux-2023#810]
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

```
Name        : chromium
Arch        : x86_64
Version     : 126.0.6478.114
Release     : 1.el7
Size        : 249 M
Repo        : installed
From repo   : epel
Summary     : A WebKit (Blink) powered web browser that Google doesn't
            : want you to use
URL         : http://www.chromium.org/Home
License     : BSD-3-Clause AND LGPL-2.1-or-later AND Apache-2.0 AND IJG
            : AND MIT AND GPL-2.0-or-later AND ISC AND OpenSSL AND
            : (MPL-1.1 OR GPL-2.0-only OR LGPL-2.0-only)
Description : Chromium is an open-source web browser, powered by WebKit
            : (Blink).
```

**Is this an update to existing package or new package request?**
New package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes, available via EPEL

**Any additional information you'd like to include. (use-cases, etc)**
An alternative to Google Chrome, I used it in headless mode to generate PDFs.

**Comment by stewartsmith** [comment]
Chromium is being tracked in https://github.com/amazonlinux/amazon-linux-2023/issues/356 so I'll resolve this issue as duplicate and we can track in https://github.com/amazonlinux/amazon-linux-2023/issues/356
