### ISSUE TITLE
[Bug] - Building wheels for collected packages fails with "cannot open linker script file"

### ISSUE THREAD

**Issue by DanielCBezerra** [amazonlinux/amazon-linux-2023#814]
**Describe the bug**
Deploying a Python project on Elastic Beanstalk, running the new version "Python 3.12 running on 64bit Amazon Linux 2023/4.2.0", with the following packages in the requirements.txt:
```
libsass >= 0.23.0, < 1.0.0
psycopg2 >= 2.9.9, < 3.0.0
```

Results with the following errors:
```
/usr/bin/ld: cannot open linker script file /root/rpmbuild/BUILD/Python-3.12.7/.package_note-python3.12-3.12.7-1.amzn2023.aarch64.ld: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
```

**To Reproduce**
Easy to reproduce just opening the instance console and doing a:
`pip install psycopg2`

**Expected behavior**
Should install as always did on old versions.

**Comment by ozbenh** [comment]
This is a problem with that Python 3.12 build which doesn't come from us (Amazon Linux) ... it looks like it hasn't been built properly. You should report this to whoever built it (Elastic Beanstalk ?)
