### ISSUE TITLE
[Bug] -No module named 'dnf'

### ISSUE THREAD

**Issue by ravi-bni** [amazonlinux/amazon-linux-2023#821]
**Describe the bug**
In amazon linux2023, after upgrading the python to 3.10, dnf is failing with no module found.

**To Reproduce**
1. wget https://www.python.org/ftp/python/3.10.8/Python-3.10.8.tgz && \
    tar -xf Python-3.10.8.tgz && \
    cd Python-3.10.8 && \
    ./configure --enable-optimizations && \
    make -j $(nproc) && \
    make altinstall
2. bash-5.2# update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.10 1 
3. bash-5.2# python3 -V
    Python 3.10.8
   bash-5.2# dnf update -y
Traceback (most recent call last):
  File "/usr/bin/dnf", line 61, in <module>
    from dnf.cli import main
ModuleNotFoundError: No module named 'dnf'
bash-5.2#

**Expected behavior**
dnf is failing with python upgrade

**Comment by stewartsmith** [comment]
System python modules are built with the system python (3.9). Replacing the system python will mean you don't have those modules available.

There's [a note in the documentation on Python in AL2023](https://docs.aws.amazon.com/linux/al2023/ug/python.html) that warns about the impact of changing `/usr/bin/python3`.

**Comment by ozbenh** [comment]
Some additional information: If you want a separate python, either namespace it or use a venv. Don't ever replace the "system" `/usr/bin/python3`, this will only need to pain and despair. This is true of any Linux distribution
