### ISSUE TITLE
[Bug] - dracut-config-generic - broken dependencies

### ISSUE THREAD

**Issue by danie-dejager** [amazonlinux/amazon-linux-2023#838]
**Describe the bug**
I am updating to the latest release of AL2023 2023.6.20241111 and found that dracut will not update unless I run dnf with "--best --allowerasing"
```
 Problem 1: package dracut-102-3.amzn2023.0.1.x86_64 from amazonlinux conflicts with dracut-config-ec2 < 3.1 provided by dracut-config-ec2-3.0-4.amzn2023.0.2.noarch from @System
  - cannot install the best update candidate for package dracut-config-ec2-3.0-4.amzn2023.0.2.noarch
  - cannot install the best update candidate for package dracut-055-6.amzn2023.0.8.x86_64
 Problem 2: problem with installed package dracut-config-ec2-3.0-4.amzn2023.0.2.noarch
  - package dracut-102-3.amzn2023.0.1.x86_64 from amazonlinux conflicts with dracut-config-ec2 < 3.1 provided by dracut-config-ec2-3.0-4.amzn2023.0.2.noarch from @System
  - package dracut-102-3.amzn2023.0.1.x86_64 from amazonlinux conflicts with dracut-config-ec2 < 3.1 provided by dracut-config-ec2-3.0-4.amzn2023.0.2.noarch from amazonlinux
  - package dracut-config-generic-102-3.amzn2023.0.1.x86_64 from amazonlinux requires dracut = 102-3.amzn2023.0.1, but none of the providers can be installed
  - cannot install the best update candidate for package dracut-config-generic-055-6.amzn2023.0.8.x86_64
```

**To Reproduce**
1. update system with `dnf update --releasever=latest`

**Expected behavior**
should `dracut-config-generic` not be build to replace `dracut-config-ec2`?

**Desktop (please complete the following information):**
 - OS: al2023

**Comment by ag00se** [comment]
Should we update the package using "--best --allowerasing" or will there be a different solution?

**Comment by prayforbirdies** [comment]
Is there a path forward? Qualys is flagging some level 4s we need resolved with the latest release.

**Comment by prayforbirdies** [comment]
> @prayforbirdies you could exclude the `dracut` packages. Run `sudo dnf upgrade --releasever=2023.6.20241111 --exclude=dracut,dracut-config-ec2,dracut-config-generic`
> 
> If you go with the `--allowerasing` option `dracut` and `dracut-config-generic` will be upgraded only. You will lose the `/etc/dracut.conf.d/ec2.conf` file that's part of the `dracut-config-ec2` package.
> 
> The `dracut-config-generic` has the same content in each package version: `hostonly="no"`. See `/usr/lib/dracut/dracut.conf.d/02-generic-image.conf`
> 
> If you launch the latest AL2023 AMI you'll notice that `dracut` packages are still version `055`

Thanks very much. I'll give it a run

**Comment by prayforbirdies** [comment]
worked, all good

**Comment by ozbenh** [comment]
Right it's a mistake on our side, the updated config  missed that release train and is coming up in the next one. The dracut update isn't a security fix and can safely be skipped. Unfortunately repoclosure didn't catch it, we'll have to improve our validation.

So this is just a case of noise in dnf about the package being skipped which can safely be ignored. What is the issue with Qualys ?

**Comment by prayforbirdies** [comment]
> Right it's a mistake on our side, the updated config missed that release train and is coming up in the next one. The dracut update isn't a security fix and can safely be skipped. Unfortunately repoclosure didn't catch it, we'll have to improve our validation.
> 
> So this is just a case of noise in dnf about the package being skipped which can safely be ignored. What is the issue with Qualys ?

No "issue" with qualys really, I just needed to patch and remove old kernels to clear the vulnerabilities - qualys flags old kernels even if they aren't running sadly. I wasn't sure I could skip dracut. I appreciate the help.

**Comment by jerry-d-deng** [comment]
Hello ,

Any update?

This issue caused the instance on my patch manager to be non-compliant.

**Comment by ozbenh** [comment]
Ah yes, we fixed it with the release that just came out.
