### ISSUE TITLE
[Bug] - pnpm process hang up

### ISSUE THREAD

**Issue by muk-ai** [amazonlinux/amazon-linux-2023#840]
**Describe the bug**

After upgrading releasever to `2023.6.20241111` certain commands hang up.

```
$ pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date



^C^C^C^C^C^C^C^C^C^C
```

This `pnpm` process cannot be killed.

```
$ ps auxwww | grep pnpm
ec2-user    5353 17.1  1.0 1994412 170116 pts/0  Dl+  21:55   0:04 node /home/ec2-user/.nvm/versions/node/v20.9.0/bin/pnpm install
ec2-user    5511  0.0  0.0 222316  2068 pts/1    S+   21:56   0:00 grep --color=auto pnpm
$ sudo kill -KILL 5353
$ sudo kill -KILL 5353
$ sudo kill -KILL 5353
$ ps auxwwww | grep pnpm
ec2-user    5353 11.1  1.0 1994412 170116 pts/0  Dl+  21:55   0:04 node /home/ec2-user/.nvm/versions/node/v20.9.0/bin/pnpm install
ec2-user    5531  0.0  0.0 222316  2032 pts/1    S+   21:56   0:00 grep --color=auto pnpm
```

There seems to be no load. The process just stops responding.

**To Reproduce**

~~execute `pnpm install`~~
https://github.com/amazonlinux/amazon-linux-2023/issues/840#issuecomment-2481890440

**Expected behavior**
Usually, this command takes only a few seconds.

**Additional context**

```
$ hostnamectl
 Static hostname: ip-172-16-1-250.ap-northeast-1.compute.internal
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: ec207c3edce5552d95110b9be794801c
         Boot ID: 2e69151397344fbc8a0c09aba812c8a4
  Virtualization: amazon
Operating System: Amazon Linux 2023.6.20241111
     CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2023
          Kernel: Linux 6.1.115-126.197.amzn2023.x86_64
    Architecture: x86-64
 Hardware Vendor: Amazon EC2
  Hardware Model: t3a.xlarge
Firmware Version: 1.0
```

**Comment by elsaco** [comment]
@muk-ai look at the state of your process, the 8th column in the `ps` output. Your process is in `Dl+` state, `D` meaning `uninterruptible sleep, processes that cannot be killed or interrupted with a signal`. Sending a `SIGKILL` won't kill it. Reboot your system!

**Comment by muk-ai** [comment]
@elsaco 
Thanks for letting me know. After rebooting, the process goes away, but the problem reproduces again.

**Comment by muk-ai** [comment]
The minimum reproduction method is this.

1.  install node.js
```
$ sudo dnf install nodejs20
```
2. put package.json
```
{
  "name": "tmp.fnn0IclzCx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "karma": "~6.4.0"
  }
}
```
3. install packages
```
$ npm-20 install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
⠦
⠏
⠹
⠸
⠴
⠧
⠧^C^C^C^C^C^C^C^C^C
```
If it does not reproduce, please try deleting `node_modules` and run `npm-20 install` several times.

**Comment by rrehbein** [comment]
We ran into the same issue with `ami-0ff6f6818640fabe3` and the symptoms are very similar to https://github.com/nodejs/node/issues/55587 which links back to a missing commit https://github.com/gregkh/linux/commit/f4ce3b5d26ce149e77e6b8e8f2058aa80e5b034e regarding io_uring ovelflow.

**Comment by kureaken** [comment]
We also encountered the same problem.

1. kernel version

`
[ec2-user@amazonlinux2023 ~]$ uname -a
Linux amazonlinux2023 6.1.115-126.197.amzn2023.aarch64 #1 SMP Tue Nov  5 17:36:31 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
[ec2-user@amazonlinux2023 ~]$

`

2 . npm install

`
[ec2-user@amazonlinux2023 ~]$ npm-20 install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
⠴^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
`

**Comment by andreasstieger** [comment]
Thank you reporters. This is is indeed the Linux kernel issue mentioned by Ray. Running `npm` with [`UV_USE_IO_URING=0`](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue) in the environment works around the issue, the upstream fix will be in the next release (let me grab the date...)

**Comment by andreasstieger** [comment]
Amazon Linux 2023 release `2023.6.20241111.0` with the Linux kernel `6.1.115-126.197.amzn2023` is affected by an [issue in the `io_uring` subsystem](https://lore.kernel.org/io-uring/3d913aef-8c44-4f50-9bdf-7d9051b08941@app.fastmail.com/T/#m57570b5f8f2fc00d5a17cfe18ffeeba9fc23a43d). It can be observed when running the `npm` cli, and results in hung processes in uninterruptible sleep state (“`D`” in `ps` output).

To work around the issue, temporarily disable the `libuv` use of `io_uring` by setting the corresponding environment variable [`UV_USE_IO_URING=0`](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue). Using an earlier Linux kernel version also works around the issue. A correction will be made available by December 9, 2024.

**Comment by muk-ai** [comment]
@andreasstieger Thanks for sharing the cause and workaround. :+1:

**Comment by dliberatore-th** [comment]
I'm seeing this in the base npm package as well. You don't even need a package.json, you can simply try to install a new npm with `npm install -g npm@<VERSION>` and you'll get this behavior.

**Comment by bobziuchkovski** [comment]
@dliberatore-th That's correct. @andreasstieger 's [comment](https://github.com/amazonlinux/amazon-linux-2023/issues/840#issuecomment-2485782075) indicated this will affect nodejs in general. That [UV_USE_IO_URING=0](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue) option he linked to is documented for nodejs itself.

**Comment by dliberatore-th** [comment]
Confirmed, that workaround fixes npm! Thank you!

**Comment by infakt-HNP** [comment]
It also causes that yarn install doesn't work on new AMI. Thank you for a hint.

**Comment by januszm** [comment]
Could we also bump `node` to v20 in the next Linux release?

**Comment by waynee-tw** [comment]
Confirmed, that workaround fixes npm installing pm2! Thank you!

**Comment by sylr** [comment]
Hi @andreasstieger 👋 

> To work around the issue, temporarily disable the libuv use of io_uring by setting the corresponding environment variable [UV_USE_IO_URING=0](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue). Using an earlier Linux kernel version also works around the issue. A correction will be made available by December 9, 2024.

I'm wondering when the fix will be published ? it seems the latest kernel version available is still 6.1.115-126.197.amzn2023.

Regards.

**Comment by andreasstieger** [comment]
Thanks for asking, I checked this morning my TZ and this is released. This is `kernel-6.1.119-129.201.amzn2023`
For more details see https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.6.20241209.html

**Comment by squaredx** [comment]
As far as I can tell, there isn't an updated AMI for elastic beanstalk instances. Is there anyway we can get the patched kernel in our EB environments or do we just have to wait for Amazon to publish the new images?

**Comment by muk-ai** [comment]
After upgrading releasever to `2023.6.20241212`, I have confirmed that the issue has been resolved.
Thanks to everyone's reports and to the amazon linux team for the fix.
