### ISSUE TITLE
[Bug] - al2023 docker image won't run on raspberry pi 4

### ISSUE THREAD

**Issue by zcobol** [amazonlinux/amazon-linux-2023#850]
**Describe the bug**
pull public.ecr.aws/amazonlinux/amazonlinux:minimal

**To Reproduce**
1. run docker image

**Expected behavior**
al2023 container to run

**Additional context**
`Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor
compliant with at least ARM architecture 8.2-a with Cryptographic
 extensions. On EC2 this is Graviton 2 or later`

**Hardware**
RPi4  with `ARM Cortex-A72` processor

**Comment by stewartsmith** [comment]
The CPU requirements for ARM are documented here: https://docs.aws.amazon.com/linux/al2023/ug/system-requirements.html#system-requirements-cpu

The Pi 4 doesn't meet the minimum CPU requirements, but a Pi 5 does.
