### ISSUE TITLE
[Package Request] - ocl-icd and opencl-filesystem

### ISSUE THREAD

**Issue by kmittman** [amazonlinux/amazon-linux-2023#86]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
ocl-icd and opencl-filesystem

NOTE: `opencl-filesystem` contains two directories, zero files
```
/etc/OpenCL
/etc/OpenCL/vendors
```

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2?**
Most likely

**Number of users impacted**
Needed for NVIDIA GPU support

**Comment by kmittman** [comment]
Also need `dkms` https://github.com/amazonlinux/amazon-linux-2022/issues/77

**Comment by nmeyerhans** [comment]
These packages are both included in current AL2023 RC releases:

```
[ec2-user@ip-10-0-0-110 ~]$ dnf list ocl-icd opencl-filesystem
Last metadata expiration check: 0:00:20 ago on Mon Mar 13 17:50:25 2023.
Installed Packages
ocl-icd.x86_64                      2.3.1-2.amzn2023.0.2            @amazonlinux
opencl-filesystem.noarch            1.0-15.amzn2023.0.3             @amazonlinux
```
