### ISSUE TITLE
[Bug] - /usr/bin/imds fails with printf format in user-data

### ISSUE THREAD

**Issue by vflaux** [amazonlinux/amazon-linux-2023#862]
**Describe the bug**
`/usr/bin/imds` print the result using a `printf` of the returned value from imds endpoint.
Depending of the content it may crash whith ``/usr/bin/imds: line 40: printf: `X': invalid format character``.

**To Reproduce**
1. Create an instance with user-data containing "%D" (ex: `echo "%D"`)
2. On the instance, run `imds latest/user-data`

**Expected behavior**
The full user-data without error or formating.

**Additional context**
I have an URL in my user-data with "%3D" ("=") and it causes imds to fail.

I do not think that calling `printf "$(cat $OUTPUT_FILE)\n"` with no additional arguments is needed. A simple `cat $OUTPUT_FILE; echo` should be sufficient.

**Comment by ozbenh** [comment]
Where does `/usr/bin/imds` comes from ? I don't think we ship this, or if we do I can't find it :-)

**Comment by vflaux** [comment]
My mistake, it looks like it's actually shipped in eks ami (https://github.com/awslabs/amazon-eks-ami/blob/main/templates/shared/runtime/bin/imds).
I'll open an issue there.
