### ISSUE TITLE
[Package Request] - Certbot

### ISSUE THREAD

**Issue by hipwebdesign** [amazonlinux/amazon-linux-2023#87]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
Certbot (via [snapd](https://certbot.eff.org/instructions?ws=apache&os=fedora)?)

**Is this an update to existing package or new package request?**
New package request.

**Is this package available in Amazon Linux 2?**
Yes, via EPEL 7 and amazon-linux-extras.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by walmartshopper** [comment]
I would like this as well.  It can be installed with "pip install certbot" but then it doesn't come with the systemd timer for certificate renewal, and I have to remember to update it manually.  Adding it to the official repo would benefit many users running AL2022 as a web server and using free certificates from Let's Encrypt.

**Comment by virshu** [comment]
Like @walmartshopper suggested, I was able to install `certbot` through `pip`; however, I still wasn't able to install `certbot-apache`. It looks like there is python version incompatibility. 

python3.9 is installed; but certbot requires python3.6

```
 Problem: conflicting requests
  - nothing provides python3.6dist(python-augeas) needed by python3-certbot-apache-1.22.0-1.el8.noarch
```

**Comment by ozbenh** [comment]
This works for installing `certbot` today via `pip`:
```
sudo dnf install python3-pip python3-pyOpenSSL
pip install certbot
```
Note: the pre-install of `python3-pyOpenSSL` is important, otherwise it tries to bring one from PyPi which is too new for the version of `python3-cryptography` that we ship, so it goes installing an even newer one which breaks `awscli-2` dependencies (not in a fatal way but it's a rabbit hole you don't want to get into).

We are still considering packaging it but due to some dependency mess, it might take a bit longer than expected.

**Comment by limmike** [comment]
Please refer to #444

**Comment by nmeyerhans** [comment]
We expect to include Certbot in an upcoming AL2023 release. I don't have a specific ETA right now but we are aiming to have it available before the end of 2023.

**Comment by sambo2021** [comment]
sudo dnf install -y augeas-libs
sudo python3 -m venv /opt/certbot/
sudo /opt/certbot/bin/pip install --upgrade pip
sudo /opt/certbot/bin/pip install certbot certbot-nginx
sudo ln -s /opt/certbot/bin/certbot /usr/bin/certbot

**Comment by ozbenh** [comment]
`certbot` has now been added to the just released AL2023.3
