### ISSUE TITLE
[Feature Request] - TCMU Userspace Kernel Module for Amazon EKS optimised AMI

### ISSUE THREAD

**Issue by cvlc** [amazonlinux/amazon-linux-2023#88]
**Is your feature request related to a problem? Please describe.**
Several storage fabric systems use LinuxIO/TCM in user-space in order to provide abstracted block storage access to applications, eg. for Kubernetes and containerised workloads. Without this feature, these systems won't work at all and we have to use alternative machine images. The benefit of TCMU is that it enables developers more flexibility in the way that underlying block storage is handled using technologies native to the Linux kernel.

**Describe the solution you'd like**
`CONFIG_TCM_USER2=m` set in `kernel.config` for Amazon Linux for EKS 2022 in order to build the kernel module `target_core_user` that currently isn't included in Amazon EKS optimised (and is currently included in non-EKS-optimised AMIs and Ubuntu EKS Optimised AMIs).

**Describe alternatives you've considered**
The alternative is to use Canonical Ubuntu, Flatcar Container Linux, Bottlerocket or other AMIs that provide this feature. 

**Additional context**
[Documentation on TCMU](https://www.kernel.org/doc/html/latest/target/tcmu-design.html)
[Slide deck from Redhat on TCMU](https://events.static.linuxfound.org/sites/events/files/slides/tcmu-bobw_0.pdf) 
[Merged Bottlerocket PR](https://github.com/bottlerocket-os/bottlerocket/pull/1953)

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by cvlc** [comment]
Thanks @liesenml, I'd be happy to assist in any way!

**Comment by AdamWallek** [comment]
Hi @liesenml, are there any updates on this?

**Comment by Arau** [comment]
Hi, 

is there any progress on this issue?

Thank you

**Comment by HarishKM7** [comment]
Hi @liesenml (& others at AWS). I'm Harish from [MYCOM OSI](https://mycom-osi.com/). We're eagerly awaiting the implementation of this feature in Amazon Linux, especially since the lack of these kernel modules is blocking us from adopting Kubernetes storage management solutions like [Ondat](https://www.ondat.io/). Please prioritize this request! 🙏🏻

**Comment by shapirov103** [comment]
@abuehaze14 and AWS team: could please share your ETA for this feature? We have AWS partners waiting on it (EKS Storage CSI drivers). Also if you could share any dependency issues (if any) that would be helpful as well.

**Comment by abuehaze14** [comment]
Hey, This is currently available on all our latest AL2 5.4 & 5.10 and 5.15 kernels, We are currently integrating this module to AL2022 as well and I will provide the exact ETA very soon.

**Comment by abuehaze14** [comment]
Hey, This module is currently available on our latest AL2022 AMI so we should be good on all AL2 supported kernel versions 5.4 & 5.10 and 5.15 as well as AL2022 5.15 kernel.

**Comment by Arau** [comment]
Hi @abuehaze14,

We have been trying to use the AMI to test, etc. I can see that the AMI has the modules, which is great. I thought that EKS default use of the AmazonLinux2 would point to the latest, however, I don't see the changes applied when using EKS clusters. Do you know when or how the changes are ported, or EKS reference to the new images applied? 

I apologise if you are not the person to ask this.

**Comment by nmeyerhans** [comment]
Hi @Arau. The kernel support is enabled in AL2023, so I'm going to resolve this issue. EKS is working on support for AL2023 in their AMIs. You can track their availability at https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html and https://github.com/awslabs/amazon-eks-ami
